### ISSUE TITLE
Unable to connect to serviceMqttException

### ISSUE THREAD

**Issue by gprsphone** [Azure/azure-iot-sdk-java#102] opened 2017-06-09 07:48 UTC
Hi,

I meet issue while run azure-iot-sdk-java/device/iot-device-samples/android-sample on latest commit,
commit: 918ace9615c874727889526d0bd5900760b89d69

- **OS and version used:** <VERSION> 
Build environment is: 
* Windows 10
* Android Stdio 2.3.2
* Code base on azure-iot-sdk-java/device/iot-device-samples/android-sample, nothing changed except 
connString and deviceId
* com.android.tools.build:gradle:2.3.0

- **Java runtime used:** <VERSION> 
embedded jdk: openjdk version "1.8.0_112-release"

- **SDK version used:** <VERSION> 
com.microsoft.azure.sdk.iot:iot-device-client:1.1.25
Android SDK23

# Description of the issue:
issue is: if I use MQTT protocol, connection to IoT hub will fail with Exception while opening IoTHub connection: java.io.IOException: Unable to connect to serviceMqttException
if I use HTTPS protocol, connection to IoT hub will not report issue but actually, no data was received at IoT Hub, and we can't see button (Like introduced other issue)

Here we focus on MQTT issue to describe:

# Code sample exhibiting the issue:
commit: 918ace9615c874727889526d0bd5900760b89d69
nothing changed except connString and deviceId
Same connString and deviceId can be used to connect to IoT hub if we use Node.js, so connString and deviceId should be OK

# Console log of the issue:
06-09 14:19:57.808 12024-12024/com.iothub.azure.microsoft.com.androidsample W/ActivityThread: Application com.iothub.azure.microsoft.com.androidsample is waiting for the debugger on port 8100...
06-09 14:19:57.818 12024-12024/com.iothub.azure.microsoft.com.androidsample I/System.out: Sending WAIT chunk
06-09 14:19:58.138 12024-12030/com.iothub.azure.microsoft.com.androidsample I/art: Debugger is active
06-09 14:19:58.228 12024-12024/com.iothub.azure.microsoft.com.androidsample I/System.out: Debugger has connected
06-09 14:19:58.228 12024-12024/com.iothub.azure.microsoft.com.androidsample I/System.out: waiting for debugger to settle...
06-09 14:19:58.428 12024-12024/com.iothub.azure.microsoft.com.androidsample I/System.out: waiting for debugger to settle...
06-09 14:19:58.628 12024-12024/com.iothub.azure.microsoft.com.androidsample I/System.out: waiting for debugger to settle...
06-09 14:19:58.828 12024-12024/com.iothub.azure.microsoft.com.androidsample I/System.out: waiting for debugger to settle...
06-09 14:19:59.038 12024-12024/com.iothub.azure.microsoft.com.androidsample I/System.out: waiting for debugger to settle...
06-09 14:19:59.228 12024-12024/com.iothub.azure.microsoft.com.androidsample I/System.out: waiting for debugger to settle...
06-09 14:19:59.428 12024-12024/com.iothub.azure.microsoft.com.androidsample I/System.out: waiting for debugger to settle...
06-09 14:19:59.628 12024-12024/com.iothub.azure.microsoft.com.androidsample I/System.out: waiting for debugger to settle...
06-09 14:19:59.828 12024-12024/com.iothub.azure.microsoft.com.androidsample I/System.out: debugger has settled (1496)
06-09 14:19:59.838 12024-12024/com.iothub.azure.microsoft.com.androidsample W/System: ClassLoader referenced unknown path: /data/app/com.iothub.azure.microsoft.com.androidsample-1/lib/arm
06-09 14:19:59.848 12024-12024/com.iothub.azure.microsoft.com.androidsample D/ContextRelationManager: ContextRelationManager() : FEATURE_ENABLED=true
06-09 14:19:59.848 12024-12024/com.iothub.azure.microsoft.com.androidsample D/RelationGraph: garbageCollect()
06-09 14:19:59.888 12024-12024/com.iothub.azure.microsoft.com.androidsample D/RelationGraph: garbageCollect()
06-09 14:20:00.068 12024-12024/com.iothub.azure.microsoft.com.androidsample W/System.err: log4j:WARN No appenders could be found for logger (com.microsoft.azure.sdk.iot.device.DeviceClientConfig).
06-09 14:20:00.068 12024-12024/com.iothub.azure.microsoft.com.androidsample W/System.err: log4j:WARN Please initialize the log4j system properly.
06-09 14:20:00.068 12024-12024/com.iothub.azure.microsoft.com.androidsample W/System.err: log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
06-09 14:20:00.388 12024-12024/com.iothub.azure.microsoft.com.androidsample I/System.out: Exception while opening IoTHub connection: java.io.IOException: Unable to connect to serviceMqttException
06-09 14:20:00.388 12024-12024/com.iothub.azure.microsoft.com.androidsample W/System.err: java.io.IOException: Unable to connect to serviceMqttException
06-09 14:20:00.388 12024-12024/com.iothub.azure.microsoft.com.androidsample W/System.err:     at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttIotHubConnection.open(MqttIotHubConnection.java:138)
06-09 14:20:00.388 12024-12024/com.iothub.azure.microsoft.com.androidsample W/System.err:     at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttTransport.open(MqttTransport.java:83)
06-09 14:20:00.388 12024-12024/com.iothub.azure.microsoft.com.androidsample W/System.err:     at com.microsoft.azure.sdk.iot.device.DeviceClient.open(DeviceClient.java:227)
06-09 14:20:00.388 12024-12024/com.iothub.azure.microsoft.com.androidsample W/System.err:     at com.iothub.azure.microsoft.com.androidsample.MainActivity.SendMessage(MainActivity.java:46)
06-09 14:20:00.388 12024-12024/com.iothub.azure.microsoft.com.androidsample W/System.err:     at com.iothub.azure.microsoft.com.androidsample.MainActivity.onCreate(MainActivity.java:25)
06-09 14:20:00.388 12024-12024/com.iothub.azure.microsoft.com.androidsample W/System.err:     at android.app.Activity.performCreate(Activity.java:6904)
06-09 14:20:00.388 12024-12024/com.iothub.azure.microsoft.com.androidsample W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1136)
06-09 14:20:00.388 12024-12024/com.iothub.azure.microsoft.com.androidsample W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3267)
06-09 14:20:00.388 12024-12024/com.iothub.azure.microsoft.com.androidsample W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3416)
06-09 14:20:00.388 12024-12024/com.iothub.azure.microsoft.com.androidsample W/System.err:     at android.app.ActivityThread.access$1100(ActivityThread.java:229)
06-09 14:20:00.388 12024-12024/com.iothub.azure.microsoft.com.androidsample W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821)
06-09 14:20:00.388 12024-12024/com.iothub.azure.microsoft.com.androidsample W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
06-09 14:20:00.388 12024-12024/com.iothub.azure.microsoft.com.androidsample W/System.err:     at android.os.Looper.loop(Looper.java:148)
06-09 14:20:00.388 12024-12024/com.iothub.azure.microsoft.com.androidsample W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7326)
06-09 14:20:00.388 12024-12024/com.iothub.azure.microsoft.com.androidsample W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
06-09 14:20:00.388 12024-12024/com.iothub.azure.microsoft.com.androidsample W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
06-09 14:20:00.388 12024-12024/com.iothub.azure.microsoft.com.androidsample W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
06-09 14:20:00.388 12024-12024/com.iothub.azure.microsoft.com.androidsample I/System.out: {"deviceId":"myFirstNodeDevice","messageId":0,"temperature":24.238257002252784,"humidity":40.78973073255939}
06-09 14:20:02.398 12024-12024/com.iothub.azure.microsoft.com.androidsample I/System.out: {"deviceId":"myFirstNodeDevice","messageId":1,"temperature":21.819412320250272,"humidity":47.176982216433984}
06-09 14:20:04.408 12024-12024/com.iothub.azure.microsoft.com.androidsample I/System.out: {"deviceId":"myFirstNodeDevice","messageId":2,"temperature":29.33790992335038,"humidity":37.413535268821384}

Please let us know if any other information was needed.

thanks!
Best Regards

**Comment by prmathur-microsoft** [comment] 2017-07-11 18:22
We are investigating this issue. We will update you as soon as we have any information

**Comment by prmathur-microsoft** [comment] 2017-07-13 20:08
We tried to repro this issue at our end, however we cannot reproduce it. Can you please help us by providing the steps to reproduce this issue ?

**Comment by gprsphone** [comment] 2017-07-14 09:26
Hi Prmathur,

Thanks for your help.

As I said before, I use com.microsoft.azure.sdk.iot:iot-device-client:1.1.25, this issue will happen, after some more try, I found if I use com.microsoft.azure.sdk.iot:iot-device-client:1.2.28, it can work now.

Thank!

Best regards
Philip

**Comment by prmathur-microsoft** [comment] 2017-07-14 18:18
That is good to hear that you were able to work with 1.2.28 version of SDK and it resolves your error. I'm closing this issue for now but feel free to reopen if you see any further issues.

**Closed by prmathur-microsoft** 2017-07-14 18:18 UTC
Labels: Android, investigation-required
