### ISSUE TITLE
Android - Provisioning service fails when minify enabled.

### ISSUE THREAD

**Issue by devzeze** [Azure/azure-iot-sdk-java#1032] opened 2020-12-23 13:03 UTC
# Description of the issue:
Its possible to build the app with latest iot-device-client and provisioning service with minify enabled however when running provisioning it fails at runtime.
Note that device client is able to register.

# Code sample exhibiting the issue:

    plugins {
        id 'com.android.application'
    }
    android {
        compileSdkVersion 30
        buildToolsVersion "30.0.0"

    defaultConfig {
        applicationId "com.demo.iottwin"
        minSdkVersion 26
        targetSdkVersion 30
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        multiDexEnabled true
    }

    buildTypes {
        debug {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    dependencies {

    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'com.google.android.material:material:1.2.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.4'
    testImplementation 'junit:junit:4.+'
    androidTestImplementation 'androidx.test.ext:junit:1.1.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'

    //  IoT
    implementation('com.microsoft.azure.sdk.iot:iot-device-client:1.28.0') {
        exclude module: 'azure-storage'
    }
    implementation 'com.microsoft.azure.sdk.iot.provisioning:provisioning-device-client:1.8.5'
    implementation 'com.microsoft.azure.sdk.iot.provisioning.security:x509-provider:1.1.4'
}

# Console log of the issue:

    2020-12-23 13:56:04.031 17439-17439/com.demo.iottwin E/iotdemo: iotregistering IotHubConnectionStatus CONNECTED
    2020-12-23 13:56:04.941 17439-17439/com.demo.iottwin E/iotdemo: iotprovisioning provisioningDeviceClientStatus: PROVISIONING_DEVICE_STATUS_ERROR
    2020-12-23 13:56:04.946 17439-17439/com.demo.iottwin E/iotdemo: iotprovisioning Exception provisioning 
    java.util.concurrent.ExecutionException: b.c.a.b.a.c.a.f.d.b: Service error: null - null - TrackingId: null
    
        at java.util.concurrent.FutureTask.report(FutureTask.java:123)
        at java.util.concurrent.FutureTask.get(FutureTask.java:207)
        at b.c.a.b.a.c.a.f.f.d.b(:115)
        at b.c.a.b.a.c.a.f.f.d.call(:296)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: b.c.a.b.a.c.a.f.d.b: Service error: null - null - TrackingId: null
    
        at b.c.a.b.a.c.a.f.f.e.d(:132)
        at b.c.a.b.a.c.a.f.f.e.a(:297)
        at b.c.a.b.a.c.a.f.f.e.e(:340)
        at b.c.a.b.a.c.a.f.f.e.call(:36)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 

I tried to found proguard rules but couldnt find it.
I android sample app file is empty.
https://github.com/Azure/azure-iot-sdk-java/blob/master/device/iot-device-samples/android-sample/app/proguard-rules.pro

If you need any more details please let me know. Issue is easy to reproduce.

AB#9020823

**Comment by timtay-microsoft** [comment] 2021-01-04 19:32
Can you provide a bit more context on the code that you are running? Is it just using the provisioning device client to register a device, and then using the IoT Hub device client to try to send messages?

**Comment by devzeze** [comment] 2021-01-07 07:40
Hi,

yes thats it. This is just a demo app to check the status of minification.

Of course because I have provisioning and then device client registration and because provision don't work with minification, to test I had following approach:

1. Run provisioning **without** minification. OK and I saved the deviceId.
2. Run device client registration **without** minification with previous deviceId and it was OK.
3. Run provisioning **with** minification. NOK. Error in issue.
2. Run device client registration **with** minification with previous saved deviceId and it was OK.

So it seems issue is only with provisioning.

**Comment by devzeze** [comment] 2021-01-07 08:02
Here you have the mapping file.

[mapping.txt](https://github.com/Azure/azure-iot-sdk-java/files/5780290/mapping.txt)

**Comment by timtay-microsoft** [comment] 2021-01-15 19:59
Can you share what protocol (amqp/amqp_ws/mqtt/mqtt_ws/https) you used for your provisioning device client, and can you share what type of attestation your enrollment uses?

**Comment by timtay-microsoft** [comment] 2021-01-15 20:09
Also, do you have a proguard file that you are using, or is your proguard file also blank?

**Comment by timtay-microsoft** [comment] 2021-01-16 00:58
So far my suspicion is on how gson and proguard are mixing on serializing enums. See [here](https://hanru-yeh.medium.com/gson-will-crash-at-enum-fields-in-custom-class-with-proguard-bbcf5ad1b623) for more details.

Does adding "-keepclassmembers enum * { *; }" to your proguard rules file help you at all?

**Comment by devzeze** [comment] 2021-01-18 09:16
Hi,

Regarding this questions:

Protocol: MQTT_WS
Attestation: Certificate
Enrollment: Enrollment Groups

I also tested with -keepclassmembers enum * { *; } and other variants like -keepclassmembers enum ** { *; } and this don't fix the problem.

Because documentation for minification is not good I opted to use @Keep annotation in other dependencies I have but they are for Android only and I makes no sense in your case.

https://developer.android.com/reference/androidx/annotation/Keep

**Comment by timtay-microsoft** [comment] 2021-01-19 19:45
I'm seeing better results so far when I include

```
-keep class com.microsoft.azure.sdk.iot.provisioning.device.internal.parser.RegistrationOperationStatusParser { *; }
-keep class com.microsoft.azure.sdk.iot.provisioning.device.internal.parser.DeviceRegistrationResultParser { *; }
```

in the proguard rules files. From my digging, these json parser classes appear to always return null in their getters when proguard is enabled, strangely. This is despite the fact that the fields themselves are not null.

Can you give the above a try?

**Comment by timtay-microsoft** [comment] 2021-01-19 23:12
Other than the above, I also bumped up the Gradle version

```
buildscript {
    dependencies {
        classpath 'net.sf.proguard:proguard-gradle:6.2.2'
    }
}
``` 

And added a dependency to a later version of proguard
```
buildscript {
    dependencies {
        classpath 'net.sf.proguard:proguard-gradle:6.2.2'
    }
}
```

I went ahead and pushed a branch that should be useful for reference. On this branch, I modified our android sample to include device provisioning and to minify using the "getDefaultProguardFile('proguard-android-optimize.txt')" rules.

See the sample [here](https://github.com/Azure/azure-iot-sdk-java/blob/timtay/provisioningAndroidProguardSample/device/iot-device-samples/android-sample/app/src/main/java/com/iothub/azure/microsoft/com/androidsample/MainActivity.java), its gradle file [here](https://github.com/Azure/azure-iot-sdk-java/blob/timtay/provisioningAndroidProguardSample/device/iot-device-samples/android-sample/app/build.gradle) and the proguard rules file [here](https://github.com/Azure/azure-iot-sdk-java/blob/timtay/provisioningAndroidProguardSample/device/iot-device-samples/android-sample/app/proguard-rules.pro)

**Comment by timtay-microsoft** [comment] 2021-01-20 18:21
Just for additional context, we don't officially support minifying our libraries, so this likely isn't the only issue that would stem from minifying. We may re-evaluate this standard in the future though. The above is moreso a temporary workaround in the meantime.

**Comment by devzeze** [comment] 2021-01-21 10:31
Hi I run both my demo app and also yours azure android sample.

The results are pretty much the same.


My sample.

`2021-01-21 11:23:16.215 18655-18711/com.demo.iottwin E/iotdemo: Date of teste 
2021-01-21 11:23:16.218 18655-18655/com.demo.iottwin E/iotdemo: iotprovisioning provisioningDeviceClientStatus: PROVISIONING_DEVICE_STATUS_ERROR
2021-01-21 11:23:16.219 18655-18655/com.demo.iottwin E/iotdemo: iotprovisioning Exception provisioning 
    java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(FutureTask.java:123)
        at java.util.concurrent.FutureTask.get(FutureTask.java:207)
        at b.c.a.b.a.c.a.f.f.d.e(:149)
        at b.c.a.b.a.c.a.f.f.d.b(:195)
        at b.c.a.b.a.c.a.f.f.d.call(:299)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: java.lang.NullPointerException
        at com.microsoft.azure.sdk.iot.provisioning.device.internal.parser.RegistrationOperationStatusParser.createFromJson(:90)
        at b.c.a.b.a.c.a.f.f.i.b(:120)
        at b.c.a.b.a.c.a.f.f.i.a(:152)
        at b.c.a.b.a.c.a.f.f.i.call(:22)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923) 
`


And your sample app.

`2021-01-21 11:19:30.582 18530-18572/com.iothub.azure.microsoft.com.androidsample W/System.err: b.b.a.b.a.c.b.e.a: java.security.cert.CertificateException: java.lang.NullPointerException: Attempt to invoke virtual method 'byte[] c.b.j.i.b.b.a()' on a null object reference
2021-01-21 11:19:30.582 18530-18572/com.iothub.azure.microsoft.com.androidsample W/System.err:     at b.b.a.b.a.c.b.f.a.<init>(:76)
2021-01-21 11:19:30.582 18530-18572/com.iothub.azure.microsoft.com.androidsample W/System.err:     at com.iothub.azure.microsoft.com.androidsample.MainActivity$b.a(:84)
2021-01-21 11:19:30.582 18530-18572/com.iothub.azure.microsoft.com.androidsample W/System.err:     at com.iothub.azure.microsoft.com.androidsample.MainActivity$b.doInBackground(:71)
2021-01-21 11:19:30.582 18530-18572/com.iothub.azure.microsoft.com.androidsample W/System.err:     at android.os.AsyncTask$3.call(AsyncTask.java:394)
2021-01-21 11:19:30.582 18530-18572/com.iothub.azure.microsoft.com.androidsample W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2021-01-21 11:19:30.582 18530-18572/com.iothub.azure.microsoft.com.androidsample W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
2021-01-21 11:19:30.582 18530-18572/com.iothub.azure.microsoft.com.androidsample W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2021-01-21 11:19:30.582 18530-18572/com.iothub.azure.microsoft.com.androidsample W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2021-01-21 11:19:30.583 18530-18572/com.iothub.azure.microsoft.com.androidsample W/System.err:     at java.lang.Thread.run(Thread.java:923)
2021-01-21 11:19:30.583 18530-18572/com.iothub.azure.microsoft.com.androidsample W/System.err: Caused by: java.security.cert.CertificateException: java.lang.NullPointerException: Attempt to invoke virtual method 'byte[] c.b.j.i.b.b.a()' on a null object reference
2021-01-21 11:19:30.583 18530-18572/com.iothub.azure.microsoft.com.androidsample W/System.err:     at b.b.a.b.a.c.b.f.a.b(:206)
2021-01-21 11:19:30.583 18530-18572/com.iothub.azure.microsoft.com.androidsample W/System.err:     at b.b.a.b.a.c.b.f.a.<init>(:66)
2021-01-21 11:19:30.583 18530-18572/com.iothub.azure.microsoft.com.androidsample W/System.err: 	... 8 more
2021-01-21 11:19:30.583 18530-18572/com.iothub.azure.microsoft.com.androidsample W/System.err: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'byte[] c.b.j.i.b.b.a()' on a null object reference
2021-01-21 11:19:30.583 18530-18572/com.iothub.azure.microsoft.com.androidsample W/System.err:     at b.b.a.b.a.c.b.f.a.b(:201)
2021-01-21 11:19:30.583 18530-18572/com.iothub.azure.microsoft.com.androidsample W/System.err: 	... 9 more
`

**Comment by timtay-microsoft** [comment] 2021-01-21 17:33
I can't repro that same exception when I run my sample as is. Are you modifying the sample I linked above in any way? If not, what device/emulator are you running it on?

**Comment by devzeze** [comment] 2021-01-25 11:13
Hi,
it was my fault, cert issues. Tested again and sample app works properly.

I will check now why still have issues on my app.

`2021-01-25 12:10:34.933 24075-24075/com.iothub.azure.microsoft.com.androidsample I/System.out: Starting...
2021-01-25 12:10:34.934 24075-24075/com.iothub.azure.microsoft.com.androidsample I/System.out: Beginning setup.
2021-01-25 12:10:34.936 24075-24075/com.iothub.azure.microsoft.com.androidsample I/System.out: Press any key to exit...
2021-01-25 12:10:35.079 24075-24132/com.iothub.azure.microsoft.com.androidsample I/System.out: Waiting for Provisioning Service to register
2021-01-25 12:10:35.080 24075-24134/com.iothub.azure.microsoft.com.androidsample I/b.b.a.b.a.c.a.f.f.d: Opening the connection to device provisioning service...
2021-01-25 12:10:35.518 24075-24132/com.iothub.azure.microsoft.com.androidsample I/System.out: Waiting for Provisioning Service to register
2021-01-25 12:10:35.958 24075-24132/com.iothub.azure.microsoft.com.androidsample I/System.out: Waiting for Provisioning Service to register
2021-01-25 12:10:36.184 24075-24134/com.iothub.azure.microsoft.com.androidsample I/b.b.a.b.a.c.a.f.f.d: Connection to device provisioning service opened successfully, sending initial device registration message
2021-01-25 12:10:36.307 24075-24143/com.iothub.azure.microsoft.com.androidsample I/b.b.a.b.a.c.a.f.f.e: Authenticating with device provisioning service using x509 certificates
2021-01-25 12:10:36.401 24075-24132/com.iothub.azure.microsoft.com.androidsample I/System.out: Waiting for Provisioning Service to register
2021-01-25 12:10:36.707 24075-24134/com.iothub.azure.microsoft.com.androidsample I/b.b.a.b.a.c.a.f.f.d: Waiting for device provisioning service to provision this device...
2021-01-25 12:10:36.708 24075-24134/com.iothub.azure.microsoft.com.androidsample I/b.b.a.b.a.c.a.f.f.d: Current provisioning status: ASSIGNING
2021-01-25 12:10:36.842 24075-24132/com.iothub.azure.microsoft.com.androidsample I/System.out: Waiting for Provisioning Service to register
2021-01-25 12:10:39.012 24075-24132/com.iothub.azure.microsoft.com.androidsample I/chatty: uid=10268(com.iothub.azure.microsoft.com.androidsample) AsyncTask #1 identical 5 lines
2021-01-25 12:10:39.438 24075-24132/com.iothub.azure.microsoft.com.androidsample I/System.out: Waiting for Provisioning Service to register
2021-01-25 12:10:39.803 24075-24134/com.iothub.azure.microsoft.com.androidsample I/b.b.a.b.a.c.a.f.f.d: Device provisioning service assigned the device successfully
2021-01-25 12:10:39.859 24075-24132/com.iothub.azure.microsoft.com.androidsample I/System.out: Device provisioning succeeded
2021-01-25 12:10:39.859 24075-24132/com.iothub.azure.microsoft.com.androidsample I/System.out: IotHub Uri : ims-iot-hub-preview.azure-devices.net
2021-01-25 12:10:39.860 24075-24132/com.iothub.azure.microsoft.com.androidsample I/System.out: Device ID : ....
2021-01-25 12:10:40.824 24075-24132/com.iothub.azure.microsoft.com.androidsample I/b.b.a.b.a.b.z.f: The connection to the IoT Hub has been established
2021-01-25 12:10:40.825 24075-24132/com.iothub.azure.microsoft.com.androidsample I/b.b.a.b.a.b.z.f: Updating transport status to new status CONNECTED with reason CONNECTION_OK
2021-01-25 12:10:40.828 24075-24132/com.iothub.azure.microsoft.com.androidsample I/b.b.a.b.a.b.z.f: Client connection opened successfully
2021-01-25 12:10:40.828 24075-24132/com.iothub.azure.microsoft.com.androidsample I/b.b.a.b.a.b.c: Device client opened successfully
2021-01-25 12:10:40.828 24075-24132/com.iothub.azure.microsoft.com.androidsample I/b.b.a.b.a.b.c: Closing device client...
2021-01-25 12:10:40.836 24075-24132/com.iothub.azure.microsoft.com.androidsample I/b.b.a.b.a.b.z.f: Updating transport status to new status DISCONNECTED with reason CLIENT_CLOSE
2021-01-25 12:10:40.836 24075-24132/com.iothub.azure.microsoft.com.androidsample I/b.b.a.b.a.b.z.f: Client connection closed successfully
2021-01-25 12:10:40.836 24075-24132/com.iothub.azure.microsoft.com.androidsample I/b.b.a.b.a.b.c: Device client closed successfully
`

**Comment by devzeze** [comment] 2021-01-25 12:41
Ok, found the difference between my demo and your samples.

`classpath "com.android.tools.build:gradle:4.1.2"`

instead of 

`classpath "com.android.tools.build:gradle:3.6.3"`

Temporarily I think we we can revert to that version but would be good t have it working with latest ones.
Can you take a look?

**Comment by timtay-microsoft** [comment] 2021-01-27 00:49
This is beginning to seem more like a bug with Proguard than with this SDK in particular. My team is interested in enabling support with Proguard, but I'm labeling this as a feature request, not a bug report.

**Comment by timtay-microsoft** [comment] 2021-02-11 22:22
I went ahead and pushed another branch with Gradle 4.1.2 and some small modifications to our proguard rules file and the sample seems to work for me. Can you give it a try and see if it works for you as well?

https://github.com/Azure/azure-iot-sdk-java/commit/47b63a5c60d50d86affadb038db1f88abf58d150

**Comment by timtay-microsoft** [comment] 2021-02-19 17:00
@devzeze does the proguard rules file in the above commit work for you as well?

**Comment by devzeze** [comment] 2021-02-22 12:02
@timtay-microsoft I can confirm provisioning works in my setup with those rules.

Thank you!

**Comment by timtay-microsoft** [comment] 2021-02-22 19:45
I'm glad to hear it! I'll go ahead and close this issue then

**Closed by timtay-microsoft** 2021-02-22 19:45 UTC
Labels: IoTSDK, enhancement

**Comment by nishanthvasu** [comment] 2021-06-09 07:52
@timtay-microsoft @devzeze  Hi , I am receiving this issue again. I tried with the your proguard rules as well. Can u help me out in this?                     
**Error: PROVISIONING FAILED : b.e.b.b.a.c.a.f.d.b: Service error: null - null - TrackingId: null**

**ProGuard Rules:** 

# Add project specific ProGuard rules here.
# By default, the flags in this file are appended to flags specified
# in C:\Users\v-askhur.REDMOND\AppData\Local\Android\Sdk/tools/proguard/proguard-android.txt
# You can edit the include path and order by changing the proguardFiles
# directive in build.gradle.
#
# For more details, see
#   http://developer.android.com/guide/developing/tools/proguard.html

# Add any project specific keep options here:

# If your project uses WebView with JS, uncomment the following
# and specify the fully qualified class name to the JavaScript interface
# class:
#-keepclassmembers class fqcn.of.javascript.interface.for.webview {
#   public *;
#}

# JSON parser classes don't mix well with minification because JSON parser classes use reflection
# based on the name of the field to create the JSON, and minification changes those names. As a result
# all the message payload serializing and deserializing breaks. These lines explicitly exclude
# the packages where we keep our JSON parsing classes from minification to avoid this issue
-keep class com.microsoft.azure.sdk.iot.provisioning.device.internal.parser.* { *; }
-keep class com.microsoft.azure.sdk.iot.deps.serializer.* { *; }
-keep class com.microsoft.azure.sdk.iot.provisioning.service.configs.* { *; }
-keep class com.microsoft.azure.sdk.iot.deps.twin.* { *; }
-keep class com.microsoft.azure.sdk.iot.service.ImportMode { *; }
-keep class com.microsoft.azure.sdk.iot.service.AuthenticationMechanism { *; }
-keep class com.microsoft.azure.sdk.iot.device.edge.MethodRequest { *; }
-keep class com.microsoft.azure.sdk.iot.device.hsm.parser.ErrorResponse { *; }
-keep class com.microsoft.azure.sdk.iot.device.hsm.parser.SignRequest { *; }

# These are the recommended exclusions when using the IoT Hub service client SDK. They are commented
# out because this sample only uses the IoT Hub device client SDK
#-keep class com.microsoft.azure.sdk.iot.service.ImportMode { *; }
#-keep class com.microsoft.azure.sdk.iot.service.AuthenticationMechanism { *; }

# These are the recommended exclusions when using the Device Provisioning Service device client SDK.
# They are commented out because this sample only uses the IoT Hub device client SDK
#-keep class com.microsoft.azure.sdk.iot.provisioning.device.internal.parser.* { *; }

# These are the recommended exclusions when using the Device Provisioning Service service client SDK.
# They are commented out because this sample only uses the IoT Hub device client SDK
#-keep class com.microsoft.azure.sdk.iot.provisioning.service.configs.* { *; }

**Gradle:**

 buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

**Dependencies:** 

//Azure provisioning device client
    // https://mvnrepository.com/artifact/com.microsoft.azure.sdk.iot.provisioning/provisioning-device-client
    implementation group: 'com.microsoft.azure.sdk.iot.provisioning', name: 'provisioning-device-client', version: '1.7.1'

    // https://mvnrepository.com/artifact/com.microsoft.azure.sdk.iot.provisioning.security/x509-provider
    implementation group: 'com.microsoft.azure.sdk.iot.provisioning.security', name: 'x509-provider', version: '1.1.3'

    // Azure IOT device client
    // https://mvnrepository.com/artifact/com.microsoft.azure.sdk.iot/iot-device-client
    implementation (group: 'com.microsoft.azure.sdk.iot', name: 'iot-device-client', version: '1.19.0') {
        exclude module: 'azure-storage'
    }
    implementation ('com.microsoft.azure.android:azure-storage-android:2.0.0@aar')

    // https://mvnrepository.com/artifact/com.microsoft.azure.sdk.iot/iot-deps
    implementation group: 'com.microsoft.azure.sdk.iot', name: 'iot-deps', version: '0.8.5'

    //Currently this is added as a module dependency due to a bug in the lib. This bug is fixed in the module dependency code
    //In future if the bug gets fixed in the lib, we can remove the module and add the gradle dependency
    //Azure IOT service client
    // https://mvnrepository.com/artifact/com.microsoft.azure.sdk.iot/iot-service-client
    //implementation group: 'com.microsoft.azure.sdk.iot', name: 'iot-service-client', version: '1.17.1'

    implementation 'org.apache.commons:commons-lang3:3.6'
    implementation group: 'com.google.guava', name: 'guava', version: '24.1-jre'
    implementation 'com.google.code.gson:gson:2.8.5'

def appCenterSdkVersion = '3.0.0'
    implementation "com.microsoft.appcenter:appcenter-analytics:${appCenterSdkVersion}"
    implementation "com.microsoft.appcenter:appcenter-crashes:${appCenterSdkVersion}"
