### ISSUE TITLE
[Device Client] AMQPS_WS cannot handle large messages

### ISSUE THREAD

**Issue by pizerg** [Azure/azure-iot-sdk-java#742] opened 2020-03-25 11:49 UTC
- **OS and version used:** Windows 10 + Ubuntu (18.04) + Raspbian (latest version)

- **Java runtime used:** Oracle's JDK 11 + OpenJDK 11

- **SDK version used:** 1.20.1

# Description of the issue:
When using AMQPS_WS as protocol and trying to send a "big" message (around 12KB after json encoding) the IoT Hub backend closes the connection which translates to a MESSAGE_EXPIRED in the client. 

MQTT_WS protocol handles this scenario without problems.

For the connection on both cases, a connection string is used.

# Code sample exhibiting the issue:
Just start a hub, set any desired callbacks, generate a large enough message and send it.

# Console log of the issue:
```2020-03-25 12:14:33.846 DEBUG AmqpsIotHubConnection:1223 - No gateway hostname was present in config, connecting directly to hub
2020-03-25 12:14:33.919 DEBUG AmqpsIotHubConnection:182 - Opening AMQP connection
2020-03-25 12:14:33.937 DEBUG AmqpsIotHubConnection:1223 - No gateway hostname was present in config, connecting directly to hub
2020-03-25 12:14:34.680 DEBUG AmqpsDeviceOperations:154 - Opening cbs sender link with link correlation id [REMOVED]
2020-03-25 12:14:34.680 DEBUG AmqpsDeviceOperations:176 - Opening cbs receiver link with link correlation id [REMOVED]
2020-03-25 12:14:34.721 DEBUG AmqpsDeviceOperations:396 - cbs sender link with link correlation id [REMOVED] was successfully opened {}
2020-03-25 12:14:34.721 DEBUG AmqpsDeviceOperations:404 - cbs receiver link with link correlation id [REMOVED] was successfully opened
2020-03-25 12:14:34.748 DEBUG AmqpsDeviceAuthenticationCBS:110 - Received amqp message on cbs receiver link with link correlation id [REMOVED] and message correlation id [REMOVED]
2020-03-25 12:14:34.748 DEBUG AmqpsDeviceAuthenticationCBS:153 - CBS authentication message was acknowledged with status 200, authentication for one cbs link pair was successful
2020-03-25 12:14:34.748 DEBUG AmqpsIotHubConnection:998 - Handling a received message with amqp message correlation id [REMOVED]
2020-03-25 12:14:34.748 DEBUG AmqpsIotHubConnection:1041 - Received message with correlation id [REMOVED] was a cbs message, handling...
2020-03-25 12:14:34.748 DEBUG AmqpsIotHubConnection:1087 - All CBS links have received a 200, opening worker links
2020-03-25 12:14:34.748 DEBUG AmqpsDeviceOperations:154 - Opening telemetry sender link with link correlation id [REMOVED]
2020-03-25 12:14:34.748 DEBUG AmqpsDeviceOperations:176 - Opening telemetry receiver link with link correlation id [REMOVED]
2020-03-25 12:14:34.787 DEBUG AmqpsDeviceOperations:396 - telemetry sender link with link correlation id [REMOVED] was successfully opened {}
2020-03-25 12:14:34.790 DEBUG AmqpsDeviceOperations:404 - telemetry receiver link with link correlation id [REMOVED] was successfully opened
2020-03-25 12:14:34.791 INFO  IotHubTransport:218 - The connection to the IoT Hub has been established
2020-03-25 12:14:34.791 INFO  IotHubTransport:1043 - Updating transport status to new status CONNECTED with reason CONNECTION_OK
2020-03-25 12:14:34.792 DEBUG IotHubTransport:1053 - Invoking connection status callbacks with new status details
IoTHub connection state callback, status: CONNECTED reason: CONNECTION_OK
2020-03-25 12:14:34.800 DEBUG AmqpsIotHubConnection:253 - AMQP connection opened successfully
2020-03-25 12:14:34.800 INFO  IotHubTransport:275 - Client connection opened successfully
2020-03-25 12:14:34.816 INFO  DeviceClient:337 - Device client opened successfully
2020-03-25 12:14:34.816 INFO  IotHubTransport:348 - Message was queued to be sent later ( Message details: Correlation Id [REMOVED] Message Id [REMOVED] )
2020-03-25 12:14:34.831 INFO  IotHubTransport:950 - Sending message ( Message details: Correlation Id [REMOVED] Message Id [REMOVED] )
2020-03-25 12:14:34.895 DEBUG AmqpsDeviceOperations:154 - Opening methods sender link with link correlation id [REMOVED]
2020-03-25 12:14:34.895 DEBUG AmqpsDeviceOperations:176 - Opening methods receiver link with link correlation id [REMOVED]
2020-03-25 12:14:34.895 DEBUG IotHubTransport:103 - IotHub message was acknowledged. Checking if there is record of sending this message ( Message details: Correlation Id [REMOVED] Message Id [REMOVED] )
2020-03-25 12:14:34.911 INFO  IotHubTransport:443 - Invoking the callback function for sent message, IoT Hub responded to message ( Message details: Correlation Id [REMOVED] Message Id [REMOVED] ) with status OK_EMPTY
2020-03-25 12:14:34.927 DEBUG AmqpsDeviceOperations:396 - methods sender link with link correlation id [REMOVED]was successfully opened {}
2020-03-25 12:14:34.927 DEBUG AmqpsDeviceOperations:404 - methods receiver link with link correlation id [REMOVED] was successfully opened
2020-03-25 12:14:37.571 ERROR ErrorLoggingBaseHandler:33 - Amqp link receiver_link_devicemethods-[REMOVED] was closed remotely with exception com.microsoft:connection-closed-on-new-connection with description Backend initiated disconnection.
2020-03-25 12:14:37.571 DEBUG AmqpsDeviceOperations:663 - methods receiver link with link correlation id [REMOVED] was closed
2020-03-25 12:14:37.586 WARN  AmqpsIotHubConnection:1206 - Amqp connection was closed, creating a thread to notify transport layer
com.microsoft.azure.sdk.iot.device.exceptions.ProtocolException: Backend initiated disconnection.
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsExceptionTranslator.convertToAmqpException(AmqpsExceptionTranslator.java:98)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection.getTransportExceptionFromProtonEndpoints(AmqpsIotHubConnection.java:1250)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection.getTransportExceptionFromEvent(AmqpsIotHubConnection.java:1271)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection.onLinkRemoteClose(AmqpsIotHubConnection.java:906)
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:176)
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.IotHubReactor.run(IotHubReactor.java:28)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection$ReactorRunner.call(AmqpsIotHubConnection.java:1352)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2020-03-25 12:14:37.602 ERROR ErrorLoggingBaseHandler:33 - Amqp link sender_link_devicemethods-[REMOVED] was closed remotely with exception com.microsoft:connection-closed-on-new-connection with description Backend initiated disconnection.
2020-03-25 12:14:37.602 DEBUG AmqpsDeviceOperations:655 - methods sender link with link correlation id [REMOVED] was closed
2020-03-25 12:14:37.602 WARN  AmqpsIotHubConnection:1206 - Amqp connection was closed, creating a thread to notify transport layer
com.microsoft.azure.sdk.iot.device.exceptions.ProtocolException: Backend initiated disconnection.
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsExceptionTranslator.convertToAmqpException(AmqpsExceptionTranslator.java:98)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection.getTransportExceptionFromProtonEndpoints(AmqpsIotHubConnection.java:1250)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection.getTransportExceptionFromEvent(AmqpsIotHubConnection.java:1271)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection.onLinkRemoteClose(AmqpsIotHubConnection.java:906)
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:176)
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.IotHubReactor.run(IotHubReactor.java:28)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection$ReactorRunner.call(AmqpsIotHubConnection.java:1352)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2020-03-25 12:14:37.602 INFO  IotHubTransport:720 - Handling a disconnection event
com.microsoft.azure.sdk.iot.device.exceptions.ProtocolException: Backend initiated disconnection.
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsExceptionTranslator.convertToAmqpException(AmqpsExceptionTranslator.java:98)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection.getTransportExceptionFromProtonEndpoints(AmqpsIotHubConnection.java:1250)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection.getTransportExceptionFromEvent(AmqpsIotHubConnection.java:1271)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection.onLinkRemoteClose(AmqpsIotHubConnection.java:906)
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:176)
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.IotHubReactor.run(IotHubReactor.java:28)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection$ReactorRunner.call(AmqpsIotHubConnection.java:1352)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2020-03-25 12:14:37.602 ERROR ErrorLoggingBaseHandler:33 - Amqp link receiver_link_telemetry-[REMOVED] was closed remotely with exception amqp:internal-error with description Another AMQP Client has opened a Receive Link
2020-03-25 12:14:37.602 DEBUG AmqpsDeviceOperations:663 - telemetry receiver link with link correlation id [REMOVED] was closed
2020-03-25 12:14:37.602 DEBUG IotHubTransport:663 - Mapping exception throwable to COMMUNICATION_ERROR because the sdk was unable to classify the thrown exception to anything other category
com.microsoft.azure.sdk.iot.device.exceptions.ProtocolException: Backend initiated disconnection.
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsExceptionTranslator.convertToAmqpException(AmqpsExceptionTranslator.java:98)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection.getTransportExceptionFromProtonEndpoints(AmqpsIotHubConnection.java:1250)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection.getTransportExceptionFromEvent(AmqpsIotHubConnection.java:1271)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection.onLinkRemoteClose(AmqpsIotHubConnection.java:906)
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:176)
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.IotHubReactor.run(IotHubReactor.java:28)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection$ReactorRunner.call(AmqpsIotHubConnection.java:1352)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2020-03-25 12:14:37.602 WARN  AmqpsIotHubConnection:1206 - Amqp connection was closed, creating a thread to notify transport layer
com.microsoft.azure.sdk.iot.device.transport.amqps.exceptions.AmqpInternalErrorException: Another AMQP Client has opened a Receive Link
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsExceptionTranslator.convertToAmqpException(AmqpsExceptionTranslator.java:45)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection.getTransportExceptionFromProtonEndpoints(AmqpsIotHubConnection.java:1250)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection.getTransportExceptionFromEvent(AmqpsIotHubConnection.java:1271)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection.onLinkRemoteClose(AmqpsIotHubConnection.java:906)
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:176)
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.IotHubReactor.run(IotHubReactor.java:28)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection$ReactorRunner.call(AmqpsIotHubConnection.java:1352)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2020-03-25 12:14:37.602 WARN  IotHubTransport:1047 - Updating transport status to new status DISCONNECTED_RETRYING with reason COMMUNICATION_ERROR
com.microsoft.azure.sdk.iot.device.exceptions.ProtocolException: Backend initiated disconnection.
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsExceptionTranslator.convertToAmqpException(AmqpsExceptionTranslator.java:98)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection.getTransportExceptionFromProtonEndpoints(AmqpsIotHubConnection.java:1250)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection.getTransportExceptionFromEvent(AmqpsIotHubConnection.java:1271)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection.onLinkRemoteClose(AmqpsIotHubConnection.java:906)
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:176)
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.IotHubReactor.run(IotHubReactor.java:28)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection$ReactorRunner.call(AmqpsIotHubConnection.java:1352)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2020-03-25 12:14:37.602 DEBUG IotHubTransport:1053 - Invoking connection status callbacks with new status details
IoTHub connection state callback, status: DISCONNECTED_RETRYING reason: COMMUNICATION_ERROR
IoTHub connection state callback error: com.microsoft.azure.sdk.iot.device.exceptions.ProtocolException: Backend initiated disconnection.
2020-03-25 12:14:37.602 DEBUG IotHubTransport:736 - Starting reconnection logic
2020-03-25 12:14:37.602 ERROR IotHubTransport:810 - Reconnection was abandoned due to encountering a non-retryable exception
com.microsoft.azure.sdk.iot.device.exceptions.ProtocolException: Backend initiated disconnection.
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsExceptionTranslator.convertToAmqpException(AmqpsExceptionTranslator.java:98)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection.getTransportExceptionFromProtonEndpoints(AmqpsIotHubConnection.java:1250)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection.getTransportExceptionFromEvent(AmqpsIotHubConnection.java:1271)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection.onLinkRemoteClose(AmqpsIotHubConnection.java:906)
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:176)
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.IotHubReactor.run(IotHubReactor.java:28)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection$ReactorRunner.call(AmqpsIotHubConnection.java:1352)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2020-03-25 12:14:37.602 DEBUG IotHubTransport:663 - Mapping exception throwable to COMMUNICATION_ERROR because the sdk was unable to classify the thrown exception to anything other category
com.microsoft.azure.sdk.iot.device.exceptions.ProtocolException: Backend initiated disconnection.
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsExceptionTranslator.convertToAmqpException(AmqpsExceptionTranslator.java:98)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection.getTransportExceptionFromProtonEndpoints(AmqpsIotHubConnection.java:1250)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection.getTransportExceptionFromEvent(AmqpsIotHubConnection.java:1271)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection.onLinkRemoteClose(AmqpsIotHubConnection.java:906)
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:176)
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.IotHubReactor.run(IotHubReactor.java:28)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection$ReactorRunner.call(AmqpsIotHubConnection.java:1352)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2020-03-25 12:14:37.602 DEBUG AmqpsIotHubConnection:344 - Closing amqp connection...
2020-03-25 12:14:37.602 DEBUG AmqpsSessionManager:87 - Closing AMQP session
2020-03-25 12:14:37.602 DEBUG AmqpsDeviceOperations:190 - Closed telemetry sender link with link correlation id [REMOVED]
2020-03-25 12:14:37.602 DEBUG AmqpsDeviceOperations:202 - Closed telemetry receiver link with link correlation id [REMOVED]
2020-03-25 12:14:37.602 DEBUG AmqpsDeviceOperations:190 - Closed methods sender link with link correlation id [REMOVED]
2020-03-25 12:14:37.602 DEBUG AmqpsDeviceOperations:202 - Closed methods receiver link with link correlation id [REMOVED]
2020-03-25 12:14:37.602 DEBUG AmqpsDeviceOperations:190 - Closed cbs sender link with link correlation id [REMOVED]
2020-03-25 12:14:37.602 DEBUG AmqpsDeviceOperations:202 - Closed cbs receiver link with link correlation id [REMOVED]
2020-03-25 12:14:37.618 WARN  IotHubTransport:1047 - Updating transport status to new status DISCONNECTED with reason COMMUNICATION_ERROR
com.microsoft.azure.sdk.iot.device.exceptions.ProtocolException: Backend initiated disconnection.
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsExceptionTranslator.convertToAmqpException(AmqpsExceptionTranslator.java:98)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection.getTransportExceptionFromProtonEndpoints(AmqpsIotHubConnection.java:1250)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection.getTransportExceptionFromEvent(AmqpsIotHubConnection.java:1271)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection.onLinkRemoteClose(AmqpsIotHubConnection.java:906)
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:176)
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.IotHubReactor.run(IotHubReactor.java:28)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection$ReactorRunner.call(AmqpsIotHubConnection.java:1352)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2020-03-25 12:14:37.618 DEBUG IotHubTransport:1053 - Invoking connection status callbacks with new status details
IoTHub connection state callback, status: DISCONNECTED reason: COMMUNICATION_ERROR
IoTHub connection state callback error: com.microsoft.azure.sdk.iot.device.exceptions.ProtocolException: Backend initiated disconnection.
Non recoverable error with IoTHub client, restarting components```

**Comment by timtay-microsoft** [comment] 2020-03-26 23:43
I've identified part of the issue here. Within our AMQP websocket implementation, there is a hardcoded max buffer size of around 4000 bytes (seen [here](https://github.com/Azure/qpid-proton-j-extensions/blob/5197bd7137dfb207b0ec67aac24a906b9831448c/src/main/java/com/microsoft/azure/proton/transport/ws/impl/WebSocketImpl.java#L33)). From my initial testing, this value can be changed to equal the hub side limit of 256 kb instead.

However, even with that change, the server kills the connection if the SDK sends a message larger than ~16 kb . I'll need to investigate further as to why that is happening.

It looks like only AMQP_WS has this issue. AMQP works fine with larger messages, and so does MQTT/MQTT_WS/HTTPS

**Comment by timtay-microsoft** [comment] 2020-05-13 17:29
Just to update this thread, we have a partial fix checked in that raises the max message size over AMQPS_WS to 16 kb, but this still isn't up to the IoT Hub max message size of 256 kb. We are still investigating how to get that last jump, but we do plan on releasing a version of this SDK that has this slightly improved message size. We'll leave this issue open until we get up to 256 kb.

**Comment by timtay-microsoft** [comment] 2020-05-18 23:14
We have done a release of the device client (1.22.0) that raises the message size limit up to ~16 kb, but we are still working to make that limit 256 kb

**Comment by nbeekwilder** [comment] 2021-01-04 20:57
We are also seeing this issue; however, older versions did not have this behavior. Compiling our client against version 0.26.0 of proton-J allows us to send messages up to the IotHub message limit whereas using version 0.27.0 or later displays the problem. I haven't had a change to figure out what changed between those two versions of proton-j but it should help you identify the root cause of the problem.

**Comment by timtay-microsoft** [comment] 2021-01-28 01:24
Interesting, thanks for sharing that insight!

**Comment by timtay-microsoft** [comment] 2021-02-23 19:39
I'm following up on this new information, and from what I can tell so far, it was [this](https://github.com/apache/qpid-proton-j/commit/5a2631dcfa750287c4506097a625ab020018330c) commit in the proton-j project that broke this feature for us. Since we can send messages up to the expected message size over AMQP just fine, it is likely just an issue between our websocket extension and proton-j. I'll keep digging

**Comment by timtay-microsoft** [comment] 2021-02-23 22:50
Thankfully proton-j allows us to configure the value that had it's default value changed by [this commit](https://github.com/apache/qpid-proton-j/commit/5a2631dcfa750287c4506097a625ab020018330c) that caused this bug. #1129 will basically revert that change which re-enables sending messages of up to 256 kB over AMQPS_WS

**Comment by timtay-microsoft** [comment] 2021-02-25 00:20
Device client version 1.29.2 has fixed this issue, so I'm closing this issue. AMQPS_WS can now send messages up to the 256 kB message size limit that IoT Hub itself imposes.

**Closed by timtay-microsoft** 2021-02-25 00:20 UTC
Labels: IoTSDK, bug, fix checked in
