### ISSUE TITLE
DeviceMethod timeouts ignored

### ISSUE THREAD

**Issue by mwm-twx** [Azure/azure-iot-sdk-java#84] opened 2017-04-19 13:55 UTC
OS:  Linux x64 (Fedora 25)
Java:  1.8.0_121
SDK:  1.2.18

# Description of the issue:
Both timeouts provided to `DeviceMethod.invoke` are ignored.  `DeviceOperations` always uses a default read timeout of 24 seconds and the time remote device does not receive the `timeoutInSeconds` key defined by the documentation.

# Code sample exhibiting the issue:
Any DeviceMethod call.

Resulting HTTP request:
```
POST /twins/ServicesThing/methods?api-version=2016-11-14 HTTP/1.1
User-Agent: com.microsoft.azure.sdk.iot.iot-service-client/1.2.18
authorization: SharedAccessSignature sr=<HUB>.azure-devices.net&sig=<SIG>&skn=service
Request-Id: 0
Accept: application/json
Content-Type: application/json; charset=utf-8
Host: <HUB>.azure-devices.net
Connection: keep-alive
Content-Length: 101

{"methodName":"echo","responseTimeoutInSeconds":30,"connectTimeoutInSeconds":30,"payload":"fdsafdsa"}
```

**Comment by prmathur-microsoft** [comment] 2017-04-24 20:56
We specify timeouts as a part of json i.e payload and not in http headers. So I can see from code that timeout is specified in payload.
{"methodName":"echo","responseTimeoutInSeconds":30,"connectTimeoutInSeconds":30,"payload":"fdsafdsa"}
Also these timeouts are not propagated to the device, but used to trigger back on the service client within this time interval.
Can you please specify more details if you are unable to see this timeout being reflected on the service client? As on my end I'm not able to reproduce.

**Comment by mwm-twx** [comment] 2017-04-25 14:57
Are the `response` and `connect` timeouts undocumented API; the documentation only mentions `timeoutInSeconds`?

A timeout of more than 24 seconds does not work.  There is a hardcoded 24 second read timeout on the HTTP request calling the device method.  Instead of a "gateway timeout" after 30 seconds, there is a `SocketTimeoutException` with `Read timed out` after 24 seconds.

**Comment by prmathur-microsoft** [comment] 2017-04-26 19:05
Okay, we will work on providing a fix for this.

**Comment by anhashia** [comment] 2017-05-12 00:21
Fix is in progress !

**Comment by anhashia** [comment] 2017-05-31 00:50
Fixed in https://github.com/Azure/azure-iot-sdk-java/commit/4ff784226d24dbd01be41e0a315c640c8ba417b1

**Comment by prmathur-microsoft** [comment] 2017-06-06 19:08
Maven package containing the fix is released now. Please give it a try and feel free to reopen if you see further issues.

**Closed by prmathur-microsoft** 2017-06-06 19:08 UTC
Labels: bug, CSS, fix checked in
