### ISSUE TITLE
Android DeviceClient.open() called two times creates a lot of threads

### ISSUE THREAD

**Issue by FranAlterados** [Azure/azure-iot-sdk-java#248] opened 2018-05-23 16:59 UTC
- **OS and version used:** Android 7.0

- **Java runtime used:** 1.8

- **SDK version used:** 
iot-device-client:1.11.0
iot-service-client:1.13.2
iot-deps:0.5.2
azure-storage-android:2.0.0
org.apache.commons:commons-lang3:3.6

# Description of the issue:
In Android if I do DeviceClient.open() in a DeviceClient already opened  the number of threads starts to grow (around 1k threads in a minute) until the app crashes.

I need a method to know if a DeviceClient is already opened or an exception if I try to open a DeviceClient two times.

Thank you

# Code sample exhibiting the issue:
```java
public class MainActivity extends AppCompatActivity {

    Button btOpenConnection;
    Button btCloseConnection;

    DeviceClient client;

    private final String connString = "[device connection string]";
    private final String deviceId = "MyAndroidDevice";

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        btOpenConnection = findViewById(R.id.bt_open_connection);
        btOpenConnection.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                IotHubClientProtocol protocol = IotHubClientProtocol.MQTT;
                try {
                    client = new DeviceClient(connString, protocol);
                    try {
                        client.open();
                    } catch (Exception e2) {
                        System.err.println("Exception while opening IoTHub connection: " + e2.toString());
                    }
                } catch (URISyntaxException e) {
                    e.printStackTrace();
                    System.err.println("Exception while creating device client: " + e.toString());
                }
            }
        });

        btCloseConnection = findViewById(R.id.bt_close_connection);
        btCloseConnection.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                try {
                    client.closeNow();
                } catch (IOException e) {
                    e.printStackTrace();
                    System.err.println("Exception while close device client: " + e.toString());
                }
            }
        });
    }
}
```

**Comment by timtay-microsoft** [comment] 2018-05-23 17:36
As of now, this SDK does not guarantee Android support. Some aspects of this SDK may work on Android, but we are not currently verifying/developing with Android support in mind. It's likely that we will start supporting it within a few months. For now though, we won't be actively looking into Android bugs. I'll keep this thread posted as we get closer to Android support.

**Comment by FranAlterados** [comment] 2018-06-11 07:45
I found a solution for this changing my communication architecture. But although it is no longer a problem for me, the problem still continues.

Problem starts when you create a DeviceClient, do client.open() and after a while you repeat it over the same variable. This creates a lot of threads that are never destroyed.

Code Example:
```java
public class MainActivity extends AppCompatActivity {

    private final String connString = "[device connection string]";
    private final String deviceId = "MyAndroidDevice";

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        try {
            DeviceClient client;
            IotHubClientProtocol protocol = IotHubClientProtocol.MQTT;
            client = new DeviceClient(connString, protocol);
            client.open();
            Thread.sleep(2000);
            client = new DeviceClient(connString, protocol);
            client.open();
        } catch (Exception e) {
            System.err.println("Exception while opening IoTHub connection: " + e.toString());
        }
    }
}
```

**Comment by timtay-microsoft** [comment] 2018-06-12 19:03
This is expected behavior. When you open an MQTT connection, it will spawn some threads (MQTT Call, for instance). These threads will live until you close the connection. You are opening two separate MQTT connections with the above sample, so the MQTT library will spawn the necessary threads for each connection. 

If you reuse the same client instead of creating a new client constantly, the threads will not multiply. There aren't any benefits to creating multiple DeviceClient instances like you are currently doing.

```java
public class MainActivity extends AppCompatActivity {

    private final String connString = "[device connection string]";
    private final String deviceId = "MyAndroidDevice";

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        try {
            DeviceClient client;
            IotHubClientProtocol protocol = IotHubClientProtocol.MQTT;
            client = new DeviceClient(connString, protocol);
            client.open();
            Thread.sleep(2000);
            //client = new DeviceClient(connString, protocol); remove this line
            client.open();
        } catch (Exception e) {
            System.err.println("Exception while opening IoTHub connection: " + e.toString());
        }
    }
}
```

If you call open on a Device Client instance, the connection will be open when the call returns, or an exception will be thrown to notify you that the connection failed. You can also register your device client to notify you of connection status updates so that you know when connection is lost in the future.

**Comment by timtay-microsoft** [comment] 2018-06-12 19:05
Since this is a problem with how you were creating unnecessary DeviceClient instances, there is no bug to fix on the SDK side. Because of that, I'm going to close this issue. Feel free to re-open this issue if you still see multiplying threads with the above code sample.

**Closed by timtay-microsoft** 2018-06-12 19:05 UTC
Labels: Android
