### ISSUE TITLE
Network Reconnection Issue in Device Client 1.6.0 for AMQPS_WS

### ISSUE THREAD

**Issue by sruthi06** [Azure/azure-iot-sdk-java#198] opened 2018-01-25 12:46 UTC
Hi,
We are using Android environment for developing a Cloud connector for our business application in the mobile device. 
OS and version used: Android 7.1
Java runtime used: JDK "1.8.0_45"
SDK version used: IoT Device Client 1.6.0 for Java

# Description of the issue:
We have tried using the latest device client (1.6.0) for connecting to IoTHub and sending the telemetry data to cloud. We are using the amqps_ws as the protocol. In case of any network disconnection and reconnection, we are not getting the status for the messages sent after the network connection is established.  The issue is happening only in AMQPS_WS. For HTTPS, we are able to get the status and connect again.

# Console log of the issue:
AMQPS_WS
I/System.out: {"deviceId":"SruthiDevice","messageId":0,"temperature":27.265127882630047,"humidity":41.55051693352014}
I/System.out: {"deviceId":"SruthiDevice","messageId":1,"temperature":28.09823132482363,"humidity":43.03031529049137}
I/System.out: IoT Hub responded to message 0 with status OK_EMPTY
I/System.out: IoT Hub responded to message 1 with status OK_EMPTY
I/System.out: {"deviceId":"SruthiDevice","messageId":2,"temperature":24.28038629171875,"humidity":35.42120489711317}
I/System.out: IoT Hub responded to message 2 with status OK_EMPTY
I/System.out: {"deviceId":"SruthiDevice","messageId":3,"temperature":20.378097272054813,"humidity":40.18882228944083}
I/System.out: IoT Hub responded to message 3 with status OK_EMPTY
I/System.out: Lost connection to the server. Reconnection attempt 1...
I/System.out: {"deviceId":"SruthiDevice","messageId":4,"temperature":22.6837198495695,"humidity":39.140708178577164}
I/System.out: {"deviceId":"SruthiDevice","messageId":5,"temperature":28.844251509319506,"humidity":43.800107704575495}
I/art: Do partial code cache collection, code=23KB, data=30KB
I/art: After code cache collection, code=22KB, data=29KB
I/art: Increasing code cache capacity to 128KB
I/System.out: Lost connection to the server. Reconnection attempt 2...
I/System.out: {"deviceId":"SruthiDevice","messageId":6,"temperature":26.528258414112187,"humidity":41.22386004811512}
I/System.out: {"deviceId":"SruthiDevice","messageId":7,"temperature":28.751660248844658,"humidity":37.07716120722981}
I/System.out: Lost connection to the server. Reconnection attempt 3...
I/System.out: {"deviceId":"SruthiDevice","messageId":8,"temperature":22.656229242833433,"humidity":39.464921098803615}
I/System.out: {"deviceId":"SruthiDevice","messageId":9,"temperature":20.642468019494565,"humidity":43.64581997752576}
I/System.out: {"deviceId":"SruthiDevice","messageId":10,"temperature":28.891527989837776,"humidity":48.41881737455572}
I/System.out: {"deviceId":"SruthiDevice","messageId":11,"temperature":28.698486106662727,"humidity":39.34208303703676}
I/System.out: Lost connection to the server. Reconnection attempt 4...
I/System.out: {"deviceId":"SruthiDevice","messageId":12,"temperature":25.712768986297966,"humidity":48.23723443557215}
I/System.out: {"deviceId":"SruthiDevice","messageId":13,"temperature":22.929790247021785,"humidity":39.319483471458376}
I/System.out: {"deviceId":"SruthiDevice","messageId":14,"temperature":28.43960342966726,"humidity":39.931153688815996}
I/System.out: {"deviceId":"SruthiDevice","messageId":15,"temperature":26.755178987778905,"humidity":35.217900948164946}
I/System.out: {"deviceId":"SruthiDevice","messageId":16,"temperature":28.512970987506957,"humidity":46.76258579622369}
I/System.out: {"deviceId":"SruthiDevice","messageId":17,"temperature":20.425427131134867,"humidity":34.88973411998207}
I/System.out: {"deviceId":"SruthiDevice","messageId":18,"temperature":26.03150932258102,"humidity":31.249846473301446}
I/System.out: {"deviceId":"SruthiDevice","messageId":19,"temperature":20.28651622726968,"humidity":41.75314537039405}
I/System.out: {"deviceId":"SruthiDevice","messageId":20,"temperature":22.567740094769736,"humidity":37.3675438840267}
I/System.out: Lost connection to the server. Reconnection attempt 5...
I/System.out: {"deviceId":"SruthiDevice","messageId":21,"temperature":27.175903497455458,"humidity":30.609816531420165}
I/System.out: {"deviceId":"SruthiDevice","messageId":22,"temperature":26.111890606079115,"humidity":41.71107139100205}
I/System.out: {"deviceId":"SruthiDevice","messageId":23,"temperature":20.835386646747732,"humidity":35.672595438402624}

For AMQPS_WS , I have disconnected and reconnected, but we are not sure, if the messages are sent after the reconnection since we have not received any response.
AMQPS_WS is the most used transport protocol for the production environment..

HTTPS:

I/System.out: {"deviceId":"SruthiDevice","messageId":0,"temperature":24.93539497476906,"humidity":37.748547055114436}
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
I/System.out: IoT Hub responded to message 0 with status OK_EMPTY
I/System.out: {"deviceId":"SruthiDevice","messageId":1,"temperature":22.358710761999763,"humidity":32.13751606161822}
I/System.out: IoT Hub responded to message 1 with status OK_EMPTY
I/System.out: {"deviceId":"SruthiDevice","messageId":2,"temperature":29.392580974338454,"humidity":43.9910355348116}
I/System.out: IoT Hub responded to message 2 with status OK_EMPTY
I/System.out: {"deviceId":"SruthiDevice","messageId":3,"temperature":28.207687733736805,"humidity":36.53007840764335}
I/System.out: {"deviceId":"SruthiDevice","messageId":4,"temperature":21.0791596953777,"humidity":49.2447614708915}
I/System.out: {"deviceId":"SruthiDevice","messageId":5,"temperature":23.105064366696347,"humidity":31.166310340368604}
I/System.out: {"deviceId":"SruthiDevice","messageId":6,"temperature":21.922837844046864,"humidity":42.52836616436349}
I/System.out: {"deviceId":"SruthiDevice","messageId":7,"temperature":28.413192203592708,"humidity":39.04857989437019}
I/System.out: {"deviceId":"SruthiDevice","messageId":8,"temperature":26.12267938300398,"humidity":36.03361581025468}
I/System.out: {"deviceId":"SruthiDevice","messageId":9,"temperature":27.570247197541086,"humidity":43.53390764848262}
I/System.out: {"deviceId":"SruthiDevice","messageId":10,"temperature":21.528604429066785,"humidity":46.60262753356571}
I/System.out: {"deviceId":"SruthiDevice","messageId":11,"temperature":23.8681051734403,"humidity":33.162836554045874}
I/System.out: {"deviceId":"SruthiDevice","messageId":12,"temperature":23.480500305029505,"humidity":46.93648172692531}
I/System.out: IoT Hub responded to message 3 with status OK_EMPTY
I/System.out: {"deviceId":"SruthiDevice","messageId":13,"temperature":25.30485161791569,"humidity":34.28029086688981}
I/System.out: IoT Hub responded to message 4 with status OK_EMPTY
I/System.out: IoT Hub responded to message 5 with status OK_EMPTY
I/System.out: IoT Hub responded to message 6 with status OK_EMPTY
I/System.out: IoT Hub responded to message 7 with status OK_EMPTY
I/System.out: IoT Hub responded to message 8 with status OK_EMPTY
I/System.out: IoT Hub responded to message 9 with status OK_EMPTY
I/System.out: IoT Hub responded to message 10 with status OK_EMPTY
I/System.out: IoT Hub responded to message 11 with status OK_EMPTY
I/System.out: IoT Hub responded to message 12 with status OK_EMPTY
I/System.out: IoT Hub responded to message 13 with status OK_EMPTY
I/System.out: {"deviceId":"SruthiDevice","messageId":14,"temperature":21.48200465538674,"humidity":45.61054215414081}
I/System.out: IoT Hub responded to message 14 with status OK_EMPTY
I/System.out: {"deviceId":"SruthiDevice","messageId":15,"temperature":24.372334042532238,"humidity":47.4475803242526}
I/System.out: IoT Hub responded to message 15 with status OK_EMPTY
I/System.out: {"deviceId":"SruthiDevice","messageId":16,"temperature":27.570350150978157,"humidity":47.10070366678545}
I/System.out: IoT Hub responded to message 16 with status OK_EMPTY

For HTTPS, we can see the response coming after reconnection and it behaves as expected.

Thanks,
Sruthi

**Comment by prmathur-microsoft** [comment] 2018-01-25 20:43
I believe this issue is related to #192. We are seeing issues over AMQP re connection.  We will keep you updated as we root cause it.

**Comment by prmathur-microsoft** [comment] 2018-02-02 22:48
We had a successful repro of this issue and we believe it is related to underlying issues as to how we handle  our lower level libraries. We are working on fixing it.

**Comment by zolvarga** [comment] 2018-02-22 22:12
@sruthi06 

We checked in the fix to master. We are preparing to release the Java SDK tomorrow.

Best Regards,
Zoltan

**Comment by timtay-microsoft** [comment] 2018-02-27 00:04
The fix for this issue was [released](https://github.com/Azure/azure-iot-sdk-java/releases/tag/2018-2-23) in Device Client 1.9.0 so I'm closing this issue for now. 

Feel free to re-open if you still face issues.

**Closed by timtay-microsoft** 2018-02-27 00:04 UTC
Labels: bug
