### ISSUE TITLE
[Bug Report] Twin sample always mqtt connection lost on updateReportedProperties - getTwin() seems to break it

### ISSUE THREAD

**Issue by dermoritz** [Azure/azure-iot-sdk-java#1590] opened 2022-08-17 14:08 UTC
## Upate

adding `client.getTwin();` at beginning of working variant (see below), it also yields `Mqtt connection lost`

It seems that **getTwin() breaks the MQTT connection**?

# Context

- **OS and version used: Windows 11** 
- **Java runtime used: 17.0.3** <VERSION> (in a command prompt: java -version )
- **SDK version used: device client 2.0.5, x509-provider:2.0.1, provisioning-device-client:2.0.1 **

## Description of the issue
i first created an example based on x509 example what is running fine:

    public void run(String... args) throws Exception {
        DeviceClient client = device.getDevice();
        client.open(false);

        Mono.fromRunnable(() -> {
            int count = 0;
            while (true){
            try {
                client.sendEventAsync(new Message("The message"),(message, exception,context) ->
                        log.info("Message sent: {}({})", message, context),count++);
                Thread.sleep(2000);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }}).subscribe();

    }

i see:
`2022-08-17 15:48:52.903  INFO 38136 --- [-IotHubSendTask] com.bosch.ccsimulateddevice.MainLoop     : Message sent:  Message details: Correlation Id [2fd9adc7-233e-4a71-b144-4ca8e4abc647] Message Id [044ed683-9328-404e-af8d-7f03dcde68db] (0)
2022-08-17 15:48:54.866  INFO 38136 --- [-IotHubSendTask] com.bosch.ccsimulateddevice.MainLoop     : Message sent:  Message details: Correlation Id [719f9658-410f-44e8-ac98-5ec9aa25cecf] Message Id [bb815e37-e23a-41c2-85e7-85abfc3cf200] (1)
2022-08-17 15:48:56.869  INFO 38136 --- [-IotHubSendTask] com.bosch.ccsimulateddevice.MainLoop     : Message sent:  Message details: Correlation Id [59649161-0ea7-421b-8d6f-d5d0d9c0fbc0] Message Id [3d829910-52ea-4a8a-ae1a-abe9d7f0878a] (2)`

## Code sample exhibiting the issue
but when i use code for twin example (instead of the loop):

        DeviceClient client = device.getDevice();
        client.open(false);

        client.setConnectionStatusChangeCallback(this::handleConnectionStatuschange, null);

        client.subscribeToDesiredProperties((twin, context) -> log.info("Desired properties updated: {}", twin), null);

        twin = client.getTwin();
        log.info("Twin: {}", twin);

        TwinCollection reportedProperties = twin.getReportedProperties();
        reportedProperties.put("chargingmode", 7);

        ReportedPropertiesUpdateResponse response = client.updateReportedProperties(reportedProperties);
        twin.getReportedProperties().setVersion(response.getVersion());

        reportedProperties.put("chargingtime", "13:00");
        client.updateReportedProperties(reportedProperties);
        twin.getReportedProperties().setVersion(response.getVersion());
        log.info("Reported properties updated: {}", twin);

I get always an MQTT exception lost exception on `client.updateReportedProperties(reportedProperties);`

The connection status change handler shows that connection is lost an reestablished later, but why this happens always on calling `updateReportedProperties`?

Is there a way to work aroun this or did i something wrong?

## Console log of the issue
This is the log for the latter/ failing case:

```
2022-08-17 16:00:27.591  INFO 39204 --- [           main] c.m.azure.sdk.iot.device.DeviceClient    : Device client opened successfully
2022-08-17 16:00:27.719  INFO 39204 --- [           main] com.bosch.ccsimulateddevice.MainLoop     : Twin: {"properties":{"desired":{"chargingmode":"5","chargingtime":"14:00","$version":1},"reported":{"chargingmode":7,"chargingtime":"13:00","$version":54}}}
2022-08-17 16:00:27.740  WARN 39204 --- [-IotHubSendTask] c.m.a.s.i.d.transport.IotHubTransport    : Encountered exception while sending message with correlation id eb1b0466-4a6b-486c-a6d8-5ee345289973

com.microsoft.azure.sdk.iot.device.transport.TransportException: Cannot publish when mqtt client is disconnected
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.Mqtt.publish(Mqtt.java:193) ~[iot-device-client-2.0.5.jar:na]
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttTwin.send(MqttTwin.java:197) ~[iot-device-client-2.0.5.jar:na]
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttIotHubConnection.sendMessage(MqttIotHubConnection.java:367) ~[iot-device-client-2.0.5.jar:na]
	at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.sendPacket(IotHubTransport.java:1530) ~[iot-device-client-2.0.5.jar:na]
	at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.sendMessages(IotHubTransport.java:746) ~[iot-device-client-2.0.5.jar:na]
	at com.microsoft.azure.sdk.iot.device.transport.IotHubSendTask.run(IotHubSendTask.java:61) ~[iot-device-client-2.0.5.jar:na]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2022-08-17 16:00:27.740  WARN 39204 --- [ Rec: java-sim1] c.m.a.s.iot.device.transport.mqtt.Mqtt   : Mqtt connection lost

org.eclipse.paho.client.mqttv3.MqttException: Verbindung wurde getrennt
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:190) ~[org.eclipse.paho.client.mqttv3-1.2.2.jar:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
Caused by: java.io.EOFException: null
	at java.base/java.io.DataInputStream.readByte(DataInputStream.java:273) ~[na:na]
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:92) ~[org.eclipse.paho.client.mqttv3-1.2.2.jar:na]
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:137) ~[org.eclipse.paho.client.mqttv3-1.2.2.jar:na]
	... 1 common frames omitted

2022-08-17 16:00:27.740  WARN 39204 --- [-IotHubSendTask] c.m.a.s.i.d.transport.IotHubTransport    : Handling an exception from sending message: Attempt number 0

com.microsoft.azure.sdk.iot.device.transport.TransportException: Cannot publish when mqtt client is disconnected
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.Mqtt.publish(Mqtt.java:193) ~[iot-device-client-2.0.5.jar:na]
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttTwin.send(MqttTwin.java:197) ~[iot-device-client-2.0.5.jar:na]
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttIotHubConnection.sendMessage(MqttIotHubConnection.java:367) ~[iot-device-client-2.0.5.jar:na]
	at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.sendPacket(IotHubTransport.java:1530) ~[iot-device-client-2.0.5.jar:na]
	at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.sendMessages(IotHubTransport.java:746) ~[iot-device-client-2.0.5.jar:na]
	at com.microsoft.azure.sdk.iot.device.transport.IotHubSendTask.run(IotHubSendTask.java:61) ~[iot-device-client-2.0.5.jar:na]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2022-08-17 16:00:27.742  WARN 39204 --- [ Rec: java-sim1] c.m.a.s.i.d.transport.IotHubTransport    : Updating transport status to new status DISCONNECTED_RETRYING with reason NO_NETWORK

com.microsoft.azure.sdk.iot.device.transport.ProtocolException: Mqtt connection lost
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.exceptions.PahoExceptionTranslator.convertToMqttException(PahoExceptionTranslator.java:63) ~[iot-device-client-2.0.5.jar:na]
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.Mqtt.connectionLost(Mqtt.java:339) ~[iot-device-client-2.0.5.jar:na]
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.connectionLost(CommsCallback.java:304) ~[org.eclipse.paho.client.mqttv3-1.2.2.jar:na]
	at org.eclipse.paho.client.mqttv3.internal.ClientComms.shutdownConnection(ClientComms.java:439) ~[org.eclipse.paho.client.mqttv3-1.2.2.jar:na]
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:190) ~[org.eclipse.paho.client.mqttv3-1.2.2.jar:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
Caused by: org.eclipse.paho.client.mqttv3.MqttException: Verbindung wurde getrennt
	... 2 common frames omitted
Caused by: java.io.EOFException: null
	at java.base/java.io.DataInputStream.readByte(DataInputStream.java:273) ~[na:na]
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:92) ~[org.eclipse.paho.client.mqttv3-1.2.2.jar:na]
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:137) ~[org.eclipse.paho.client.mqttv3-1.2.2.jar:na]
	... 1 common frames omitted

2022-08-17 16:00:27.742  INFO 39204 --- [ Rec: java-sim1] com.bosch.ccsimulateddevice.MainLoop     : The connection was lost, but is being re-established. Can still send messages, but they won't be sent until the connection is re-established
com.microsoft.azure.sdk.iot.device.transport.ProtocolException: Mqtt connection lost
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.exceptions.PahoExceptionTranslator.convertToMqttException(PahoExceptionTranslator.java:63)
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.Mqtt.connectionLost(Mqtt.java:339)
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.connectionLost(CommsCallback.java:304)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms.shutdownConnection(ClientComms.java:439)
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:190)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: Verbindung wurde getrennt (32109) - java.io.EOFException
	... 2 more
Caused by: java.io.EOFException
	at java.base/java.io.DataInputStream.readByte(DataInputStream.java:273)
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:92)
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:137)
	... 1 more
2022-08-17 16:00:28.629  INFO 39204 --- [ubReconnectTask] com.bosch.ccsimulateddevice.MainLoop     : The connection was successfully established. Can send messages.
2022-08-17 16:00:28.831  WARN 39204 --- [ Rec: java-sim1] c.m.a.s.iot.device.transport.mqtt.Mqtt   : Mqtt connection lost

org.eclipse.paho.client.mqttv3.MqttException: Verbindung wurde getrennt
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:190) ~[org.eclipse.paho.client.mqttv3-1.2.2.jar:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
Caused by: java.io.EOFException: null
	at java.base/java.io.DataInputStream.readByte(DataInputStream.java:273) ~[na:na]
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:92) ~[org.eclipse.paho.client.mqttv3-1.2.2.jar:na]
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:137) ~[org.eclipse.paho.client.mqttv3-1.2.2.jar:na]
	... 1 common frames omitted

2022-08-17 16:00:28.831  WARN 39204 --- [ Rec: java-sim1] c.m.a.s.i.d.transport.IotHubTransport    : Updating transport status to new status DISCONNECTED_RETRYING with reason NO_NETWORK

com.microsoft.azure.sdk.iot.device.transport.ProtocolException: Mqtt connection lost
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.exceptions.PahoExceptionTranslator.convertToMqttException(PahoExceptionTranslator.java:63) ~[iot-device-client-2.0.5.jar:na]
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.Mqtt.connectionLost(Mqtt.java:339) ~[iot-device-client-2.0.5.jar:na]
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.connectionLost(CommsCallback.java:304) ~[org.eclipse.paho.client.mqttv3-1.2.2.jar:na]
	at org.eclipse.paho.client.mqttv3.internal.ClientComms.shutdownConnection(ClientComms.java:439) ~[org.eclipse.paho.client.mqttv3-1.2.2.jar:na]
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:190) ~[org.eclipse.paho.client.mqttv3-1.2.2.jar:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
Caused by: org.eclipse.paho.client.mqttv3.MqttException: Verbindung wurde getrennt
	... 2 common frames omitted
Caused by: java.io.EOFException: null
	at java.base/java.io.DataInputStream.readByte(DataInputStream.java:273) ~[na:na]
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:92) ~[org.eclipse.paho.client.mqttv3-1.2.2.jar:na]
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:137) ~[org.eclipse.paho.client.mqttv3-1.2.2.jar:na]
	... 1 common frames omitted

2022-08-17 16:00:28.831  INFO 39204 --- [ Rec: java-sim1] com.bosch.ccsimulateddevice.MainLoop     : The connection was lost, but is being re-established. Can still send messages, but they won't be sent until the connection is re-established
com.microsoft.azure.sdk.iot.device.transport.ProtocolException: Mqtt connection lost
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.exceptions.PahoExceptionTranslator.convertToMqttException(PahoExceptionTranslator.java:63)
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.Mqtt.connectionLost(Mqtt.java:339)
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.connectionLost(CommsCallback.java:304)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms.shutdownConnection(ClientComms.java:439)
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:190)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: Verbindung wurde getrennt (32109) - java.io.EOFException
	... 2 more
Caused by: java.io.EOFException
	at java.base/java.io.DataInputStream.readByte(DataInputStream.java:273)
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:92)
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:137)
	... 1 more
2022-08-17 16:00:29.637  INFO 39204 --- [ubReconnectTask] com.bosch.ccsimulateddevice.MainLoop     : The connection was successfully established. Can send messages.
2022-08-17 16:00:29.830  INFO 39204 --- [           main] com.bosch.ccsimulateddevice.MainLoop     : Reported properties updated: {"properties":{"desired":{"chargingmode":"5","chargingtime":"14:00","$version":1},"reported":{"chargingmode":7,"chargingtime":"13:00","$version":55}}}
2022-08-17 16:00:29.840  WARN 39204 --- [ Rec: java-sim1] c.m.a.s.iot.device.transport.mqtt.Mqtt   : Mqtt connection lost

org.eclipse.paho.client.mqttv3.MqttException: Verbindung wurde getrennt
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:190) ~[org.eclipse.paho.client.mqttv3-1.2.2.jar:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
Caused by: java.io.EOFException: null
	at java.base/java.io.DataInputStream.readByte(DataInputStream.java:273) ~[na:na]
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:92) ~[org.eclipse.paho.client.mqttv3-1.2.2.jar:na]
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:137) ~[org.eclipse.paho.client.mqttv3-1.2.2.jar:na]
	... 1 common frames omitted

2022-08-17 16:00:29.841  WARN 39204 --- [ Rec: java-sim1] c.m.a.s.i.d.transport.IotHubTransport    : Updating transport status to new status DISCONNECTED_RETRYING with reason NO_NETWORK

com.microsoft.azure.sdk.iot.device.transport.ProtocolException: Mqtt connection lost
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.exceptions.PahoExceptionTranslator.convertToMqttException(PahoExceptionTranslator.java:63) ~[iot-device-client-2.0.5.jar:na]
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.Mqtt.connectionLost(Mqtt.java:339) ~[iot-device-client-2.0.5.jar:na]
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.connectionLost(CommsCallback.java:304) ~[org.eclipse.paho.client.mqttv3-1.2.2.jar:na]
	at org.eclipse.paho.client.mqttv3.internal.ClientComms.shutdownConnection(ClientComms.java:439) ~[org.eclipse.paho.client.mqttv3-1.2.2.jar:na]
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:190) ~[org.eclipse.paho.client.mqttv3-1.2.2.jar:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
Caused by: org.eclipse.paho.client.mqttv3.MqttException: Verbindung wurde getrennt
	... 2 common frames omitted
Caused by: java.io.EOFException: null
	at java.base/java.io.DataInputStream.readByte(DataInputStream.java:273) ~[na:na]
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:92) ~[org.eclipse.paho.client.mqttv3-1.2.2.jar:na]
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:137) ~[org.eclipse.paho.client.mqttv3-1.2.2.jar:na]
	... 1 common frames omitted

2022-08-17 16:00:29.841  INFO 39204 --- [ Rec: java-sim1] com.bosch.ccsimulateddevice.MainLoop     : The connection was lost, but is being re-established. Can still send messages, but they won't be sent until the connection is re-established
com.microsoft.azure.sdk.iot.device.transport.ProtocolException: Mqtt connection lost
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.exceptions.PahoExceptionTranslator.convertToMqttException(PahoExceptionTranslator.java:63)
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.Mqtt.connectionLost(Mqtt.java:339)
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.connectionLost(CommsCallback.java:304)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms.shutdownConnection(ClientComms.java:439)
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:190)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: Verbindung wurde getrennt (32109) - java.io.EOFException
	... 2 more
Caused by: java.io.EOFException
	at java.base/java.io.DataInputStream.readByte(DataInputStream.java:273)
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:92)
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:137)
	... 1 more
2022-08-17 16:00:30.576  INFO 39204 --- [ubReconnectTask] com.bosch.ccsimulateddevice.MainLoop     : The connection was successfully established. Can send messages.

Process finished with exit code 130
```

**Comment by patilsnr** [comment] 2022-08-17 18:01
Hi @dermoritz,

Thanks for reaching out. Could you please try running this again using AMQP? It should hopefully yield some more informative error messages. Additionally, could you please post your device twin JSON (specifically "properties"), feeling free to redact any personal information contained within.

To access your device twin, navigate to your IoT Hub => Devices => Device Twin

**Comment by dermoritz** [comment] 2022-08-18 08:33
Using `IotHubClientProtocol.AMQPS` fixes the issue! 
Using MQTT causes allways a EOFException in `readByte(DataInputStream.java:273)` on getTwin(). 
(updating paho dependency to 1.2.5 didn't helped)
This is the current twin (updating my properties is working fine):

```
{
    "etag": "\"AAAAAAAAAAE=\"",
    "deviceId": "java-sim1",
    "deviceEtag": "NTk5NTQ5NjEz",
    "version": 2,
    "tags": {},
    "properties": {
        "desired": {
            "$metadata": {
                "$lastUpdated": "0001-01-01T00:00:00.0000000Z",
                "$lastUpdatedVersion": 1,
                "chargingmode": {
                    "$lastUpdated": "0001-01-01T00:00:00.0000000Z",
                    "$lastUpdatedVersion": 1
                },
                "chargingtime": {
                    "$lastUpdated": "0001-01-01T00:00:00.0000000Z",
                    "$lastUpdatedVersion": 1
                }
            },
            "$version": 1,
            "chargingmode": "5",
            "chargingtime": "14:00"
        },
        "reported": {
            "$metadata": {
                "$lastUpdated": "2022-08-18T08:26:29.0000000Z",
                "chargingmode": {
                    "$lastUpdated": "2022-08-18T08:26:29.0000000Z"
                },
                "chargingtime": {
                    "$lastUpdated": "2022-08-18T08:26:29.0000000Z"
                }
            },
            "$version": 66,
            "chargingmode": 7,
            "chargingtime": "13:00"
        }
    },
    "capabilities": {
        "iotEdge": false
    },
    "status": "Enabled",
    "statusUpdateTime": "0001-01-01T00:00:00.0000000Z",
    "lastActivityTime": "0001-01-01T00:00:00.0000000Z",
    "connectionState": "Disconnected",
    "cloudToDeviceMessageCount": 0,
    "authenticationType": "SelfSigned",
    "x509Thumbprint": {
        "PrimaryThumbprint": "xyz",
        "SecondaryThumbprint": "xyz"
    }
}
```

**Comment by patilsnr** [comment] 2022-08-18 21:30
Good afternoon @dermoritz,

We'll try and recreate the issue on our end. On first glance, how did you get your timestamps to appear in the format of `"0001-01-01T00:00:00.0000000Z"`? There's a chance that they could be invalid.

**Comment by dermoritz** [comment] 2022-09-12 06:29
I am using 1:1 the provided sample code, only getting the twin and setting one or two properties.
After deleting the complete twin it is exactly recreated this way. Not sure what part is recreating it (server or client).

**Comment by patilsnr** [comment] 2022-09-12 15:40
Awesome, thanks for the update! Looking into this ASAP, will reply with updates as soon as we have them.

**Comment by patilsnr** [comment] 2022-09-14 21:22
Hey again @dermoritz -- I've forked the repo that you linked above and it doesn't seem to build. I'll keep troubleshooting it, but in the meanwhile, are you able to send over a single java file that can reproduce your issue? That would make it much easier on our end of things at the moment. Cheers!

**Comment by dermoritz** [comment] 2022-09-15 06:57
i fixed it, i somehow fucked up by creating a 2nd remote and pushed the wrong state.
Now it should compile. i disabled the test. to make it run you need to set the correct scope and provide certificate - see readme (most likely you know better than me :-P)

**Comment by patilsnr** [comment] 2022-09-16 22:04
Thanks for updating the repository, it successfully builds :) -- when running with JDK 17, however, the following occurs.

`Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'simulatedDevice' defined in file [C:\Code\Bugs\cc-simulated-device\build\classes\java\main\com\bosch\ccsimulateddevice\device\SimulatedDevice.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'provisioningDeviceService' defined in file [C:\Code\Bugs\cc-simulated-device\build\classes\java\main\com\bosch\ccsimulateddevice\device\ProvisioningDeviceService.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'securityProviderFactory' defined in file [C:\Code\Bugs\cc-simulated-device\build\classes\java\main\com\bosch\ccsimulateddevice\configuration\SecurityProviderFactory.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.bosch.ccsimulateddevice.configuration.SecurityProviderFactory$$EnhancerBySpringCGLIB$$b96128a9]: Constructor threw exception; nested exception is java.lang.NullPointerException: Cannot invoke "String.length()" because "s" is null
`

Is there any more insight into the runtime configuration for this program? Specifically how to include the public and private keys, as I cannot find the option to add additional Spring properties within Intellij. Thanks in advance!

**Comment by dermoritz** [comment] 2022-09-19 06:27
This is caused because you didn't provided "public-key.properties" nor "private-key.properties" and add them as additional property source via e.g.:
`-Dspring.config.additional-location=classpath:/public-key.properties,classpath:/private-key.properties`. (to make it connect you need to setup the correct certificate in your DPS)
(not the best way to provide secrets for sure :-P)
Sorry readme as well as error handling are very bare bone yet.

**Comment by patilsnr** [comment] 2022-09-19 21:36
Hi @dermoritz -- we've gotten the code to run. On our end, however, we can call `getTwin()` and `updateTwinProperties()` just fine (using the device twin you provided above) without the MQTT connection breaking. Here are the logs we have:

<img width="1124" alt="image" src="https://user-images.githubusercontent.com/110431552/191123865-1308ec67-ff91-44a3-8b97-73750cf16814.png">

Is there any chance that something local to your development environment could be triggering this issue? We'll keep trying to reproduce in the meanwhile.

**Comment by patilsnr** [comment] 2022-09-20 17:51
Good morning @dermoritz -- We've verified that we're using `IotHubClientProtocol.MQTT` in `SimulatedDevice.java`. To get my DPS set up, the following documents were referenced:

https://learn.microsoft.com/en-us/azure/iot-dps/how-to-verify-certificates
https://learn.microsoft.com/en-us/azure/iot-dps/quick-create-simulated-device-x509?tabs=windows&pivots=programming-language-java

Can you try using MQTT Web Socket? There's a chance this could be a port issue.

**Comment by dermoritz** [comment] 2022-09-21 06:57
Good Morning @patilsnr 
I tried MQTT_WS with no avail. Regarding the docs i know them all. My question was more about a possible different setting in enrollment group. one of the first questions was about the device_twin and an initial one is set in enrollment group but deleting it didn't help.

What confuses me is cause and effect here: it seems that the connection lost is caused by the EOF exception (failed check on reading a byte) - an encoding issue probably? What OS you are using - i am running Win 11.
The connection lost seems not the cause. So what made you think it could be related to a port? Can i check this somehow?

**Comment by dermoritz** [comment] 2022-09-29 07:28
I now was able to check this on another machine - with different azure subscription: There it works!
I will do further research and report back here...

**Comment by patilsnr** [comment] 2022-10-03 16:44
Good morning @dermoritz -- we'd love to stay in the loop regarding how the different Azure subscription is changing the behavior of the SDK. Please feel free to post any logs here so we can go over them as well. Thanks!

**Comment by timtay-microsoft** [comment] 2022-10-05 00:39
Alternatively, #1607 should fix this bug for you. While the service behavior has changed as @patilsnr pointed out, this fix will allow you to use your current hub without any support tickets to the service team.

**Comment by dermoritz** [comment] 2022-10-05 06:19
@patilsnr thanks for doing this additional research. On my end i only came to the conclusion that it is something within iot hub: On my colleagues subscription all was working (he created his subscription and hub last week) even from my machine. On my subscription it was not working for him. Since this problem is currently not pressing so hard i will wait for the fix, or work around with AMQP until it's fixed.

@timtay-microsoft thanks for coming here :-). will this be merged soon or should i cherry pick?

**Comment by timtay-microsoft** [comment] 2022-10-05 15:55
It will be merged soon and released soon, yeah.

**Comment by dermoritz** [comment] 2022-10-14 09:51
For me  update to 2.1.2 fixed it -thanks

**Comment by timtay-microsoft** [comment] 2022-10-14 16:25
Glad to hear it! I'll go ahead and close this issue then now that 2.1.2 has been released.

**Closed by timtay-microsoft** 2022-10-14 16:25 UTC
Labels: bug, fix checked in, service bug, IoTSDK
