### ISSUE TITLE
No disconnection callback

### ISSUE THREAD

**Issue by m-radzikowski** [Azure/azure-iot-sdk-java#467] opened 2019-03-16 18:59 UTC
- **OS and version used:** Linux Min 19.0

- **Java runtime used:** Oracle JDK 1.8.0_191

- **SDK version used:** 1.16.0

# Description of the issue:
I get no events for disconnection from IoT Hub, when I shut internet connection down on my laptop. I've launched send-event example, commented out only message expiry time. I get initial CONNECTED callback, but when I disable internet connection messages are queued, but no callback is executed. After I restore internet connection I see queued messages are sent.

# Console log of the issue:

```
Starting...
Beginning setup.
Successfully read input parameters.
Using communication protocol MQTT.
19:53:55.768 [main] INFO com.microsoft.azure.sdk.iot.device.IotHubConnectionString - IotHubConnectionString object is created successfully, method name is <init> 
19:53:56.027 [main] INFO com.microsoft.azure.sdk.iot.device.DeviceClientConfig - DeviceClientConfig object is created successfully with IotHubName=****, deviceID=**** , method name is <init> 
19:53:56.032 [main] INFO com.microsoft.azure.sdk.iot.device.DeviceIO - DeviceIO object is created successfully, method name is <init> 
Successfully created an IoT Hub client.
19:53:56.032 [main] INFO com.microsoft.azure.sdk.iot.device.DeviceClient - Setting SASTokenExpiryTime as 2400 seconds, method name is setOption_SetSASTokenExpiryTime 
Updated token expiry time to 2400
19:53:56.724 [main] INFO com.microsoft.azure.sdk.iot.device.transport.IotHubTransport - The connection to the IoT Hub has been established, method name is onConnectionEstablished 

CONNECTION STATUS UPDATE: CONNECTED
CONNECTION STATUS REASON: CONNECTION_OK
CONNECTION STATUS THROWABLE: null

19:53:56.728 [main] INFO com.microsoft.azure.sdk.iot.device.DeviceClient - Connection opened with success, method name is open 
Opened connection to IoT Hub.
Sending the following event messages:
19:53:57.015 [main] INFO com.microsoft.azure.sdk.iot.device.DeviceIO - Message with messageid 95d68d3b-5915-407a-bf82-518d5169f462 along with callback and callbackcontext is added to the queue, method name is sendEventAsync 
Wait for 10 second(s) for response from the IoT Hub...
19:53:57.018 [azure-iot-sdk-IotHubSendTask] INFO com.microsoft.azure.sdk.iot.device.transport.IotHubTransport - Get the message from waiting message queue to be sent to IoT Hub, method name is sendMessages 
19:53:57.098 [azure-iot-sdk-IotHubSendTask] INFO com.microsoft.azure.sdk.iot.device.transport.IotHubTransport - Invoking the callback function for sent message, IoT Hub responded to message with status OK_EMPTY, method name is invokeCallbacks 
IoT Hub responded to message 95d68d3b-5915-407a-bf82-518d5169f462 with status OK_EMPTY
19:54:07.023 [main] INFO com.microsoft.azure.sdk.iot.device.DeviceIO - Message with messageid c2572cca-9023-4ed9-824c-84243408d7d5 along with callback and callbackcontext is added to the queue, method name is sendEventAsync 
Wait for 10 second(s) for response from the IoT Hub...
19:54:07.028 [azure-iot-sdk-IotHubSendTask] INFO com.microsoft.azure.sdk.iot.device.transport.IotHubTransport - Get the message from waiting message queue to be sent to IoT Hub, method name is sendMessages 
19:54:17.026 [main] INFO com.microsoft.azure.sdk.iot.device.DeviceIO - Message with messageid 507a8bbc-e2bd-4460-98c4-3b3e625cd33b along with callback and callbackcontext is added to the queue, method name is sendEventAsync 
Wait for 10 second(s) for response from the IoT Hub...
19:54:17.028 [azure-iot-sdk-IotHubSendTask] INFO com.microsoft.azure.sdk.iot.device.transport.IotHubTransport - Get the message from waiting message queue to be sent to IoT Hub, method name is sendMessages 
19:54:23.929 [azure-iot-sdk-IotHubSendTask] INFO com.microsoft.azure.sdk.iot.device.transport.IotHubTransport - Invoking the callback function for sent message, IoT Hub responded to message with status OK_EMPTY, method name is invokeCallbacks 
IoT Hub responded to message c2572cca-9023-4ed9-824c-84243408d7d5 with status OK_EMPTY
19:54:23.938 [azure-iot-sdk-IotHubSendTask] INFO com.microsoft.azure.sdk.iot.device.transport.IotHubTransport - Invoking the callback function for sent message, IoT Hub responded to message with status OK_EMPTY, method name is invokeCallbacks 
IoT Hub responded to message 507a8bbc-e2bd-4460-98c4-3b3e625cd33b with status OK_EMPTY
```

From what I see from other issues, for example [here](https://github.com/Azure/azure-iot-sdk-java/issues/316#issuecomment-442588979), it should report connection changes properly.

I'm using Free (F1) IoT Hub plan for now, if that matters.

**Comment by timtay-microsoft** [comment] 2019-03-18 18:20
How long does your computer stay disconnected for? If you only unplug and then replug in your ethernet quickly, the SDK won't report any connectivity issues. If you leave the computer disconnected for long enough, you should see this callback fired.

**Comment by m-radzikowski** [comment] 2019-03-19 07:56
You can see by the timestamps in the log, that:
- at 19:53:57 the first message was added to the queue and sent correctly, receiving confirmation (status OK_EMPTY) almost immediately,
- at 19:54:07 the second message was added to the queue, internet was already disconnected,
- at 19:54:17 the third message was added to the queue,
- at 19:54:23 both (second and third) messages were sent, meaning connection was restored.

So the internet was disconnected from before 19:54:07 to around 19:54:23, which gives us at least 10 seconds. Isn't it enough for the SDK to report connection lost?

I've repeated the test with 120 seconds of no internet connectivity, still no diconnection info. Tested on both OracleJDK and OpenJDK, Java 8.

**Comment by timtay-microsoft** [comment] 2019-03-19 21:41
For the messages that you call ```java sendEventAsync(...)``` on after you disconnect, can you verify that the messages aren't being received by the iothub? The azure portal gives you a real time view of the count of messages coming in so you should be able to verify if the flow of messages stops when you expect it to stop. If the SDK isn't reporting connection loss, it may be because the connection was never actually lost somehow.

If you have access to a different tier of IotHub, I recommend trying out AMQP to see if you get different behavior. Unfortunately, there is currently a bug that prevents this SDK from using AMQP against a free tier iot hub. Any B or S tier should work.

**Comment by timtay-microsoft** [comment] 2019-03-19 22:56
For the sake of testing this scenario, can you also comment out the line that closes the device client after 2 seconds? I'm worried that may be interfering with the connection status reporting. It would be better if you just left the device client open until you kill the application

**Comment by m-radzikowski** [comment] 2019-03-23 01:31
I've changed loop to send one message every 10 seconds, and it's not closing device client until the end. I've extracted this example to separate repository - very small changes to the original, you can build and run it easily: https://github.com/m-radzikowski/azure-iot-sdk-java-issue467

I've run it in a virtual machine with Debian 9. Exactly the same behavior after it's disconnected from the network.

Additionally, what I observe, is:
- when the loop ends, I get callbacks with `MESSAGE_CANCELLED_ONCLOSE`, which is ok,
- then, after a few seconds, is the connection state update `DISCONNECTION` with reason `CLIENT_CLOSE`,
- then, after 30 seconds, there is `Connection closed with success, method name is closeNow` log with message `Shutting down...` from the example,
- application is not closing, it **waits indefinately probably for some IoT background thread**, which is probably a bigger issue then lack of disconnection messages itself...

See the log - 3 messages, internet was disconnected right after first one was sent successfully. I had to sigint app at the end after few minutes of waiting.

```
Starting...
Beginning setup.
Successfully read input parameters.
Using communication protocol MQTT.
2019-03-23 02:22:43:089 [main] INFO com.microsoft.azure.sdk.iot.device.IotHubConnectionString - IotHubConnectionString object is created successfully, method name is <init> 
2019-03-23 02:22:43:243 [main] INFO com.microsoft.azure.sdk.iot.device.DeviceClientConfig - DeviceClientConfig object is created successfully with IotHubName=alcox.azure-devices.net, deviceID=dev1 , method name is <init> 
2019-03-23 02:22:43:247 [main] INFO com.microsoft.azure.sdk.iot.device.DeviceIO - DeviceIO object is created successfully, method name is <init> 
Successfully created an IoT Hub client.
2019-03-23 02:22:43:247 [main] INFO com.microsoft.azure.sdk.iot.device.DeviceClient - Setting SASTokenExpiryTime as 2400 seconds, method name is setOption_SetSASTokenExpiryTime 
Updated token expiry time to 2400
2019-03-23 02:22:43:911 [main] INFO com.microsoft.azure.sdk.iot.device.transport.IotHubTransport - The connection to the IoT Hub has been established, method name is onConnectionEstablished 

CONNECTION STATUS UPDATE: CONNECTED
CONNECTION STATUS REASON: CONNECTION_OK
CONNECTION STATUS THROWABLE: null

2019-03-23 02:22:43:915 [main] INFO com.microsoft.azure.sdk.iot.device.DeviceClient - Connection opened with success, method name is open 
Opened connection to IoT Hub.
Sending the following event messages:
2019-03-23 02:22:43:918 [main] INFO com.microsoft.azure.sdk.iot.device.Message - Setting message property, method name is setProperty 
2019-03-23 02:22:43:929 [main] INFO com.microsoft.azure.sdk.iot.device.Message - The message with messageid cf5b6bb8-9d32-4927-a322-5ec8dddc5e28 has expiry time as 10000 milliseconds and the message will expire on Sat Mar 23 02:22:53 CET 2019, method name is setExpiryTime 
{"deviceId":"MyJavaDevice","messageId":0,"temperature":25.243909568944503,"humidity":40.509537588645514}
2019-03-23 02:22:43:930 [main] INFO com.microsoft.azure.sdk.iot.device.DeviceIO - Message with messageid cf5b6bb8-9d32-4927-a322-5ec8dddc5e28 along with callback and callbackcontext is added to the queue, method name is sendEventAsync 
Wait for 10 second(s) for response from the IoT Hub...
2019-03-23 02:22:43:935 [azure-iot-sdk-IotHubSendTask] INFO com.microsoft.azure.sdk.iot.device.transport.IotHubTransport - Get the message from waiting message queue to be sent to IoT Hub, method name is sendMessages 
2019-03-23 02:22:44:015 [azure-iot-sdk-IotHubSendTask] INFO com.microsoft.azure.sdk.iot.device.transport.IotHubTransport - Invoking the callback function for sent message, IoT Hub responded to message with status OK_EMPTY, method name is invokeCallbacks 
IoT Hub responded to message cf5b6bb8-9d32-4927-a322-5ec8dddc5e28 with status OK_EMPTY
2019-03-23 02:22:53:932 [main] INFO com.microsoft.azure.sdk.iot.device.Message - Setting message property, method name is setProperty 
2019-03-23 02:22:53:933 [main] INFO com.microsoft.azure.sdk.iot.device.Message - The message with messageid 19f26f8f-4767-45c7-a2e0-5a5a59ad0b69 has expiry time as 10000 milliseconds and the message will expire on Sat Mar 23 02:23:03 CET 2019, method name is setExpiryTime 
{"deviceId":"MyJavaDevice","messageId":1,"temperature":26.446916828294505,"humidity":31.04324465090111}
2019-03-23 02:22:53:933 [main] INFO com.microsoft.azure.sdk.iot.device.DeviceIO - Message with messageid 19f26f8f-4767-45c7-a2e0-5a5a59ad0b69 along with callback and callbackcontext is added to the queue, method name is sendEventAsync 
Wait for 10 second(s) for response from the IoT Hub...
2019-03-23 02:22:53:935 [azure-iot-sdk-IotHubSendTask] INFO com.microsoft.azure.sdk.iot.device.transport.IotHubTransport - Get the message from waiting message queue to be sent to IoT Hub, method name is sendMessages 
2019-03-23 02:23:03:934 [main] INFO com.microsoft.azure.sdk.iot.device.Message - Setting message property, method name is setProperty 
2019-03-23 02:23:03:935 [main] INFO com.microsoft.azure.sdk.iot.device.Message - The message with messageid 365dbba1-5612-4edf-a903-2560a8aea28a has expiry time as 10000 milliseconds and the message will expire on Sat Mar 23 02:23:13 CET 2019, method name is setExpiryTime 
{"deviceId":"MyJavaDevice","messageId":2,"temperature":21.6295032726495,"humidity":30.593144945747746}
2019-03-23 02:23:03:936 [main] INFO com.microsoft.azure.sdk.iot.device.DeviceIO - Message with messageid 365dbba1-5612-4edf-a903-2560a8aea28a along with callback and callbackcontext is added to the queue, method name is sendEventAsync 
Wait for 10 second(s) for response from the IoT Hub...
2019-03-23 02:23:03:945 [azure-iot-sdk-IotHubSendTask] INFO com.microsoft.azure.sdk.iot.device.transport.IotHubTransport - Get the message from waiting message queue to be sent to IoT Hub, method name is sendMessages 
Closing
2019-03-23 02:23:13:939 [main] INFO com.microsoft.azure.sdk.iot.device.transport.IotHubTransport - Invoking the callback function for sent message, IoT Hub responded to message with status MESSAGE_CANCELLED_ONCLOSE, method name is invokeCallbacks 
IoT Hub responded to message 19f26f8f-4767-45c7-a2e0-5a5a59ad0b69 with status MESSAGE_CANCELLED_ONCLOSE
2019-03-23 02:23:13:940 [main] INFO com.microsoft.azure.sdk.iot.device.transport.IotHubTransport - Invoking the callback function for sent message, IoT Hub responded to message with status MESSAGE_CANCELLED_ONCLOSE, method name is invokeCallbacks 
IoT Hub responded to message 365dbba1-5612-4edf-a903-2560a8aea28a with status MESSAGE_CANCELLED_ONCLOSE

CONNECTION STATUS UPDATE: DISCONNECTED
CONNECTION STATUS REASON: CLIENT_CLOSE
CONNECTION STATUS THROWABLE: null

2019-03-23 02:23:45:947 [main] INFO com.microsoft.azure.sdk.iot.device.DeviceClient - Connection closed with success, method name is closeNow 
List of messages that were cancelled on close:[19f26f8f-4767-45c7-a2e0-5a5a59ad0b69, 365dbba1-5612-4edf-a903-2560a8aea28a]
Shutting down...
```

I have no access to other tiers IoT Hub right now. But this should be easily reproducible - you only need a device connection string from IoT Hub and you can launch the example from my repo. Please let me know if I can help with anything else.

**Comment by timtay-microsoft** [comment] 2019-03-25 18:11
I'm seeing the expected connection status callbacks when I run this on windows, so I'll spin up a new Debian 9 vm and try out your sample, sure.

**Comment by anhashia** [comment] 2019-05-20 21:27
@m-radzikowski . On Ubuntu, it will take time as it will rely on underlying **third party** paho MQTT library to timeout on period of inactivity.  Java SDK client set the keep-alive timeout to **230** seconds.

So you will have to wait for some time for this time out to occur.

Below is log from Ubuntu 16.04  machine where CONNECTION STATUS UPDATE gets update in SDK after timeout occurs.

`````
"deviceId":"MyJavaDevice","iteration":0" + "messageid":243,"temperature":24.595747148812904,"humidity":39.63999782153179}
{"deviceId":"MyJavaDevice","iteration":0" + "messageid":244,"temperature":27.541375941258963,"humidity":41.21776986610598}
{"deviceId":"MyJavaDevice","iteration":0" + "messageid":245,"temperature":24.55842483805478,"humidity":42.672071750602996}
{"deviceId":"MyJavaDevice","iteration":0" + "messageid":246,"temperature":21.333219300327826,"humidity":33.594617730915246}
May 20, 2019 2:13:38 PM org.eclipse.paho.client.mqttv3.internal.ClientState checkForActivity
SEVERE: MyDevice9: Timed out as no activity, keepAlive=230,000 lastOutboundActivity=1,558,386,588,460 lastInboundActivity=1,558,386,338,537 time=1,558,386,818,459 lastPing=1,558,386,588,460
com.microsoft.azure.sdk.iot.device.exceptions.ProtocolException: Mqtt connection lost

CONNECTION STATUS UPDATE: DISCONNECTED_RETRYING
CONNECTION STATUS REASON: NO_NETWORK
CONNECTION STATUS THROWABLE: Mqtt connection lost
```````

**Comment by pawankaushal** [comment] 2019-05-21 05:19
I am not getting callbacks on HTTPS protocol. Is this known limitation?

**Comment by timtay-microsoft** [comment] 2019-05-21 19:22
@pawankaushal HTTPS protocol is connection-less, so the connection status callbacks will never fire for HTTPS device clients. This is by design.

**Comment by timtay-microsoft** [comment] 2019-05-30 20:33
Since anhashia has shown the cause of this unexpected behavior is due to the long delay between keep-alive messages, I'm going to close this issue. We have a separate issue open discussing if this heartbeat should be configurable or not.

**Comment by az-iot-builder-01** [comment] 2019-05-30 20:33
@m-radzikowski, @pawankaushal, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Closed** 2019-05-30 20:33 UTC
Labels: investigation-required
