### ISSUE TITLE
[Device Client - MQTT] SDK allows to keep sending messages even when the connection is lost

### ISSUE THREAD

**Issue by pizerg** [Azure/azure-iot-sdk-java#220] opened 2018-04-05 09:31 UTC
- **OS and version used:** Raspbian Jessie

- **Java runtime used:** 1.8

- **SDK version used:**  iot-device-client 1.9.0

# Description of the issue:
Reopening the issue #99 

The following is still happening:

> The SDK allows to keep sending messages even when the connection is lost, this becomes a problem as the callback is invoked immediately with status OK_EMPTY

# Code sample exhibiting the issue:

- Set up a client using connection string + MQTT

- Open the connection

- Disconnect internet access

- Send a message to receive an OK_EMPTY status in the callback.

**Comment by timtay-microsoft** [comment] 2018-04-11 22:02
Are you only seeing this behavior with MQTT? What about MQTT_WS?

Either way, I suspect this will be fixed in our next release which is slated for 4/13. I can dig into this further if you are still seeing this issue after that.

**Comment by timtay-microsoft** [comment] 2018-04-17 04:32
Are you still seeing this same behavior with Device client version 1.10.0?

**Comment by pizerg** [comment] 2018-04-18 10:15
My initial tests show that now it doesn't reply with OK_EMPTY status immediately if the connection has dropped, however the message expiration time is not matching the "message expired" callback invocation timing, I've set the message expiration time at 4 seconds and I receive the "message expired" callback +/- 15 seconds after it's sent to the device client

**Comment by timtay-microsoft** [comment] 2018-04-23 18:43
The expiry time on a message is not a guarantee. It should be treated as a rough estimate on when to expect the callback. The discrepancy you are seeing is due to the retry policy you set (or didn't set). Every time a message attempts to be sent by our internal queuing, its expiry time is checked. While a message is waiting to be retried, it is not actively checking to see if it has expired. In your case, I expect that a message is waiting some X seconds to retry and that the message expires during that delay, but doesn't notify you until it tries to be sent again. This is expected behavior.

Since you are no longer seeing an issue with messages being sent after a connection is lost, I'm closing this issue. Feel free to re-open this issue if you face any further issues.

@pizerg  thank you for your contribution to our open-sourced project!  Please help us improve by filling out this 2-minute [customer satisfaction survey](https://www.surveymonkey.com/r/Q5PLZ3V).

**Closed by timtay-microsoft** 2018-04-23 18:43 UTC
Labels: investigation-required
