### ISSUE TITLE
[Technical Question] Provisioning client SDK won't add secondary certificate

### ISSUE THREAD

**Issue by ybdc-jl** [Azure/azure-iot-sdk-java#1220] opened 2021-05-24 07:26 UTC
- **OS and version used:** Windows 10 19041.985
- **Java runtime used:** java version "11.0.10" 2021-01-19 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.10+8-LTS-162)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.10+8-LTS-162, mixed mode)

- **SDK version used:** Compiled from a162b280

# Description of the issue:
Hi! I'm trying to follow the provisioning/provisioning-samples/service-enrollment-sample and provisioning-X509-sample. It's possible to enroll the device in DPS with two certificates, but I couldn't figure out where to pass the secondary certificate during the registration in IoT Hub.

After the provisioning, the primary and secondary certificate thumbprints show up correctly in DPS but for IoT Hub the two thumbprints stays the same. And of course simulating sending message to IoT Hub with secondary key won't work.

# Code sample exhibiting the issue:
```
// enroll
// you can add two certs in this step
Attestation attestation = X509Attestation.createFromClientCertificates(FirstPem, SecondPem);
IndividualEnrollment individualEnrollment = new IndividualEnrollment(registrationId, attestation);
IndividualEnrollment individualEnrollmentResult = provisioningServiceClient.createOrUpdateIndividualEnrollment(individualEnrollment);

// register
// there is no way to pass the second certificate
SecurityProvider securityProviderX509 = new SecurityProviderX509Cert(FirstPem, FirstKey, new LinkedList<>());
ProvisioningDeviceClient provisioningDeviceClient = ProvisioningDeviceClient.create(GLOBAL_ENDPOINT, ID_SCOPE, PROVISIONING_DEVICE_CLIENT_TRANSPORT_PROTOCOL, securityProviderX509);
provisioningDeviceClient.registerDevice(new ProvisioningDeviceClientRegistrationCallbackImpl(), provisioningStatus);
```

# Console log of the issue:
NA

**Comment by timtay-microsoft** [comment] 2021-05-24 15:51
> Attestation attestation = X509Attestation.createFromClientCertificates(FirstPem, SecondPem);

This line creates the attestation with a primary and a secondary x509 certificate. That means you will be able to use either the first certificate or second certificate when you create the security provider later on. There is no need to provide both the primary and secondary certificate when registering your device. 

The reason we allow a primary/secondary model here is just so that if you need to revoke one of those certificates for whatever reason, you still have a backup certificate that will still work for you.

With all that in mind, is there a reason why you still want to use both the primary and secondary certificates during device registration?

**Comment by ybdc-jl** [comment] 2021-05-25 01:04
> > Attestation attestation = X509Attestation.createFromClientCertificates(FirstPem, SecondPem);
> 
> This line creates the attestation with a primary and a secondary x509 certificate. That means you will be able to use either the first certificate or second certificate when you create the security provider later on. There is no need to provide both the primary and secondary certificate when registering your device.
> 
> The reason we allow a primary/secondary model here is just so that if you need to revoke one of those certificates for whatever reason, you still have a backup certificate that will still work for you.
> 
> With all that in mind, is there a reason why you still want to use both the primary and secondary certificates during device registration?

Hi @timtay-microsoft, thank you for your quick response.

Yes I understand that the secondary cert is only used to make sure the connection is not broken when the primary certificate is expired/revoked/whatever.

The thing is if I pass two certs during enrollment in DPS and register it in IoT Hub (running the previous snippets)

```
Attestation attestation = X509Attestation.createFromClientCertificates(FirstPem, SecondPem);
IndividualEnrollment individualEnrollment = new IndividualEnrollment(registrationId, attestation);
IndividualEnrollment individualEnrollmentResult = provisioningServiceClient.createOrUpdateIndividualEnrollment(individualEnrollment);

SecurityProvider securityProviderX509 = new SecurityProviderX509Cert(FirstPem, FirstKey, new LinkedList<>());
ProvisioningDeviceClient provisioningDeviceClient = ProvisioningDeviceClient.create(GLOBAL_ENDPOINT, ID_SCOPE, PROVISIONING_DEVICE_CLIENT_TRANSPORT_PROTOCOL, securityProviderX509);
provisioningDeviceClient.registerDevice(new ProvisioningDeviceClientRegistrationCallbackImpl(), provisioningStatus);
```

Both the thumbprints shows up correctly in DPS, e.g.
```
Primary Certificate Thumbprint
DD344C0A8D514C3D25A19632B4CE4B769FA01AA4

Secondary Certificate Thumbprint
BD743C0BA40A35422725A2DAAF5133D6E4DFDFC2
```
But in IoT Hub, only the first thumbprint is registered
```
Primary Thumbprint
E4B83E95E732B4587A25B183371943425FE99C56BF5F18C3B6ED2A191987483D

Secondary Thumbprint
E4B83E95E732B4587A25B183371943425FE99C56BF5F18C3B6ED2A191987483D
```
And sending messages using the secondary certificate will raise `Connection Refused: not authorised` error. Is there anything I'm missing?

**Comment by timtay-microsoft** [comment] 2021-05-25 16:19
This sounds like a service behavior question, then. After a successful registration, it is DPS that tells your IoT Hub to add this new device with all the authentication details. My hunch is that DPS doesn't propagate the secondary thumbprint to IoT Hub either by mistake or by design (since the DPS registration only used the primary certificates). I'm working with the relevant service teams to understand this a bit better, but this doesn't appear to be an SDK bug.

**Comment by ybdc-jl** [comment] 2021-05-26 07:37
> This sounds like a service behavior question, then. After a successful registration, it is DPS that tells your IoT Hub to add this new device with all the authentication details. My hunch is that DPS doesn't propagate the secondary thumbprint to IoT Hub either by mistake or by design (since the DPS registration only used the primary certificates). I'm working with the relevant service teams to understand this a bit better, but this doesn't appear to be an SDK bug.

Thank you @timtay-microsoft, I think you are correct that it's not a SDK bug but a design issue. Just did a quick test with C# sdk and it behaves the same: you can submit two certificates in DPS, but only the one you just registered with works in the IoT Hub, and the two thumbprints in the Hub are the same. To post with the other certificate you need to re-provision with it first, which is kind of against the purpose I guess.

**Comment by timtay-microsoft** [comment] 2021-05-26 16:24
Yep, I have confirmed with the service teams around this scenario, and they say that this behavior is by design

**Comment by timtay-microsoft** [comment] 2021-06-02 15:47
Closing this thread as it is a service side issue, not an SDK side issue

**Comment by abhipsaMisra** [comment] 2021-07-01 16:16
Re-opening and closing to work around dashboard issue.

**Comment by abhipsaMisra** [comment] 2021-07-01 16:16
Closing the issue.

**Closed by abhipsaMisra** 2021-07-01 16:16 UTC
Labels: IoTSDK, area-service
