### ISSUE TITLE
Error on get tags on DeviceTwinDevice after query all devices

### ISSUE THREAD

**Issue by cafijo** [Azure/azure-iot-sdk-java#522] opened 2019-05-20 11:47 UTC
- **OS and version used:** <VERSION>alpine3.9 

- **Java runtime used:** <VERSION>openjdk:8u212-jre

- **SDK version used:** <VERSION>iot-service-client 1.17.0

# Description of the issue:
Error on get tags on DeviceTwinDevice after query all devices. This error was not happening the past month.

# Code sample exhibiting the issue:
```
SqlQuery sqlQuery = SqlQuery.createSqlQuery("*", SqlQuery.FromType.DEVICES, null, null);
Query twinQueryCollection = twinClient.queryTwin(sqlQuery.getQuery());
 while (twinClient.hasNextDeviceTwin(twinQueryCollection)) {
            DeviceTwinDevice deviceTwin = twinClient.getNextDeviceTwin(twinQueryCollection));
if(!deviceTwin.getTags().isEmpty()) {
--------
 }
```
# Console log of the issue:
```
java.lang.IllegalArgumentException: Key cannot contain illegal unicode control characters '.', '$', ' '
	at com.microsoft.azure.sdk.iot.service.devicetwin.Pair.<init>(Pair.java:29) ~[iot-service-client-1.17.0.jar!/:na]
	at com.microsoft.azure.sdk.iot.service.devicetwin.DeviceTwinDevice.mapToSet(DeviceTwinDevice.java:598) ~[iot-service-client-1.17.0.jar!/:na]
	at com.microsoft.azure.sdk.iot.service.devicetwin.DeviceTwinDevice.getTags(DeviceTwinDevice.java:218) ~[iot-service-client-1.17.0.jar!/:na]
```
I do the same using query iothub from Portal Azure and device tags contains $ on tag's key, like $version and $metadata. Only occurs on IoTHub deployed on EE. UU West. IoTHub deployed in Europe West, the same query does not contains $ on device tags key. I add a snapshot of response queries on different IotHub. 
**West Europe Response:**
![WestEurope](https://user-images.githubusercontent.com/1439380/58019314-894ba600-7b05-11e9-88f0-e3bfa73b8d7e.PNG)
**West EE.UU Response:**
![WestUS](https://user-images.githubusercontent.com/1439380/58019316-894ba600-7b05-11e9-9b44-22648b9d472f.PNG)

**Comment by pawankaushal** [comment] 2019-05-21 05:06
The same issue is reproduced on my setup . 

The culprit seems to be :

**Comment by timtay-microsoft** [comment] 2019-05-21 19:07
I'm going to take out this device side validation of twin fields. This SDK really shouldn't be validating data like this sent from the service, and this same validation will occur on the service side for customer provided data. 

I'll look into removing this device side validation to unblock you.

**Comment by timtay-microsoft** [comment] 2019-05-21 19:09
The fact that you are getting different twin from hubs deployed in different regions is interesting, though. I'll take a look into that as well.

**Comment by bearrito** [comment] 2019-05-24 20:33
This is also affecting us in SouthCentral Region. We are opening a Severity A ticket since this is affecting production workloads for our fleet.

**Comment by timtay-microsoft** [comment] 2019-05-29 18:08
This IllegalArgumentException was caused by a regression from the iothub side, and the service is rolling back to fix this issue soon.

**Comment by timtay-microsoft** [comment] 2019-06-04 19:50
Since this was a service side issue rather then an SDK issue, and an ticket has been opened internally to track it, I'm going to close this issue.

**Comment by az-iot-builder-01** [comment] 2019-06-04 19:50
@cafijo, @pawankaushal, @bearrito, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Closed** 2019-06-04 19:50 UTC
Labels: service bug

**Comment by raj2103** [comment] 2019-06-07 19:19
@timtay-microsoft - I am still seeing this error with `iot-service-client version 1.17.1` and as a result all queries on module twin tags are failing.

**Comment by datoga** [comment] 2019-06-12 05:14
@timtay-microsoft How we could track the changes on IoT services? The fact is the issue is not really solved until the service would be changed!

**Comment by gjswalling** [comment] 2019-06-25 20:09
Unfortunately, the IoT Hub Service side code is not available for the same type of tracking, and it's taking longer than expected to rollout the fix for all hubs.  @az-iot-builder-01 @raj2103 @datoga please feel free to create a support case so we can work with you to mitigate the issue quicker.
