### ISSUE TITLE
[MQTT] [C2D] Only 1 message received if send before subscribe without messageid

### ISSUE THREAD

**Issue by allenhula** [Azure/azure-iot-sdk-java#101] opened 2017-06-08 04:47 UTC
Environment:
- **OS and version used:** Windows 10
- **Java runtime version used:** 1.8.0_131
- **SDK version used:** iot-device-client 1.2.28

# Description of the issue:
Send several C2D messages at first without setting the messageid, then using MQTT protocol on device side to receive the messages, only 1 message will be received no matter how many messages sent.
But if send messages with messageid, then device can receive all messages successfully.
And if start receiver at first then sender, messages can be received successfully.

So to repro this issue, two key conditions:

1. messages send without message id
2. send at first then receive later

# Code sample exhibiting the issue:
C2D Sender (without setting messageid): 
```
ServiceClient serviceClient = ServiceClient.createFromConnectionString(connectionString, IotHubServiceClientProtocol.AMQPS);
serviceClient.open();
for (int i=0; i<5; i++) {
	Message messageToSend = new Message("Cloud to device message " + i);
	//messageToSend.setMessageId(UUID.randomUUID().toString());
	messageToSend.setDeliveryAcknowledgement(DeliveryAcknowledgement.Full);

	serviceClient.send(deviceId, messageToSend);
	System.out.println("Message sent to device " + i);
}
serviceClient.close();
```
C2D Receiver:
```
DeviceClient client = new DeviceClient(connString, IotHubClientProtocol.MQTT);
MessageCallback callback = new MessageCallback();
client.setMessageCallback(callback, null);
client.open();

private static class MessageCallback implements
com.microsoft.azure.sdk.iot.device.MessageCallback {
	public IotHubMessageResult execute(Message msg, Object context) {
		System.out.println("Received message from hub: "
		+ new String(msg.getBytes(), Message.DEFAULT_IOTHUB_MESSAGE_CHARSET)
		+ " with message id " + msg.getMessageId());

		return IotHubMessageResult.COMPLETE;
	}
}
```

# Console log of the issue:
Sender output (5 messages sent):

> Message sent to device 0
> Message sent to device 1
> Message sent to device 2
> Message sent to device 3
> Message sent to device 4

Receiver output (only 1 message received)

> Received message from hub: Cloud to device message 4 with message id 7f67122e-c113-48f1-9a4b-f37280e7a55a

**Comment by allenhula** [comment] 2017-06-08 05:00
After some debugging in receiver side by comparing the situations with and without messageid, found that the main difference comes in **topic** argument passed into messageArrived(String **topic**, MqttMessage mqttMessage) method of class Mqtt.
When messages sent with messageid, the topic here is having mid parameter, such as "devices/newdevice007/messages/devicebound/%24.mid=55a2e75e-ddea-4429-99f3-c702c40ef863&%24.to=%2Fdevices%2Fnewdevice007%2Fmessages%2Fdevicebound&iothub-ack=full".
But if sent without messageid, the topic here has no mid parameter, such as "devices/newdevice007/messages/devicebound/%24.to=%2Fdevices%2Fnewdevice007%2Fmessages%2Fdevicebound&iothub-ack=full". Thus only last message returned as all five message parsed with same topic here.
Based on my understanding, if sender doesn't set the messageid explicitly, iothub will set it for us, then the topic passed in MessageArrived should still contain the messageid set by iothub. So somehow it is missing here.

**Comment by allenhula** [comment] 2017-06-08 05:06
Tried same scenario with .NET SDK, everything works fine. So just Java SDK issue.

**Comment by timtay-microsoft** [comment] 2017-06-21 17:55
Hi Allenhula,

Thanks for doing some legwork on this already. You are absolutely correct that that is where the issue is happening. The fix should be out soon and I'll update this thread when it is.

**Comment by prmathur-microsoft** [comment] 2017-07-13 01:07
Fix for this issue is checked in @77011ed1c33509449a7f63d3f3c626accf310aa1. Please give it a try and let us know.

**Comment by prmathur-microsoft** [comment] 2017-07-15 01:19
Maven package for the same is also released. Follow our release from https://github.com/Azure/azure-iot-sdk-java/releases/tag/2017-7-14

**Closed by prmathur-microsoft** 2017-07-15 01:19 UTC
Labels: bug, fix checked in
