### ISSUE TITLE
EnvironmentalSensor sample reports writeable properties incorrectly (type mismatch)

### ISSUE THREAD

**Issue by wickste** [Azure/azure-iot-sdk-java#657] opened 2019-12-23 15:01 UTC
- **OS and version used:** Windows 10

- **Java runtime used:** 13.0.1

- **SDK version used:** latest preview with PnP support

# Description of the issue:
EnvironmentalSensor sample reports writeable properties incorrectly as objects, whereas they should be strongly typed (e.g. 'name' should be string, 'brightness' should be long). As a result the user will see error messages in the Azure IoT Explorer tool when following the quickstart tutorial.

# Code sample exhibiting the issue:
Tutorial is here: https://docs.microsoft.com/en-us/azure/iot-pnp/quickstart-connect-pnp-device-java

Code sample is here: https://github.com/Azure-Samples/azure-iot-samples-java/blob/master/digital-twin/Samples/device/JdkSample/environmental-sensor-sample/src/main/java/com/microsoft/azure/sdk/iot/digitaltwin/sample/EnvironmentalSensor.java

The error will be observed on step #10 of the section "Use the Azure IoT explorer to validate the code"

**Comment by davilu** [comment] 2019-12-27 08:20
@wickste This is by design. The definition of writeable properties is from service to device. Reported property schema is not defined in interface but in document here https://microsoft.sharepoint.com/:w:/r/teams/Azure_IoT/_layouts/15/Doc.aspx?sourcedoc=%7B0ECCE6BC-4692-4C82-926B-51117337E0C8%7D&file=IothubPnP_DevDesign.docx&action=default&mobileredirect=true

Please contact service team for latest document.

**Comment by wickste** [comment] 2019-12-30 17:16
This is not by design. It works for C#, but doesn't work for Java. When you follow the quickstart tutorial for Java you end up with this error on step:
![java_error](https://user-images.githubusercontent.com/19159740/71592373-d30d5d80-2ae4-11ea-8400-92caa1987603.PNG)

**Comment by timtay-microsoft** [comment] 2021-01-26 01:09
Since this issue is tied to the PnP code that was recently deprecated in favor of a new client and new samples, I'm closing this issue

**Closed by timtay-microsoft** 2021-01-26 01:09 UTC
Labels: IoTSDK, bug
