### ISSUE TITLE
[Technical Question] [Device Client] Mqtt connection lost

### ISSUE THREAD

**Issue by johanz9** [Azure/azure-iot-sdk-java#1257] opened 2021-06-26 21:23 UTC
- OS Windows 10
- Java runtime used: JDK 12
- SDK version used: 1.29.4
- Paho version used: 1.2.5

Hi i have a problem with your sdk, I'm trying to receive message from cloud, but i obtained Mqtt connection lost. My code is:

import com.microsoft.azure.sdk.iot.device.*;
import com.microsoft.azure.sdk.iot.device.transport.IotHubConnectionStatus;

import java.io.IOException;
import java.net.URISyntaxException;

public class test {
    private static String connString = "something";

    // Using the MQTT protocol to connect to IoT Hub
    private static IotHubClientProtocol protocol = IotHubClientProtocol.MQTT;
    private static DeviceClient client;

    private static class AppMessageCallback implements MessageCallback {
        public IotHubMessageResult execute(Message msg, Object context) {
            System.out.println("Received message from hub: "
                    + new String(msg.getBytes(), Message.DEFAULT_IOTHUB_MESSAGE_CHARSET));

            return IotHubMessageResult.COMPLETE;
        }
    }

    public static void main(String[] args) throws URISyntaxException, IOException {
        client = new DeviceClient(connString, protocol);

        MessageCallback callback = new AppMessageCallback();
        client.setMessageCallback(callback, null);
        client.registerConnectionStatusChangeCallback(new IotHubConnectionStatusChangeCallback()
        {
            @Override
            public void execute(IotHubConnectionStatus status, IotHubConnectionStatusChangeReason statusChangeReason, Throwable throwable, Object callbackContext) {
                System.out.println();
                System.out.println("CONNECTION STATUS UPDATE: " + status);
                System.out.println("CONNECTION STATUS REASON: " + statusChangeReason);
                System.out.println("CONNECTION STATUS THROWABLE: " + (throwable == null ? "null" : throwable.getMessage()));
                System.out.println();
            }

        }, new Object());

        client.open();

        System.out.println("Press ENTER to exit.");
        System.in.read();
        client.closeNow();
    }
}

but i obtained this error:

23:05:13.082 [MQTT Rec: VehicleTest01] WARN  c.m.a.s.i.device.transport.mqtt.Mqtt - Mqtt connection lost
org.eclipse.paho.client.mqttv3.MqttException: Se ha perdido la conexión
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:197) ~[org.eclipse.paho.client.mqttv3-1.2.5.jar:na]
	at java.base/java.lang.Thread.run(Thread.java:835) ~[na:na]
Caused by: java.io.EOFException: null
	at java.base/java.io.DataInputStream.readByte(DataInputStream.java:272) ~[na:na]
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:92) ~[org.eclipse.paho.client.mqttv3-1.2.5.jar:na]
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:137) ~[org.eclipse.paho.client.mqttv3-1.2.5.jar:na]
	... 1 common frames omitted
23:05:13.094 [azure-iot-sdk-ConnectionReconnectionTask:2e1c21f9-007b-47e5-bbbe-01be312990e3] INFO  c.m.a.s.i.d.t.IotHubTransport - Handling a disconnection event
com.microsoft.azure.sdk.iot.device.exceptions.ProtocolException: Mqtt connection lost
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.exceptions.PahoExceptionTranslator.convertToMqttException(PahoExceptionTranslator.java:74) ~[iot-device-client-1.29.4.jar:na]
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.Mqtt.connectionLost(Mqtt.java:340) ~[iot-device-client-1.29.4.jar:na]
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.connectionLost(CommsCallback.java:304) ~[org.eclipse.paho.client.mqttv3-1.2.5.jar:na]
	at org.eclipse.paho.client.mqttv3.internal.ClientComms.shutdownConnection(ClientComms.java:441) ~[org.eclipse.paho.client.mqttv3-1.2.5.jar:na]
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:197) ~[org.eclipse.paho.client.mqttv3-1.2.5.jar:na]
	at java.base/java.lang.Thread.run(Thread.java:835) ~[na:na]
Caused by: org.eclipse.paho.client.mqttv3.MqttException: Se ha perdido la conexión
	... 2 common frames omitted
Caused by: java.io.EOFException: null
	at java.base/java.io.DataInputStream.readByte(DataInputStream.java:272) ~[na:na]
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:92) ~[org.eclipse.paho.client.mqttv3-1.2.5.jar:na]
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:137) ~[org.eclipse.paho.client.mqttv3-1.2.5.jar:na]
	... 1 common frames omitted
23:05:13.095 [azure-iot-sdk-ConnectionReconnectionTask:2e1c21f9-007b-47e5-bbbe-01be312990e3] DEBUG c.m.a.s.i.d.t.IotHubTransport - Mapping throwable to NO_NETWORK because it was a retryable exception
com.microsoft.azure.sdk.iot.device.exceptions.ProtocolException: Mqtt connection lost
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.exceptions.PahoExceptionTranslator.convertToMqttException(PahoExceptionTranslator.java:74) ~[iot-device-client-1.29.4.jar:na]
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.Mqtt.connectionLost(Mqtt.java:340) ~[iot-device-client-1.29.4.jar:na]
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.connectionLost(CommsCallback.java:304) ~[org.eclipse.paho.client.mqttv3-1.2.5.jar:na]
	at org.eclipse.paho.client.mqttv3.internal.ClientComms.shutdownConnection(ClientComms.java:441) ~[org.eclipse.paho.client.mqttv3-1.2.5.jar:na]
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:197) ~[org.eclipse.paho.client.mqttv3-1.2.5.jar:na]
	at java.base/java.lang.Thread.run(Thread.java:835) ~[na:na]
Caused by: org.eclipse.paho.client.mqttv3.MqttException: Se ha perdido la conexión
	... 2 common frames omitted
Caused by: java.io.EOFException: null
	at java.base/java.io.DataInputStream.readByte(DataInputStream.java:272) ~[na:na]
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:92) ~[org.eclipse.paho.client.mqttv3-1.2.5.jar:na]
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:137) ~[org.eclipse.paho.client.mqttv3-1.2.5.jar:na]
	... 1 common frames omitted
23:05:13.096 [azure-iot-sdk-ConnectionReconnectionTask:2e1c21f9-007b-47e5-bbbe-01be312990e3] WARN  c.m.a.s.i.d.t.IotHubTransport - Updating transport status to new status DISCONNECTED_RETRYING with reason NO_NETWORK
com.microsoft.azure.sdk.iot.device.exceptions.ProtocolException: Mqtt connection lost
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.exceptions.PahoExceptionTranslator.convertToMqttException(PahoExceptionTranslator.java:74) ~[iot-device-client-1.29.4.jar:na]
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.Mqtt.connectionLost(Mqtt.java:340) ~[iot-device-client-1.29.4.jar:na]
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.connectionLost(CommsCallback.java:304) ~[org.eclipse.paho.client.mqttv3-1.2.5.jar:na]
	at org.eclipse.paho.client.mqttv3.internal.ClientComms.shutdownConnection(ClientComms.java:441) ~[org.eclipse.paho.client.mqttv3-1.2.5.jar:na]
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:197) ~[org.eclipse.paho.client.mqttv3-1.2.5.jar:na]
	at java.base/java.lang.Thread.run(Thread.java:835) ~[na:na]
Caused by: org.eclipse.paho.client.mqttv3.MqttException: Se ha perdido la conexión
	... 2 common frames omitted
Caused by: java.io.EOFException: null
	at java.base/java.io.DataInputStream.readByte(DataInputStream.java:272) ~[na:na]
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:92) ~[org.eclipse.paho.client.mqttv3-1.2.5.jar:na]
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:137) ~[org.eclipse.paho.client.mqttv3-1.2.5.jar:na]
	... 1 common frames omitted
23:05:13.097 [azure-iot-sdk-ConnectionReconnectionTask:2e1c21f9-007b-47e5-bbbe-01be312990e3] DEBUG c.m.a.s.i.d.t.IotHubTransport - Invoking connection status callbacks with new status details

CONNECTION STATUS UPDATE: DISCONNECTED_RETRYING
CONNECTION STATUS REASON: NO_NETWORK
CONNECTION STATUS THROWABLE: Mqtt connection lost

**Comment by timtay-microsoft** [comment] 2021-06-28 16:03
Can you share a bit more context around this disconnection event? By default, the SDK will disconnect every ~60 minutes in order to re-authenticate with the service, and that is by design. Otherwise, you may see this error when underlaying network issues interfere with the connection, and are considered typical behavior and that the SDK will handle reconnecting for you.

Are you seeing this error frequently? And if so, how frequently?

**Comment by timtay-microsoft** [comment] 2021-07-01 00:53
@johanz9 do you have any extra context that you can share for this issue?

**Comment by johanz9** [comment] 2021-07-01 05:07
Hi, sorry.  The problem was underlaying network. used two client connected frequenly 😅. Thanks very much

**Comment by timtay-microsoft** [comment] 2021-07-01 16:41
Okay, I'll go ahead and close this issue then

**Closed by timtay-microsoft** 2021-07-01 16:41 UTC
Labels: IoTSDK, customer input needed, question
