### ISSUE TITLE
Azure Java iot sdk never reconnecting back to the iot hub after connection drop.

### ISSUE THREAD

**Issue by AlanTuring1988** [Azure/azure-iot-sdk-java#252] opened 2018-05-29 10:27 UTC
Hi,
I have developed a client that connects to Iot Hub through certificates, using the protocol AMQPS_WS and AMQPS. in case of reconnection, due to a momentary disconnection of the network, I have the same problem reported in #192 . I am using the lib iot-device-client version 1.9.0 and Java8

Best,
Pietro.

INFO [main] (CustomLogger.java:23) - IotHubConnectionString object is created successfully for myiothub.azure-devices.net, method name is 
INFO [main] (CustomLogger.java:23) - DeviceClientConfig object is created successfully with IotHubName=myiot.azure-devices.net, deviceID=mydevice, method name is 
INFO [main] (CustomLogger.java:23) - DeviceIO object is created successfully, method name is 
INFO [main] (CustomLogger.java:23) - DeviceClient object is created successfully, method name is commonConstructorSetup
INFO [main] (CustomLogger.java:23) - Opening the connection..., method name is open
INFO [main] (CustomLogger.java:23) - AmqpsIotHubConnection object is created successfully using port 443 in method
DEBUG [main] (CustomLogger.java:31) - Entered in method open
DEBUG [main] (CustomLogger.java:31) - Entered in method openAsync
INFO [main] (CustomLogger.java:23) - Reactor is assigned to executor service, method name is openAsync
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Entered in method onReactorInit
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Exited from method onReactorInit
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Entered in method onConnectionInit
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Entered in method onConnectionInit
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Entered in method openLinks
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Entered in method openLinks
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Exited from method openLinks
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Entered in method openLinks
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Exited from method openLinks
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Entered in method openLinks
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Exited from method openLinks
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Exited from method openLinks
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Exited from method onConnectionInit
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Exited from method onConnectionInit
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Entered in method onLinkInit
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Entered in method onLinkInit
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Entered in method initLink
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Entered in method initLink
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Exited from method initLink
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Entered in method initLink
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Exited from method initLink
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Entered in method initLink
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Exited from method initLink
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Exited from method initLink
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Exited from method onLinkInit
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Exited from method onLinkInit
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Entered in method onLinkInit
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Entered in method onLinkInit
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Entered in method initLink
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Entered in method initLink
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Exited from method initLink
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Entered in method initLink
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Exited from method initLink
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Entered in method initLink
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Exited from method initLink
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Exited from method initLink
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Exited from method onLinkInit
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Exited from method onLinkInit
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Entered in method onLinkInit
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Entered in method onLinkInit
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Entered in method initLink
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Entered in method initLink
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Exited from method initLink
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Entered in method initLink
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Exited from method initLink
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Entered in method initLink
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Exited from method initLink
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Exited from method initLink
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Exited from method onLinkInit
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Exited from method onLinkInit
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Entered in method onLinkInit
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Entered in method onLinkInit
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Entered in method initLink
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Entered in method initLink
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Exited from method initLink
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Entered in method initLink
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Exited from method initLink
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Entered in method initLink
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Exited from method initLink
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Exited from method initLink
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Exited from method onLinkInit
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Exited from method onLinkInit
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Entered in method onLinkInit
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Entered in method onLinkInit
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Entered in method initLink
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Entered in method initLink
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Exited from method initLink
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Entered in method initLink
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Exited from method initLink
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Entered in method initLink
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Exited from method initLink
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Exited from method initLink
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Exited from method onLinkInit
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Exited from method onLinkInit
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Entered in method onLinkInit
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Entered in method onLinkInit
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Entered in method initLink
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Entered in method initLink
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Exited from method initLink
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Entered in method initLink
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Exited from method initLink
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Entered in method initLink
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Exited from method initLink
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Exited from method initLink
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Exited from method onLinkInit
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Exited from method onLinkInit
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Entered in method onConnectionBound
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Entered in method onConnectionBound
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Exited from method onConnectionBound
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Exited from method onConnectionBound
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Entered in method onTransportError
INFO [pool-1-thread-1] (CustomLogger.java:23) - Starting to reconnect to IotHub, method name is onTransportError
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Entered in method startReconnect
INFO [pool-1-thread-1] (CustomLogger.java:23) - The messages in progress are buffered to be sent again due to a connection loss, method name is connectionLost
DEBUG [pool-1-thread-1] (AzureCloudClient.java:250) - >> registerConnectionStateCallback(CONNECTION_DROP) - Date : 2018-05-29T11:44:31.593+02:00
INFO [pool-1-thread-1] (AzureCloudClient.java:255) - Lost connection to the server. Retry connection in 2 seconds.
INFO [pool-1-thread-1] (CustomLogger.java:23) - Lost connection to the server. Reconnection attempt 1, method name is startReconnect
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Entered in method closeAsync
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Entered in method closeNow
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Entered in method closeLinks
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Entered in method closeLinks
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Exited from method closeLinks
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Entered in method closeLinks
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Exited from method closeLinks
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Entered in method closeLinks
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Exited from method closeLinks
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Exited from method closeLinks
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Entered in method closeLinks
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Exited from method closeLinks
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Exited from method closeNow
INFO [pool-1-thread-1] (CustomLogger.java:23) - Proton reactor has been stopped, method name is closeAsync
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Exited from method closeAsync
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Exited from method onTransportError
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Entered in method onConnectionUnbound
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Exited from method onConnectionUnbound
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Entered in method onReactorFinal
DEBUG [pool-1-thread-1] (CustomLogger.java:31) - Entered in method reconnect
[…]

DEBUG [pool-2-thread-1] (CustomLogger.java:31) - Get the callback function for the received message, method name is handleMessage
DEBUG [pool-2-thread-1] (CustomLogger.java:31) - Get the callback function for the received message, method name is handleMessage
DEBUG [pool-2-thread-2] (CustomLogger.java:31) - Get the callback function for the received message, method name is handleMessage
DEBUG [pool-2-thread-1] (CustomLogger.java:31) - Get the callback function for the received message, method name is handleMessage
DEBUG [pool-2-thread-1] (CustomLogger.java:31) - Get the callback function for the received message, method name is handleMessage
DEBUG [pool-2-thread-1] (CustomLogger.java:31) - Get the callback function for the received message, method name is handleMessage
DEBUG [pool-2-thread-1] (CustomLogger.java:31) - Get the callback function for the received message, method name is handleMessage
DEBUG [pool-2-thread-2] (CustomLogger.java:31) - Get the callback function for the received message, method name is handleMessage
DEBUG [pool-2-thread-1] (CustomLogger.java:31) - Get the callback function for the received message, method name is handleMessage
DEBUG [pool-2-thread-2] (CustomLogger.java:31) - Get the callback function for the received message, method name is handleMessage
DEBUG [pool-2-thread-1] (CustomLogger.java:31) - Get the callback function for the received message, method name is handleMessage
DEBUG [pool-2-thread-2] (CustomLogger.java:31) - Get the callback function for the received message, method name is handleMessage
DEBUG [pool-2-thread-1] (CustomLogger.java:31) - Get the callback function for the received message, method name is handleMessage
DEBUG [pool-2-thread-1] (CustomLogger.java:31) - Get the callback function for the received message, method name is handleMessage
DEBUG [pool-2-thread-2] (CustomLogger.java:31) - Get the callback function for the received message, method name is handleMessage
DEBUG [pool-2-thread-1] (CustomLogger.java:31) - Get the callback function for the received message, method name is handleMessage
DEBUG [pool-2-thread-1] (CustomLogger.java:31) - Get the callback function for the received message, method name is handleMessage
DEBUG [pool-2-thread-1] (CustomLogger.java:31) - Get the callback function for the received message, method name is handleMessage
DEBUG [pool-2-thread-1] (CustomLogger.java:31) - Get the callback function for the received message, method name is handleMessage
DEBUG [pool-2-thread-1] (CustomLogger.java:31) - Get the callback function for the received message, method name is handleMessage
DEBUG [pool-2-thread-2] (CustomLogger.java:31) - Get the callback function for the received message, method name is handleMessage
DEBUG [pool-2-thread-2] (CustomLogger.java:31) - Get the callback function for the received message, method name is handleMessage
DEBUG [pool-2-thread-2] (CustomLogger.java:31) - Get the callback function for the received message, method name is handleMessage
DEBUG [pool-2-thread-1] (CustomLogger.java:31) - Get the callback function for the received message, method name is handleMessage
DEBUG [pool-2-thread-2] (CustomLogger.java:31) - Get the callback function for the received message, method name is handleMessage
DEBUG [pool-2-thread-2] (CustomLogger.java:31) - Get the callback function for the received message, method name is handleMessage
DEBUG [pool-2-thread-2] (CustomLogger.java:31) - Get the callback function for the received message, method name is handleMessage
DEBUG [pool-2-thread-1] (CustomLogger.java:31) - Get the callback function for the received message, method name is handleMessage
DEBUG [pool-2-thread-1] (CustomLogger.java:31) - Get the callback function for the received message, method name is handleMessage
DEBUG [pool-2-thread-1] (CustomLogger.java:31) - Get the callback function for the received message, method name is handleMessage
DEBUG [pool-2-thread-1] (CustomLogger.java:31) - Get the callback function for the received message, method name is handleMessage
DEBUG [pool-2-thread-1] (CustomLogger.java:31) - Get the callback function for the received message, method name is handleMessage
DEBUG [pool-2-thread-2] (CustomLogger.java:31) - Get the callback function for the received message, method name is handleMessage
DEBUG [pool-2-thread-1] (CustomLogger.java:31) - Get the callback function for the received message, method name is handleMessage
DEBUG [pool-2-thread-1] (CustomLogger.java:31) - Get the callback function for the received message, method name is handleMessage
[…]

**Comment by pjanfred** [comment] 2018-05-29 12:33
I have the same issue with version 1.11.1

**Comment by timtay-microsoft** [comment] 2018-06-05 17:33
@AlanTuring1988 or @pjanfred can you please run your scenario again with the above code sample? I still cannot repro this behavior.

**Comment by AlanTuring1988** [comment] 2018-06-07 09:52
Hi,
the problem occurs if you start the connection when the network is disabled and next you enable it. In this case the reconnect does not take place.

**Comment by timtay-microsoft** [comment] 2018-06-07 18:47
Just to clarify, the problem here is that you expect the open operation to retry? 

Currently, the open operation does not have any retry logic beyond what the underlying AMQP library has. This is by design, and we have no immediate plans to add retry logic to the open call. It would be a breaking change to add it right now.

If you would like to have the open operation retry until successful, you can use this code snippet:

```java
public static void openDeviceClientWithRetry(DeviceClient client)
{
    boolean clientOpenSucceeded = false;
    long startTime = System.currentTimeMillis();
    while (!clientOpenSucceeded)
    {
        if (System.currentTimeMillis() - startTime > OPEN_RETRY_TIMEOUT)
        {
            throw new Exception("Device Client open timed out");
        }

        try
        {
            client.open();
            clientOpenSucceeded = true;
        }
        catch (IOException e)
        {
            //ignore and try again
            System.out.println("Encountered exception while opening device client, retrying...");
            e.printStackTrace();
            Thread.sleep(500); //buffer between open attempts 
        }
    }

    System.out.println("Successfully opened connection!");
}
```

**Comment by timtay-microsoft** [comment] 2018-06-12 18:49
@AlanTuring1988 can you please clarify if your problem has been resolved with the above code snippet?

@pjanfred can you please try to run the code sample I provided and give me the logs so that I can fix this issue for you?

**Comment by milunko** [comment] 2018-06-14 11:55
Hi, we are experiencing the exact same issue as described in the first post of this thread. (and as far as I see your code snipplet handles another issue altogether).

I added the callback that logs the connection state and what the logs showed:

2018-06-01 11:44:01,042 WARN c.z.i.p.a.AzureIotHubCommunicationBlock [main] Connection state changed to CONNECTION_SUCCESS
...... everything works fine for couple of days......
2018-06-08 16:35:18,570 WARN c.z.i.p.a.AzureIotHubCommunicationBlock [pool-27-thread-1] Connection state changed to CONNECTION_SUCCESS
...... everything works fine......
2018-06-08 23:38:59,148 WARN c.z.i.p.a.AzureIotHubCommunicationBlock [pool-29-thread-1] Connection state changed to CONNECTION_DROP
...... connection never gets reestablished, and whenever we try sending anything to IOT hub we get error as seen:    ..................
2018-06-08 23:44:53,269 ERROR c.z.i.p.a.AzureIotHubBlock [pool-5-thread-1] Error sending message to IoT Hub
java.lang.IllegalStateException: Cannot add a message when the transport is closed.
	at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.addMessage(IotHubTransport.java:335) ~
	at com.microsoft.azure.sdk.iot.device.DeviceIO.sendEventAsync(DeviceIO.java:299) ~
	at com.microsoft.azure.sdk.iot.device.DeviceClient.sendEventAsync(DeviceClient.java:477) ~
	....

**Comment by timtay-microsoft** [comment] 2018-06-14 19:23
What's likely happening is that your connection is interrupted and the SDK is wrongly classifying that exception as non-retryable, so it doesn't bother reconnecting. It is very important that you figure out what that exception you are encountering is, and the connectionStatusChange callback should surface it for you.

**Comment by timtay-microsoft** [comment] 2018-07-13 21:02
A lot of discussion around this bug came over email, so to catch this thread up:
The issue was that the retry policy would eventually stop retrying if it lost internet connectivity for longer than the device operation timeout (default of 4 minutes).

The only ways to avoid this problem are to set a longer device operation timeout, provide a different retry algorithm than the default exponential backoff, or to upgrade your network connectivity to avoid long periods where your device cannot reach the router.

Since this issue was not due to any bug in the SDK, I'm going to go ahead and close this issue. Feel free to re-open if you are still running into this issue even after providing more leeway to your retry policy.

**Closed by timtay-microsoft** 2018-07-13 21:02 UTC
Labels: investigation-required
