### ISSUE TITLE
"java.net.SocketException: Permission denied: connect"  while using com.microsoft.azure.iot.service.sdk.RegistryManager.addDevice

### ISSUE THREAD

**Issue by nagamanojv** [Azure/azure-iot-sdk-java#72] opened 2017-03-30 04:19 UTC
- **OS and version used:** Microsoft Windows [Version 6.2.9200] 

- **Java runtime used:** Java 8 1.8.0_111 

- **SDK version used:** iothub-java-service-client - 1.0.10 

# Description of the issue:

When trying to register add device to IoTHub using RegistryManager.addDevice() method it fails with the exception java.net.SocketException: Permission denied: connect . My application is deployed as an azure app service. When the application starts, for some time this method call is working successfully creating new devices. But after some time (approx after 6 - 7 hours) it starts failing with the above exception. Some times even after the first failure, it works for some time intermittently but after a while it fails forever. 

# Code sample exhibiting the issue:

RegistryManager registryManager;
...
registryManager = RegistryManager
        .createFromConnectionString(PropertyManager.getInstance().getProperty("iot.hub.conn"));
...
 public Device register(String deviceId)
      throws JsonSyntaxException, IOException, IllegalArgumentException, NoSuchAlgorithmException {

    Device device = Device.createFromId(deviceId, null, null);
    try {
      device = registryManager.addDevice(device);
      logger.info(
          String.format("Device %s registered successfully with key %s", device.getDeviceId(), device.getPrimaryKey()));
    } catch (IotHubException iote) {
      try {
        device = registryManager.getDevice(deviceId);
      } catch (IotHubException iotf) {
        logger.error("Error while registering device", iotf);
      }
    }
    return device;
  }

In the above piece of code, the error occurs from the line "device = registryManager.addDevice(device);"

# Console log of the issue:

Error while registering device
java.net.SocketException: Permission denied: connect
	at java.net.TwoStacksPlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_102]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_102]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_102]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_102]
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172) ~[na:1.8.0_102]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_102]
	at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_102]
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668) ~[na:1.8.0_102]
	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173) ~[na:1.8.0_102]
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180) ~[na:1.8.0_102]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432) ~[na:1.8.0_102]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527) ~[na:1.8.0_102]
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264) ~[na:1.8.0_102]
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367) ~[na:1.8.0_102]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191) ~[na:1.8.0_102]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105) ~[na:1.8.0_102]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999) ~[na:1.8.0_102]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177) ~[na:1.8.0_102]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1513) ~[na:1.8.0_102]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441) ~[na:1.8.0_102]
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480) ~[na:1.8.0_102]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338) ~[na:1.8.0_102]
	at com.microsoft.azure.iot.service.transport.http.HttpConnection.getResponseStatus(HttpConnection.java:236) ~[iothub-java-service-client-1.0.10.jar:na]
	at com.microsoft.azure.iot.service.transport.http.HttpRequest.send(HttpRequest.java:76) ~[iothub-java-service-client-1.0.10.jar:na]
	at com.microsoft.azure.iot.service.sdk.RegistryManager.addDevice(RegistryManager.java:108) ~[iothub-java-service-client-1.0.10.jar:na]
	at com.moveinsync.iot.services.IOTDeviceManagementService.register(IOTDeviceManagementService.java:33) ~[classes/:na]
	at com.moveinsync.iot.services.IOTDeviceManagementService.getConnectionString(IOTDeviceManagementService.java:59) ~[classes/:na]
	at com.moveinsync.iot.controller.DeviceController.getConnectionString(DeviceController.java:51) [classes/:na]
	at sun.reflect.GeneratedMethodAccessor68.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_102]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_102]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:222) [spring-web-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137) [spring-web-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110) [spring-webmvc-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:814) [spring-webmvc-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:737) [spring-webmvc-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85) [spring-webmvc-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959) [spring-webmvc-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893) [spring-webmvc-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:969) [spring-webmvc-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:860) [spring-webmvc-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:622) [servlet-api.jar:na]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:845) [spring-webmvc-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729) [servlet-api.jar:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230) [catalina.jar:8.5.6]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) [catalina.jar:8.5.6]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-websocket.jar:8.5.6]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) [catalina.jar:8.5.6]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) [catalina.jar:8.5.6]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198) [catalina.jar:8.5.6]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:108) [catalina.jar:8.5.6]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472) [catalina.jar:8.5.6]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) [catalina.jar:8.5.6]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [catalina.jar:8.5.6]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620) [catalina.jar:8.5.6]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [catalina.jar:8.5.6]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349) [catalina.jar:8.5.6]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:784) [tomcat-coyote.jar:8.5.6]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-coyote.jar:8.5.6]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:802) [tomcat-coyote.jar:8.5.6]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1410) [tomcat-coyote.jar:8.5.6]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:8.5.6]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_102]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_102]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.5.6]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_102]

**Comment by prmathur-microsoft** [comment] 2017-04-03 18:12
Thank you reporting this. We will look into this.

**Comment by prmathur-microsoft** [comment] 2017-04-15 02:16
Can you confirm your network connectivity is in place when this exception occurs ?

**Comment by nagamanojv** [comment] 2017-04-15 05:23
My application is deployed on Azure App service, so I am guessing the network connectivity was available when the exception occurred. 

By the way, when I am using the SDK  [iot-service-client](https://mvnrepository.com/artifact/com.microsoft.azure.sdk.iot/iot-service-client) this exception is not coming.

**Comment by markrad** [comment] 2017-04-19 21:39
Hi @nagamanojv,

Do you know if this only reproduces when you run it as an Azure App Service? I've tried it on the desktop and I'm yet to see the same issue. 

_Mark Radbourne MSFT_

**Comment by prmathur-microsoft** [comment] 2017-04-25 00:06
@nagamanojv - Can you please provide more details to help us reproduce this issue ?

**Comment by markrad** [comment] 2017-04-25 21:59
Hi @nagamanojv,

This issue will be closed as no repro if I don't hear from you this week.

Thank you.

**Comment by markrad** [comment] 2017-05-02 21:04
I'm closing this due to a lack of response. You are welcome to reopen this issue if you can provide the information requested.

**Closed by markrad** 2017-05-02 21:04 UTC
Labels: CSS, help wanted
