### ISSUE TITLE
[Device SDK / MQTT] DeviceClient closeNow not stopping threads

### ISSUE THREAD

**Issue by hochas** [Azure/azure-iot-sdk-java#453] opened 2019-02-27 09:24 UTC
- **OS and version used:** Ubuntu 18.04.2 LTS

- **Java runtime used:**
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment (build 11.0.1+13-Ubuntu-3ubuntu118.04ppa1)
OpenJDK 64-Bit Server VM (build 11.0.1+13-Ubuntu-3ubuntu118.04ppa1, mixed mode, sharing)

- **SDK version used:**
1.15.0

# Description of the issue:
Calling closeNow() leaves threads open. On startup, when connecting and calling `open`for the first time:
``` 
Thread [MQTT Call: leafdevice] (Running)	
Thread [MQTT Rec: leafdevice] (Running)	
Thread [MQTT Snd: leafdevice] (Running)	
Thread [MQTT Disc: leafdevice] (Running)	
Thread [MQTT Snd: leafdevice] (Running)	
Thread [MQTT Rec: leafdevice] (Running)	
Thread [MQTT Call: leafdevice] (Running)	
Thread [MQTT Ping: leafdevice] (Running)	
``` 
This result also seems weird, why are there duplicate `Call`, `Rec` and `Snd` threads? We are using a modified version of [this sample](https://github.com/Azure/azure-iot-sdk-java/blob/692654a8d2528b11e2f19b52f726957d7c74f6cb/provisioning/provisioning-samples/provisioning-X509-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/ProvisioningX509Sample.java) to connect devices. **We are only calling `open` once from our application code**.

I leave the application running, but I call `client.closeNow();`and reconnect the device.
The stack now looks like this:

```
Thread [MQTT Call: leafdevice] (Running)	
Thread [MQTT Rec: leafdevice] (Running)	
Thread [MQTT Snd: leafdevice] (Running)	
Thread [MQTT Disc: leafdevice] (Running)
Thread [MQTT Snd: leafdevice] (Running)	
Thread [MQTT Rec: leafdevice] (Running)	
Thread [MQTT Call: leafdevice] (Running)	
Thread [MQTT Disc: leafdevice] (Running)
Thread [MQTT Snd: leafdevice] (Running)	
Thread [MQTT Rec: leafdevice] (Running)	
Thread [MQTT Call: leafdevice] (Running)	
Thread [MQTT Ping: leafdevice] (Running)
```

Notice that there is one new instance of `Call`, `Rec` and `Snd` each, as well as a duplicate of `Disc`. Still only a single `Ping` thread.

# Code sample exhibiting the issue:

#141  discusses the same issue. It seems [the related Paho issue has been resolved](https://github.com/eclipse/paho.mqtt.java/issues/402), but there have been no new releases of the SDK since this fix.

**Comment by hochas** [comment] 2019-02-27 13:21
I rebuilt `iot-device-client` locally with updated paho dependenct:

```
<dependency>
	<groupId>org.eclipse.paho</groupId>
	<artifactId>org.eclipse.paho.client.mqttv3</artifactId>
	<version>1.2.1</version>
</dependency>
```

It now only creates 4 threads upon first calling `open`, calling `closeNow` and then `open` again and there is till 4 threads.

Would you like me to issue a pull request?

**Comment by timtay-microsoft** [comment] 2019-02-27 18:36
I can create the PR for this. I'm glad to see Paho has fixed this issue as it has been around for a while. Thanks for bringing it to our attention.

**Comment by hochas** [comment] 2019-02-28 06:37
No problem, glad to help!

**Comment by timtay-microsoft** [comment] 2019-03-21 20:31
Just to update this issue, we have attempted to upgrade our paho dependency to resolve this threading issue, but we are encountering regressions. We are still investigating the cause of these, and we'll try to keep this thread updated with our findings.

**Comment by timtay-microsoft** [comment] 2019-06-17 21:24
Sorry for the intermittent updates, but to keep this thread up to date, Paho version 1.2.1 did introduce a regression on MQTT_WS connections, so until that issue is resolved, we cannot upgrade to fix this thread leak. I have opened an issue on Paho's issues page about this regression [here](https://github.com/eclipse/paho.mqtt.java/issues/679).

**Comment by hochas** [comment] 2019-06-18 06:03
No worries, we've worked around it the meantime. I understand it's out of your control.

**Comment by timtay-microsoft** [comment] 2019-08-22 19:38
A member of the MQTT Paho team is actively looking into the bug in Paho 1.2.1 that was preventing us from upgrading our dependency. We plan on updating and releasing our SDK as soon as that new Paho version becomes available. That new version of Paho should resolve this issue.

**Comment by kartben** [comment] 2019-09-18 08:46
Just an update on this, the 1.2.2 release of Paho is imminent as per https://github.com/eclipse/paho.mqtt.java/issues/679#issuecomment-531194567

**Comment by timtay-microsoft** [comment] 2019-09-24 20:24
We are working to upgrade our Paho dependency now that they have released version 1.2.2. Thankfully, it appears that this leaked thread bug is not present in 1.2.2 so once we upgrade our dependency, I will do a release of this SDK and close this issue.

**Comment by timtay-microsoft** [comment] 2019-09-30 22:51
As of [this release](https://github.com/Azure/azure-iot-sdk-java/releases/tag/2019-09-30_2), the device client and deps will now use Paho version 1.2.2. This newest version of Paho fixed this issue, so I'm closing this issue.

**Comment by az-iot-builder-01** [comment] 2019-09-30 22:51
@hochas, @kartben, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Closed** 2019-09-30 22:51 UTC
Labels: Underlying Library Issue, fix checked in
