### ISSUE TITLE
Replace log4j by its successor logback

### ISSUE THREAD

**Issue by JMayrbaeurl** [Azure/azure-iot-sdk-java#51] opened 2017-03-15 13:08 UTC
- **OS and version used:** Windows 10 

- **Java runtime used:** 1.8 

- **SDK version used:** 1.0.21 

# Description of the issue:
Please consider replacing the logging library log4j with its successor logback (see https://logback.qos.ch/ ). Logback brings a very large number of improvements over log4j, big and small. For more details see https://logback.qos.ch/reasonsToSwitch.html 

# Code sample exhibiting the issue:

# Console log of the issue:

**Comment by prmathur-microsoft** [comment] 2017-03-16 00:40
We will investigate all the options for logging and use a better method for logging.

**Comment by jasmineymlo** [comment] 2018-05-03 17:58
duplicate of #50.

**Closed by jasmineymlo** 2018-05-03 17:58 UTC
Labels: enhancement
