### ISSUE TITLE
[Bug Report] DeviceClient.open() using AMQPS might throw NullPointerException. 

### ISSUE THREAD

**Issue by EinarBergseth** [Azure/azure-iot-sdk-java#900] opened 2020-08-21 14:24 UTC
# Context

- **OS and version used:** Linux version 4.4.187 (build@a78bfeb6277f) (gcc version 7.4.0 (Buildroot 2019.02.2-svn3578) )
- **Java runtime used:** Java(TM) SE Embedded Runtime Environment (build 1.8.0_251-b08, profile compact2, headless)
- **SDK version used:** iot-device-client 1.25.0

## Description of the issue
DeviceClient.open() using AMQPS might throw NullPointerException (if authenticationSessionOpen Timed Out). In this case the function com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection.closeAsync() is called where the variable this.connection might be null. See the provided stack trace below.

I don't know how to reproduce this error. 

## Console log of the issue
java.lang.NullPointerException
        at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection.closeAsync(AmqpsIotHubConnection.java:712)
        at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection.close(AmqpsIotHubConnection.java:175)
        at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection.closeConnectionWithException(AmqpsIotHubConnection.java:690)
        at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection.open(AmqpsIotHubConnection.java:143)
        at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.openConnection(IotHubTransport.java:785)
        at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.open(IotHubTransport.java:325)
        at com.microsoft.azure.sdk.iot.device.DeviceIO.open(DeviceIO.java:156)
        at com.microsoft.azure.sdk.iot.device.InternalClient.open(InternalClient.java:146)
        at com.microsoft.azure.sdk.iot.device.DeviceClient.open(DeviceClient.java:395)
        at e2u.gateway.commandservice.CommandServiceConnectionImpl.open(CommandServiceConnectionImpl.java:40)
        at e2u.gateway.commandservice.CommandServiceImpl.openConnection(CommandServiceImpl.java:68)
        at e2u.gateway.commandservice.CommandServiceImpl.open(CommandServiceImpl.java:50)
        at e2u.gateway.commandservice.CommandAndControlModule.lambda$startIotHubConnectTask$0(CommandAndControlModule.java:140)
        at e2u.gateway.common.system.E2UExecutor.lambda$scheduleWithFixedDelay$4(E2UExecutor.java:147)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

AB#8057737

**Comment by emilm** [comment] 2020-09-10 07:56
I suppose it also fixes this one?

2020-09-10T01:19:29,503Z [azure-iot-sdk-ReactorRunner] WARN  c.m.a.s.i.d.transport.IotHubTransport - Updating transport status to new status DISCONNECTED_RETRYING with reason COMMUNICATION_ERROR
com.microsoft.azure.sdk.iot.device.exceptions.TransportException: org.apache.qpid.proton.engine.HandlerException: java.lang.NullPointerException
        at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection$ReactorRunner.call(AmqpsIotHubConnection.java:781)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.apache.qpid.proton.engine.HandlerException: java.lang.NullPointerException
        at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:112)
        at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)
        at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291)
        at com.microsoft.azure.sdk.iot.device.transport.amqps.IotHubReactor.run(IotHubReactor.java:25)
        at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection$ReactorRunner.call(AmqpsIotHubConnection.java:777)
        ... 4 common frames omitted
Caused by: java.lang.NullPointerException: null
        at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsExceptionTranslator.convertFromAmqpException(AmqpsExceptionTranslator.java:17)
        at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection.onMessageAcknowledged(AmqpsIotHubConnection.java:482)
        at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsSessionHandler.onMessageAcknowledged(AmqpsSessionHandler.java:235)
        at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsSenderLinkHandler.onDelivery(AmqpsSenderLinkHandler.java:84)
        at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:185)
        at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
        ... 8 common frames omitted

**Comment by timtay-microsoft** [comment] 2020-09-15 18:09
That looks like a different stacktrace. I'll add some null checks in that function to prevent it in the future

**Comment by timtay-microsoft** [comment] 2020-10-02 15:37
These issues have been fixed as of device client version 1.26.0, so I'm closing this issue

**Comment by az-iot-builder-01** [comment] 2020-10-02 15:37
@EinarBergseth, @timtay-microsoft, @emilm, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Closed** 2020-10-02 15:37 UTC
Labels: IoTSDK, bug, fix checked in
