### ISSUE TITLE
[Bug Report] MQTT C2D message throws ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by gary-newbolt** [Azure/azure-iot-sdk-java#1722] opened 2023-06-09 08:20 UTC
# Context

- **OS and version used:** Windows 11
- **Java runtime used:** 1.8
- **SDK version used:** 2.2.0

## Description of the issue
When sending a C2D message, using the MQTT protocol, I'm recieving a an `ArrayIndexOutOfBoundsException` when a message is received. I believe this is being triggered by a property encoded into the MQTT topic name, however, since I believe this is something created by the IoTHub we're connecting to, it is unclear as to what that property is; this assumption is based on reading the documentation (here: https://learn.microsoft.com/en-us/azure/iot/iot-mqtt-connect-to-iot-hub#receiving-cloud-to-device-messages), and an entry in what the docs calls, the `{property-bag}` element of the url used for the topic name. 

I suspect that there is a property in the topic name that is of the format `key=`, which based on the documentation in the link above, should be acceptable, however, as there is no logging of the topic name, I cannot verify this is the cause, and there seems to be nothing unconfigured in our IoTHub config on Azure that would be responsible. The theory as to this being the cause is based on the surrounding code in the SDK that is causing the exception and in the code block below. You will see that the code does not seem to support the format in the topic name of `key=`, in contradiction to what is advised in the documentation link above. 

I am able to replicate this on one of our IoTHubs, however, on a test IoTHub, this does not occur, so I can confidently say this is related to the specific IoTHub. Furthermore, using AMQP, this issue is not present. However, to the best of my understanding, the documentation and the code seem to be at odds, and the naming of the topic is also abstracted away from IoTHub users as far as I know. 

Kind regards and thanks for the assistance!

## Code sample exhibiting the issue
The line of code in the SDK can be found here: https://github.com/Azure/azure-iot-sdk-java/blob/62eca480aaf0e0c7a653ba68f940a0ce902d9ba0/iothub/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/mqtt/Mqtt.java#L476

Tracing the code backwards I see this attempt to split the properties is related to the inbound message topic name. The static var is set to 1, attempting to access a second array element, and in a property where `key=` would exist, this will always throw the below exception. 

## Console log of the issue
```
MqttException (0) - java.lang.ArrayIndexOutOfBoundsException: 1
        at org.eclipse.paho.client.mqttv3.internal.CommsCallback.run(CommsCallback.java:228)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
        at com.microsoft.azure.sdk.iot.device.transport.mqtt.Mqtt.assignPropertiesToMessage(Mqtt.java:476)
        at com.microsoft.azure.sdk.iot.device.transport.mqtt.Mqtt.constructMessage(Mqtt.java:442)
        at com.microsoft.azure.sdk.iot.device.transport.mqtt.Mqtt.receive(Mqtt.java:306)
        at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttIotHubConnection.onMessageArrived(MqttIotHubConnection.java:458)
        at com.microsoft.azure.sdk.iot.device.transport.mqtt.Mqtt.messageArrived(Mqtt.java:364)
        at org.eclipse.paho.client.mqttv3.internal.CommsCallback.deliverMessage(CommsCallback.java:519)
        at org.eclipse.paho.client.mqttv3.internal.CommsCallback.handleMessage(CommsCallback.java:417)
        at org.eclipse.paho.client.mqttv3.internal.CommsCallback.run(CommsCallback.java:214)
        ... 1 more
```

**Comment by timtay-microsoft** [comment] 2023-06-09 17:38
Hi Gary

The service team is making some changes on hubs that may be the cause of this. Do you happen to have any repro code that demonstrates this behavior? The service client side that sends the c2d message in particular would be helpful here as the issue may be tied to a particular property set on that c2d message

**Comment by gary-newbolt** [comment] 2023-06-14 10:50
Hi Tim, 

Thanks, I can't send you our production code atm and I don't have an app to demo it at the moment, I don't have a lot of time atm but can build one for you later if necessary.  In the meantime I have cloned SDK 2.2.0 and added some logging in to display the topic name which showed me this: 
```
%24.cid=&%24.mid=4c1c6f74-6fbe-44f1-a49e-a5915a7dc1e4&%24.to=%2Fdevices%2Fd2361%2Fmessages%2Fdevicebound&iothub-ack=full
```
highlighting that our message lacked a correlation Id, (`%24.cid=` decoded as: `$.cid=`). When I reviewed our client code that produces the message, I did find that we aren't adding a correlation ID,  only a message ID. So the lack of correlation ID is a result of our client. It also uses the AMQP protocol to send the message to the IoTHub. I am taking measures on our code to ensure future messages have one. 

That being said, it raises a few questions: 

1. The documentation at https://learn.microsoft.com/en-us/azure/iot/iot-mqtt-connect-to-iot-hub#receiving-cloud-to-device-messages does give the impression that any property can be of the form `key=`, and even when excluding the value, should be accepted, however the code in the SDK implies this is not the case for any property, should the documentation be changed? 
2. If, under MQTT, the processing of the message is dependent on there being a Correlation ID, should the IoTHub accept messages to send to devices without one?
3. The SDK code does imply that if there was no key of `$.cid` on the topic name, then the message would be accepted (In my previous message this, is how a message produced using the VSCode plugin was able to be be accepted on my test IoTHub), is this the correct behaviour or should this be changed?
4. Using the AMQP protocal, messages can be received even if there is no correlation ID, should this behaviour be consistent across both protocols? 

Please let me know if you would still like the demo app given the further investigation findings.

**Comment by timtay-microsoft** [comment] 2023-06-14 21:36
> 1) The documentation at https://learn.microsoft.com/en-us/azure/iot/iot-mqtt-connect-to-iot-hub#receiving-cloud-to-device-messages does give the impression that any property can be of the form key=, and even when excluding the value, should be accepted, however the code in the SDK implies this is not the case for any property, should the documentation be changed?

The service team has confirmed for me that the expected behavior from the service is to never send a key-value pair without a value. So what you are encountering is a service bug and they are working to fix it.

They have also confirmed that adding a correlation Id to the message you sent with your service client will prevent this error as well, so that can be your workaround for now.

I'll work on the documentation here to clear up this misconception.

> 2) If, under MQTT, the processing of the message is dependent on there being a Correlation ID, should the IoTHub accept messages to send to devices without one?

IoT hub never requires a correlation Id on a message regardless of protocol or operation. It exists solely for the benefit of users who wish to track their messages through IoT hub. Because of that, you should expect IoT hub to accept/forward messages without correlation Id without issue.

> 3) The SDK code does imply that if there was no key of $.cid on the topic name, then the message would be accepted (In my previous message this, is how a message produced using the VSCode plugin was able to be be accepted on my test IoTHub), is this the correct behaviour or should this be changed?

This is the correct behavior. As mentioned above, setting a correlation Id on any particular message is optional. The SDK will handle the case when a correlation Id isn't present, and it will handle the case when it isn't present (other than this service bug case).

> 4) Using the AMQP protocal, messages can be received even if there is no correlation ID, should this behaviour be consistent across both protocols?

It should be consistent across protocols. Correlation Id is optional regardless of protocol. Once the service-side bug is fixed, then you will see consistent behavior here. Alternatively, you can set correlation Ids on your messages, and the behavior will be consistent across protocols immediately.

**Comment by timtay-microsoft** [comment] 2023-06-14 21:43
> Please let me know if you would still like the demo app given the further investigation findings.

I think we are fine without it at this point. The service team is aware of this bug, so we don't need any help repro'ing it  right now

**Comment by timtay-microsoft** [comment] 2023-06-16 21:25
Given that this is a service-side bug and not an SDK bug, I'm inclined to close this thread. Any objections @gary-newbolt ?

**Comment by gary-newbolt** [comment] 2023-06-19 07:23
Thanks for the answers and the action taken @timtay-microsoft, given the action taken I've no objects to closing this. Thanks again.

**Comment by timtay-microsoft** [comment] 2023-06-19 17:50
Gotcha. I'll close this thread then.

**Closed by timtay-microsoft** 2023-06-19 17:50 UTC
Labels: bug, IoTSDK
