### ISSUE TITLE
PROVISIONING FAILED : b.e.b.b.a.c.a.f.d.b: Service error: null - null - TrackingId: null* - Proguard Protocol Used: AMQPS

### ISSUE THREAD

**Issue by nishanthvasu** [Azure/azure-iot-sdk-java#1236] opened 2021-06-09 07:54 UTC
@timtay-microsoft Hi , I am receiving this issue again. I tried with the your proguard rules as well. Can u help me out in this?                     
**Error: PROVISIONING FAILED : b.e.b.b.a.c.a.f.d.b: Service error: null - null - TrackingId: null**

**ProGuard Rules:** 

```
# Add project specific ProGuard rules here.
# By default, the flags in this file are appended to flags specified
# in C:\Users\v-askhur.REDMOND\AppData\Local\Android\Sdk/tools/proguard/proguard-android.txt
# You can edit the include path and order by changing the proguardFiles
# directive in build.gradle.
#
# For more details, see
#   http://developer.android.com/guide/developing/tools/proguard.html

# Add any project specific keep options here:

# If your project uses WebView with JS, uncomment the following
# and specify the fully qualified class name to the JavaScript interface
# class:
#-keepclassmembers class fqcn.of.javascript.interface.for.webview {
#   public *;
#}

# JSON parser classes don't mix well with minification because JSON parser classes use reflection
# based on the name of the field to create the JSON, and minification changes those names. As a result
# all the message payload serializing and deserializing breaks. These lines explicitly exclude
# the packages where we keep our JSON parsing classes from minification to avoid this issue
-keep class com.microsoft.azure.sdk.iot.provisioning.device.internal.parser.* { *; }
-keep class com.microsoft.azure.sdk.iot.deps.serializer.* { *; }
-keep class com.microsoft.azure.sdk.iot.provisioning.service.configs.* { *; }
-keep class com.microsoft.azure.sdk.iot.deps.twin.* { *; }
-keep class com.microsoft.azure.sdk.iot.service.ImportMode { *; }
-keep class com.microsoft.azure.sdk.iot.service.AuthenticationMechanism { *; }
-keep class com.microsoft.azure.sdk.iot.device.edge.MethodRequest { *; }
-keep class com.microsoft.azure.sdk.iot.device.hsm.parser.ErrorResponse { *; }
-keep class com.microsoft.azure.sdk.iot.device.hsm.parser.SignRequest { *; }

# These are the recommended exclusions when using the IoT Hub service client SDK. They are commented
# out because this sample only uses the IoT Hub device client SDK
#-keep class com.microsoft.azure.sdk.iot.service.ImportMode { *; }
#-keep class com.microsoft.azure.sdk.iot.service.AuthenticationMechanism { *; }

# These are the recommended exclusions when using the Device Provisioning Service device client SDK.
# They are commented out because this sample only uses the IoT Hub device client SDK
#-keep class com.microsoft.azure.sdk.iot.provisioning.device.internal.parser.* { *; }

# These are the recommended exclusions when using the Device Provisioning Service service client SDK.
# They are commented out because this sample only uses the IoT Hub device client SDK
#-keep class com.microsoft.azure.sdk.iot.provisioning.service.configs.* { *; }
```

**Gradle:**

 buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

**Dependencies:** 

//Azure provisioning device client
    // https://mvnrepository.com/artifact/com.microsoft.azure.sdk.iot.provisioning/provisioning-device-client
    implementation group: 'com.microsoft.azure.sdk.iot.provisioning', name: 'provisioning-device-client', version: '1.7.1'

    // https://mvnrepository.com/artifact/com.microsoft.azure.sdk.iot.provisioning.security/x509-provider
    implementation group: 'com.microsoft.azure.sdk.iot.provisioning.security', name: 'x509-provider', version: '1.1.3'

    // Azure IOT device client
    // https://mvnrepository.com/artifact/com.microsoft.azure.sdk.iot/iot-device-client
    implementation (group: 'com.microsoft.azure.sdk.iot', name: 'iot-device-client', version: '1.19.0') {
        exclude module: 'azure-storage'
    }
    implementation ('com.microsoft.azure.android:azure-storage-android:2.0.0@aar')

    // https://mvnrepository.com/artifact/com.microsoft.azure.sdk.iot/iot-deps
    implementation group: 'com.microsoft.azure.sdk.iot', name: 'iot-deps', version: '0.8.5'

    //Currently this is added as a module dependency due to a bug in the lib. This bug is fixed in the module dependency code
    //In future if the bug gets fixed in the lib, we can remove the module and add the gradle dependency
    //Azure IOT service client
    // https://mvnrepository.com/artifact/com.microsoft.azure.sdk.iot/iot-service-client
    //implementation group: 'com.microsoft.azure.sdk.iot', name: 'iot-service-client', version: '1.17.1'

    implementation 'org.apache.commons:commons-lang3:3.6'
    implementation group: 'com.google.guava', name: 'guava', version: '24.1-jre'
    implementation 'com.google.code.gson:gson:2.8.5'

def appCenterSdkVersion = '3.0.0'
    implementation "com.microsoft.appcenter:appcenter-analytics:${appCenterSdkVersion}"
    implementation "com.microsoft.appcenter:appcenter-crashes:${appCenterSdkVersion}"

**Comment by barustum** [comment] 2021-06-22 21:34
Hi @nishanthvasu 

I am looking at this issue, but I am unable to reproduce the problem you are seeing. I wrote a provisioning sample with the same dependencies you are using, but I was able to provision just fine. 

Can you please attach a stack trace and possibility some sample code where this is happening for you?

Thanks

**Comment by barustum** [comment] 2021-06-22 21:37
Also, if possible can we take a look at your build.gradle file or your android project?

**Comment by nishanthvasu** [comment] 2021-06-23 05:39
Hi @barustum ,

Please find the stack trace below and also attaching class file, gradle file and proguard rules file as well. In class file, You can change idscope and global end point as yours and check it.

[TOGIT.zip](https://github.com/Azure/azure-iot-sdk-java/files/6699202/TOGIT.zip)


**2021-06-23 11:02:37.642 4448-4982/com.iothub.azure.microsoft.com.androidsample W/m.androidsampl: Accessing hidden field Lsun/misc/Unsafe;->theUnsafe:Lsun/misc/Unsafe; (greylist, reflection, allowed)
2021-06-23 11:02:37.643 4448-4982/com.iothub.azure.microsoft.com.androidsample W/m.androidsampl: Accessing hidden method Lsun/misc/Unsafe;->allocateInstance(Ljava/lang/Class;)Ljava/lang/Object; (greylist, reflection, allowed)
2021-06-23 11:02:46.007 4448-4448/com.iothub.azure.microsoft.com.androidsample W/System.err: java.util.concurrent.ExecutionException: b.b.a.b.a.c.a.f.d.b: Service error: null - null - TrackingId: null
2021-06-23 11:02:46.007 4448-4448/com.iothub.azure.microsoft.com.androidsample W/System.err:     at java.util.concurrent.FutureTask.report(FutureTask.java:123)
2021-06-23 11:02:46.007 4448-4448/com.iothub.azure.microsoft.com.androidsample W/System.err:     at java.util.concurrent.FutureTask.get(FutureTask.java:207)
2021-06-23 11:02:46.007 4448-4448/com.iothub.azure.microsoft.com.androidsample W/System.err:     at b.b.a.b.a.c.a.f.f.d.b(:113)
2021-06-23 11:02:46.007 4448-4448/com.iothub.azure.microsoft.com.androidsample W/System.err:     at b.b.a.b.a.c.a.f.f.d.call(:287)
2021-06-23 11:02:46.007 4448-4448/com.iothub.azure.microsoft.com.androidsample W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2021-06-23 11:02:46.008 4448-4448/com.iothub.azure.microsoft.com.androidsample W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2021-06-23 11:02:46.008 4448-4448/com.iothub.azure.microsoft.com.androidsample W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2021-06-23 11:02:46.008 4448-4448/com.iothub.azure.microsoft.com.androidsample W/System.err:     at java.lang.Thread.run(Thread.java:919)
2021-06-23 11:02:46.008 4448-4448/com.iothub.azure.microsoft.com.androidsample W/System.err: Caused by: b.b.a.b.a.c.a.f.d.b: Service error: null - null - TrackingId: null
2021-06-23 11:02:46.008 4448-4448/com.iothub.azure.microsoft.com.androidsample W/System.err:     at b.b.a.b.a.c.a.f.f.e.d(:130)
2021-06-23 11:02:46.008 4448-4448/com.iothub.azure.microsoft.com.androidsample W/System.err:     at b.b.a.b.a.c.a.f.f.e.a(:290)
2021-06-23 11:02:46.008 4448-4448/com.iothub.azure.microsoft.com.androidsample W/System.err:     at b.b.a.b.a.c.a.f.f.e.e(:331)
2021-06-23 11:02:46.008 4448-4448/com.iothub.azure.microsoft.com.androidsample W/System.err:     at b.b.a.b.a.c.a.f.f.e.call(:35)
2021-06-23 11:02:46.008 4448-4448/com.iothub.azure.microsoft.com.androidsample W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2021-06-23 11:02:46.008 4448-4448/com.iothub.azure.microsoft.com.androidsample W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
2021-06-23 11:02:46.008 4448-4448/com.iothub.azure.microsoft.com.androidsample W/System.err: 	... 4 more**

**Comment by barustum** [comment] 2021-06-24 22:17
Hi @nishanthvasu 

Please try uncommenting this line from the proguard rules file:
-keep class com.microsoft.azure.sdk.iot.provisioning.device.internal.parser.* { *; }

Because this is an application that uses the provisioning service device client sdk, we recommend that class should be excluded. The parser classes do not work well with minification because JSON parser classes use reflection based on the name of the field to create the JSON, and minification changes those names.

**Comment by nishanthvasu** [comment] 2021-06-28 13:24
Hi @barustum ,

Thanks for your comments but still it didn't worked out for me which gives the below error,

**Proguard File:**  [proguard-rules.zip](https://github.com/Azure/azure-iot-sdk-java/files/6726568/proguard-rules.zip)



PROVISIONING_DEVICE_STATUS_ERROR
E/exception :: c.e.b.b.a.c.a.f.d.b: Service error: null - null - TrackingId: null


W/System.err: java.util.concurrent.ExecutionException: c.e.b.b.a.c.a.f.d.b: Service error: null - null - TrackingId: null
W/System.err:     at java.util.concurrent.FutureTask.report(FutureTask.java:94)
W/System.err:     at java.util.concurrent.FutureTask.get(FutureTask.java:178)
W/System.err:     at c.e.b.b.a.c.a.f.f.d.a()
W/System.err:     at c.e.b.b.a.c.a.f.f.d.call()
W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
W/System.err:     at java.lang.Thread.run(Thread.java:818)
W/System.err: Caused by: c.e.b.b.a.c.a.f.d.b: Service error: null - null - TrackingId: null
W/System.err:     at c.e.b.b.a.c.a.f.f.e.c(:5)
W/System.err:     at c.e.b.b.a.c.a.f.f.e.call(:4)
W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
W/System.err: 	... 4 more
I/System.out: Registration error Provisioning Test, bailing out

**Comment by barustum** [comment] 2021-07-26 18:57
Hi @nishanthvasu,

I copied the same proguard rules files you provided, but I am unable to reproduce. A couple of things:
1. When you change the proguard rules file, do you ensure that you 'Sync Project with Grade files'?
2. Would it be possible to get a sample attached here that reproduces?

Thanks for your patience as we're trying to identify what's going on.

**Comment by nishanthvasu** [comment] 2021-08-02 04:26
Hi @barustum ,

[ProvisioningIssue.zip](https://github.com/Azure/azure-iot-sdk-java/files/6914377/ProvisioningIssue.zip)

Pls find the all the attached gradle files used in the project. build_deviceagent.gradle was the one used for provisioning. Also attached the class used for provisioning and errors which I receive as well as here.

**Comment by timtay-microsoft** [comment] 2022-04-06 00:36
Closing this thread because our library [doesn't officially support](https://github.com/Azure/azure-iot-sdk-java/blob/main/supported_platforms.md) using proguard for minification.

**Closed by timtay-microsoft** 2022-04-06 00:36 UTC
Labels: bug, Android, IoTSDK
