### ISSUE TITLE
[Device Client - MQTT] IotHubConnectionStatusChangeCallback not being called even if received error on DeviceClient.open()

### ISSUE THREAD

**Issue by Mauli317** [Azure/azure-iot-sdk-java#249] opened 2018-05-24 09:30 UTC
- **OS and version used:** Android 6.0.1
- **Java runtime used:** 1.7

- **SDK version used:** iot-device-client:1.10.0

# Description of the issue:
When I call open() method, it first gives IotHubConnectionStatus as CONNECTED in IotHubConnectionStatusChangeCallback and immediately after that it throws error "java.io.IOException: Could not open the connection" and does not notify of IotHubConnectionStatus DISCONNECTED in IotHubConnectionStatusChangeCallback. And when I try to send any message, it throws exception "java.lang.IllegalStateException: Cannot send event from an IoT Hub client that is closed.".

I have not observed this frequently but poor internet connection can be possible reason for this kind of behaviour. But in my code I have made sure that I call any method after checking internet availability.

So, issue here is it does not notify of IotHubConnectionStatus in IotHubConnectionStatusChangeCallback if anything goes wrong.

# Code sample exhibiting the issue:
```
private void start() {
        try {
            sClient = new DeviceClient(sConnString, IotHubClientProtocol.MQTT);
            sClient.registerConnectionStatusChangeCallback(new IotConnStatusCallback(), this);
            sClient.open();
        } catch (URISyntaxException | IOException e) {
            Log.e(TAG, "Exception in onStart()", e);
            mError = ERROR_STATE.ERROR;
        }
}
```

# Console log of the issue:
```
05-24 06:25:34.767 12805-13007/com.myapplication D/IotHubSvc: IotHubConnectionStatusChangeCallback status : CONNECTED. And reason : CONNECTION_OK
05-24 06:25:35.806 12805-13007/com.myapplication E/IotHubSvc: Exception in start()
    java.io.IOException: Could not open the connection
        at com.microsoft.azure.sdk.iot.device.DeviceIO.open(DeviceIO.java:164)
        at com.microsoft.azure.sdk.iot.device.DeviceClient.open(DeviceClient.java:372)
        at com.myapplication.Services.IoTHubService.start(IoTHubService.java:256)
        at com.myapplication.Services.IoTHubService.onHandleIntent(IoTHubService.java:103)
        at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: com.microsoft.azure.sdk.iot.device.exceptions.ProtocolException: Unable to subscribe to topic :
        at com.microsoft.azure.sdk.iot.device.transport.mqtt.exceptions.PahoExceptionTranslator.convertToMqttException(PahoExceptionTranslator.java:69)
        at com.microsoft.azure.sdk.iot.device.transport.mqtt.Mqtt.subscribe(Mqtt.java:267)
        at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttMessaging.start(MqttMessaging.java:41)
        at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttIotHubConnection.open(MqttIotHubConnection.java:177)
        at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.openConnection(IotHubTransport.java:630)
        at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.open(IotHubTransport.java:264)
        at com.microsoft.azure.sdk.iot.device.DeviceIO.open(DeviceIO.java:160)
        at com.microsoft.azure.sdk.iot.device.DeviceClient.open(DeviceClient.java:372) 
        at com.myapplication.Services.IoTHubService.start(IoTHubService.java:256) 
        at com.myapplication.Services.IoTHubService.onHandleIntent(IoTHubService.java:103) 
        at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
     Caused by: Timed out waiting for a response from the server (32000)
        at org.eclipse.paho.client.mqttv3.internal.Token.waitForCompletion(Token.java:112)
        at org.eclipse.paho.client.mqttv3.MqttToken.waitForCompletion(MqttToken.java:67)
        at com.microsoft.azure.sdk.iot.device.transport.mqtt.Mqtt.subscribe(Mqtt.java:262)
        at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttMessaging.start(MqttMessaging.java:41) 
        at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttIotHubConnection.open(MqttIotHubConnection.java:177) 
        at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.openConnection(IotHubTransport.java:630) 
        at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.open(IotHubTransport.java:264) 
        at com.microsoft.azure.sdk.iot.device.DeviceIO.open(DeviceIO.java:160) 
        at com.microsoft.azure.sdk.iot.device.DeviceClient.open(DeviceClient.java:372) 
        at com.myapplication.Services.IoTHubService.start(IoTHubService.java:256) 
        at com.myapplication.Services.IoTHubService.onHandleIntent(IoTHubService.java:103) 
        at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
05-24 06:25:35.807 12805-13007/com.myapplication D/IotHubSvc: IotHub Connection Status is CONNECTED
    IoTHubService did not start due to some unexpected error
05-24 06:25:35.808 12805-13007/com.myapplication E/IotHubSvc: OnHandleIntent action = com.myapplication.action.ACTION_SEND
05-24 06:25:35.808 12805-13007/com.myapplication D/IotHubSvc: Current IoTHub connection status is CONNECTED, message can be sent
05-24 06:25:35.812 12805-13007/com.myapplication V/IotHubSvc: sending 295 bytes, callback key=1
05-24 06:25:35.813 12805-13007/com.myapplication E/IotHubSvc: Exception uploading to IoTHub:
    java.lang.IllegalStateException: Cannot send event from an IoT Hub client that is closed.
        at com.microsoft.azure.sdk.iot.device.DeviceIO.sendEventAsync(DeviceIO.java:280)
        at com.microsoft.azure.sdk.iot.device.DeviceClient.sendEventAsync(DeviceClient.java:477)
        at com.myapplication.Services.IoTHubService.onSendData(IoTHubService.java:346)
        at com.myapplication.Services.IoTHubService.onHandleIntent(IoTHubService.java:122)
        at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by timtay-microsoft** [comment] 2018-05-24 17:27
I see what the bug here is, I'll see if I can get a fix for this out soon.

**Comment by timtay-microsoft** [comment] 2018-05-24 21:27
The fix for this issue has been checked in and should be released tomorrow. Feel free to try building from source yourself to check if the bug was fixed for you, too.

**Comment by Mauli317** [comment] 2018-05-25 06:48
Thank you @timtay-microsoft for responding quickly and fixing it. I will try building from source and check the fix.

**Comment by timtay-microsoft** [comment] 2018-05-25 20:15
The fix for this bug has been released now as a part of Device Client 1.11.1

Since this bug is fixed, I'm going to close this issue. Feel free to re-open if you still see this issue.

@Mauli317 thank you for your contribution to our open-sourced project!  Please help us improve by filling out this 2-minute [customer satisfaction survey](https://www.surveymonkey.com/r/Q5PLZ3V).

**Closed by timtay-microsoft** 2018-05-25 20:15 UTC
Labels: bug, fix checked in

**Comment by hidips** [comment] 2018-06-19 08:33
I see similar issue with Mqtt.connect while trying to connect IOT Hub:
client = new DeviceClient(connString, protocol);
client.open();
throws following error:

java.io.IOException: Could not open the connection
	at com.microsoft.azure.sdk.iot.device.DeviceIO.open(DeviceIO.java:164)
	at com.microsoft.azure.sdk.iot.device.DeviceClient.open(DeviceClient.java:372)
	at com.microsoft.docs.iothub.samples.SimulatedDevice.main(SimulatedDevice.java:169)
Caused by: com.microsoft.azure.sdk.iot.device.exceptions.ProtocolException: Unable to establish MQTT connection
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.exceptions.PahoExceptionTranslator.convertToMqttException(PahoExceptionTranslator.java:69)
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.Mqtt.connect(Mqtt.java:105)
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttMessaging.start(MqttMessaging.java:40)
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttIotHubConnection.open(MqttIotHubConnection.java:181)
	at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.openConnection(IotHubTransport.java:642)
	at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.open(IotHubTransport.java:276)
	at com.microsoft.azure.sdk.iot.device.DeviceIO.open(DeviceIO.java:160)
	... 2 more
Caused by: Unable to connect to server (32103) - java.net.ConnectException: Connection timed out: connect
	at org.eclipse.paho.client.mqttv3.internal.TCPNetworkModule.start(TCPNetworkModule.java:79)
	at org.eclipse.paho.client.mqttv3.internal.SSLNetworkModule.start(SSLNetworkModule.java:86)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:650)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.net.ConnectException: Connection timed out: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)

**Comment by timtay-microsoft** [comment] 2018-06-19 17:38
We can discuss this in the issue you created instead. This thread is about a separate issue that has already been resolved.
