### ISSUE TITLE
DeviceClient.subscribeToTwinDesiredProperties stop working suddenly on Android

### ISSUE THREAD

**Issue by FranAlterados** [Azure/azure-iot-sdk-java#431] opened 2019-01-31 15:22 UTC
- **OS and version used:** Android

- **Java runtime used:** 1.8

- **SDK version used:** 1.15.0

# Description of the issue:
We are using Desired Properties in our project and always everything went fine in the past, but two weeks ago Desired Properties started an inappropriate behavior. When getDeviceTwin() method is called not all properties are obtained from the server, but if I updated one of this lost properties I get the updated value, that means that I am correctly subscribed to the property but I don't know why the server doesn't send me all the stored values.

**Comment by timtay-microsoft** [comment] 2019-01-31 18:43
What protocol are you using? And did you upgrade to a different version of this SDK around the time you started seeing these problems?

**Comment by FranAlterados** [comment] 2019-02-01 09:45
We were using AMQPS, device-client 1.14.1 and iot-deps 0.7.1 and everything worked fine. After advice the problem we upgrade to last library version (device-client 1.15.0 and iot-deps 0.8.0), tried with all protocols (AMQPS, AMQPS_WS,MQTT,MQTT_WS,HTTPS) and the problem still persist.

HTTPS doesn't work. MQTT and MQTT_WS throws a connection error. AMQPS and AMQPS connect but don't send all the parameters.

We don't change anything and before everything worked fine.

**Comment by FranAlterados** [comment] 2019-02-11 08:24
Is there any news about it?

**Comment by yzhong94** [comment] 2019-02-12 22:04
Hi @FranAlterados sorry about the delay, this looks like a regression then.  Did you update to a new version of Android OS as well?

**Comment by jasmineymlo** [comment] 2019-02-14 02:49
@FranAlterados which Android API version are you using?  We will need to repro from our end.  We have nightly tests running on API 28 with the latest code in master and they seems to be fine.  "We were using AMQPS, device-client 1.14.1 and iot-deps 0.7.1 and everything worked fine."...do you mean that 2 weeks ago, the behavior of getDeviceTwin() changed and that's why you are upgrading to 1.15.0.  But after upgrade, you are still seeing the same behavior?  Thanks.

**Comment by FranAlterados** [comment] 2019-02-14 18:25
We are using Android API 28.
"do you mean that 2 weeks ago, the behavior of getDeviceTwin() changed and that's why you are upgrading to 1.15.0. But after upgrade, you are still seeing the same behavior?" 
exactly that
Thanks.

**Comment by jasmineymlo** [comment] 2019-02-19 18:02
Would you give me more details on what is the "behavior of getDeviceTwin() changed"?  A specific example would help us to understand the issue.  What are you getting back and what's the expectation etc?  We would need to repro the issue on our end to further investigate.  Thanks.

**Comment by FranAlterados** [comment] 2019-02-22 10:22
Here is an example tested on Xiaomi Mi A1 with Api level 28:

Android code:
```java
public class MainActivity extends AppCompatActivity {

    int numDesiredProperties = 10;
    public static final String NAME_TAG_1 = "test";
    public static final String NAME_TAG_2 = "atest";
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        start();
    }

    private DeviceClient deviceClient = null;

    public interface OnDesiredPropertyCallback {
        void onTelemetryConfigChanged(Property property);
    }

    OnDesiredPropertyCallback onDesiredPropertyCallback;

    public void setOnDesiredPropertyCallback(OnDesiredPropertyCallback onDesiredPropertyCallback) {
        this.onDesiredPropertyCallback = onDesiredPropertyCallback;
    }

    public interface DirectMethodToBlackBoxCallback {
        DeviceMethodData onDirectMethodReceived(String methodName, Object methodData);
    }

    DirectMethodToBlackBoxCallback directMethodToBlackBoxCallback;

    public void setDirectMethodToBlackBoxCallback(DirectMethodToBlackBoxCallback directMethodToBlackBoxCallback) {
        this.directMethodToBlackBoxCallback = directMethodToBlackBoxCallback;
    }

    /**
     * Inicia el controlador del DeviceClient de Azure
     */
    public void start() {
        try {
            IotHubClientProtocol protocol = IotHubClientProtocol.AMQPS;
            String publicKeyCertificate = null;
            String privateKey = null;
            String connString = "XXX";
            if (publicKeyCertificate == null && privateKey == null) {
                deviceClient = new DeviceClient(connString, protocol);
            } else {
                deviceClient = new DeviceClient(connString, protocol, publicKeyCertificate, false, privateKey, false);
            }
        } catch (Exception ex) {
            Log.e("DeviceMethodController", "Error creating Device Client");
            ex.printStackTrace();
        }
        startDeviceClient();
    }

    private void startDeviceClient() {
        try {
            deviceClient.open();
            deviceClient.subscribeToDeviceMethod(new DirectMethodCallback(), null, new DirectMethodStatusCallback(), null);
            deviceClient.startDeviceTwin(new DeviceTwinStatusCallback(), null, new PropertyCallback(), null);
            Log.d("azure","Subscribed to direct methods and polling for reported properties. Waiting...");

            System.out.println("Subscribe to Desired properties on device Twin...");
            Map<Property, Pair<TwinPropertyCallBack, Object>> desiredProperties = new HashMap<Property, Pair<TwinPropertyCallBack, Object>>() {
                {
                    for (int i = 0; i < numDesiredProperties; i++) {
                        put(new Property(NAME_TAG_1 + i, null), new Pair<TwinPropertyCallBack, Object>(new onDesiredPropertyChanged(), null));
                    }

                    for (int i = 0; i < numDesiredProperties; i++) {
                        put(new Property(NAME_TAG_2 + i, null), new Pair<TwinPropertyCallBack, Object>(new onDesiredPropertyChanged(), null));
                    }
                }
            };

            deviceClient.subscribeToTwinDesiredProperties(desiredProperties);

            deviceClient.getDeviceTwin();

        } catch (Exception e) {
            Log.d("azure","On exception, shutting down \n" + " Cause: " + e.getCause() + " \n" + e.getMessage());
            try {
                if (deviceClient != null) {
                    deviceClient.closeNow();
                }
            } catch (IOException e1) {
                e1.printStackTrace();
            }
            Log.d("azure","Shutting down...");
        }
    }

    /**
     * Cierra el cliente de Azure
     */
    public void close() {
        try {
            if (deviceClient != null) {
                deviceClient.closeNow();
            }
        } catch (IOException e1) {
            e1.printStackTrace();
        }
    }

    public void sendReportedProperties(final Property property) throws IOException {

        Log.d("azure", "enviando property: " + property.getKey() + "=" + property.getValue());
        Log.d("azure","Update reported properties...");
        Set<Property> reportProperties = new HashSet<Property>() {
            {
                add(property);
            }
        };
        deviceClient.sendReportedProperties(reportProperties);
    }

    private class onDesiredPropertyChanged implements TwinPropertyCallBack {
        @Override
        public void TwinPropertyCallBack(Property property, Object context) {
                Log.e("azure", "onTelemetryConfigChanged, Key: " + property.getKey() + " Value: " + property.getValue());
                onDesiredPropertyCallback.onTelemetryConfigChanged(property);
        }
    }

    protected static class DirectMethodStatusCallback implements IotHubEventCallback {
        public void execute(IotHubStatusCode status, Object context) {
            Log.d("Azure","IoT Hub responded to device method operation with status " + status.name());
        }
    }

    protected static class DeviceTwinStatusCallback implements IotHubEventCallback {
        public void execute(IotHubStatusCode status, Object context) {
            Log.d("azure","IoT Hub responded to device twin operation with status " + status.name());
        }
    }

    protected static class PropertyCallback implements PropertyCallBack<String, String> {
        public void PropertyCall(String propertyKey, String propertyValue, Object context) {
            Log.d("azure","PropertyKey:     " + propertyKey);
            Log.d("azure","PropertyKvalue:  " + propertyKey);
        }
    }

    protected class DirectMethodCallback implements com.microsoft.azure.sdk.iot.device.DeviceTwin.DeviceMethodCallback {
        @Override
        public DeviceMethodData call(String methodName, Object methodData, Object context) {
            return directMethodToBlackBoxCallback.onDirectMethodReceived(methodName, methodData);
        }
    }
}
```

Properties on Azure:

```
{
  "test0": 0,
  "test1": 1,
  "test2": 2,
  "test3": 3,
  "test4": 4,
  "test5": 5,
  "test6": 6,
  "test7": 7,
  "test8": 8,
  "test9": 9,
  "atest0": 0,
  "atest1": 1,
  "atest2": 2,
  "atest3": 3,
  "atest4": 4,
  "atest5": 5,
  "atest6": 6,
  "atest7": 7,
  "atest8": 8,
  "atest9": 9
}
```

Output from logcat:
```
2019-02-22 11:10:42.012 19220-19220/com.helloauto.desiredtest W/System.err: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
2019-02-22 11:10:42.013 19220-19220/com.helloauto.desiredtest W/System.err: SLF4J: Defaulting to no-operation (NOP) logger implementation
2019-02-22 11:10:42.013 19220-19220/com.helloauto.desiredtest W/System.err: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2019-02-22 11:10:43.484 19220-19220/com.helloauto.desiredtest D/azure: Subscribed to direct methods and polling for reported properties. Waiting...
2019-02-22 11:10:43.484 19220-19220/com.helloauto.desiredtest I/System.out: Subscribe to Desired properties on device Twin...
2019-02-22 11:10:43.510 19220-19220/com.helloauto.desiredtest D/OpenGLRenderer: Skia GL Pipeline
2019-02-22 11:10:43.567 19220-19278/com.helloauto.desiredtest I/Adreno: QUALCOMM build                   : 2df12b3, I07da2d9908
    Build Date                       : 10/04/18
    OpenGL ES Shader Compiler Version: EV031.25.03.01
    Local Branch                     : 
    Remote Branch                    : 
    Remote Branch                    : 
    Reconstruct Branch               : 
2019-02-22 11:10:43.567 19220-19278/com.helloauto.desiredtest I/Adreno: Build Config                     : S L 6.0.7 AArch64
2019-02-22 11:10:43.567 19220-19278/com.helloauto.desiredtest D/vndksupport: Loading /vendor/lib64/hw/gralloc.msm8953.so from current namespace instead of sphal namespace.
2019-02-22 11:10:43.572 19220-19278/com.helloauto.desiredtest I/Adreno: PFP: 0x005ff087, ME: 0x005ff063
2019-02-22 11:10:43.575 19220-19277/com.helloauto.desiredtest D/Azure: IoT Hub responded to device method operation with status OK_EMPTY
2019-02-22 11:10:43.579 19220-19278/com.helloauto.desiredtest I/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
2019-02-22 11:10:43.579 19220-19278/com.helloauto.desiredtest I/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
2019-02-22 11:10:43.585 19220-19278/com.helloauto.desiredtest I/OpenGLRenderer: Initialized EGL, version 1.4
2019-02-22 11:10:43.585 19220-19278/com.helloauto.desiredtest D/OpenGLRenderer: Swap behavior 2
2019-02-22 11:10:43.595 19220-19277/com.helloauto.desiredtest D/azure: IoT Hub responded to device twin operation with status OK
2019-02-22 11:10:43.637 19220-19278/com.helloauto.desiredtest D/vndksupport: Loading /vendor/lib64/hw/android.hardware.graphics.mapper@2.0-impl.so from current namespace instead of sphal namespace.
2019-02-22 11:10:43.638 19220-19278/com.helloauto.desiredtest D/vndksupport: Loading /vendor/lib64/hw/gralloc.msm8953.so from current namespace instead of sphal namespace.
2019-02-22 11:10:43.669 19220-19277/com.helloauto.desiredtest E/azure: onTelemetryConfigChanged, Key: atest0 Value: 0.0
2019-02-22 11:10:43.670 19220-19277/com.helloauto.desiredtest D/azure: IoT Hub responded to device twin operation with status OK
2019-02-22 11:10:43.703 19220-19277/com.helloauto.desiredtest E/azure: onTelemetryConfigChanged, Key: atest0 Value: 0.0
```

In gradle I have this:
```
implementation('com.microsoft.azure.sdk.iot:iot-device-client:1.15.0')
implementation('com.microsoft.azure.sdk.iot:iot-deps:0.8.0')
```

As you can see, from 20 properties uploaded to Azure I only receive one 'onTelemetryConfigChanged, Key: atest0 Value: 0.0' two times

**Comment by FranAlterados** [comment] 2019-03-04 12:42
Can you repro the issue with my code?

**Comment by FranAlterados** [comment] 2019-03-12 15:00
Is there any news about it?

**Comment by FranAlterados** [comment] 2019-03-19 07:53
I tried the code in a NON-android Java project and got the same output than an Android project. I don't get all the values stored in the cloud when the application starts.

In the beginning, this didn't happen and I got all the values (in the example the 20 values stored). I think this is not an expected behavior.

Please correct me if I'm wrong

**Comment by yzhong94** [comment] 2019-03-19 16:29
@FranAlterados I'm sorry about the delay, but due to resources, we cannot get to this problem immediately now.  If this is blocking production or time sensitive, can you also open a support ticket here?  https://docs.microsoft.com/en-us/azure/azure-supportability/how-to-create-azure-support-request

**Comment by FranAlterados** [comment] 2019-03-19 17:06
Thank you very much @yzhong94

**Comment by timtay-microsoft** [comment] 2019-03-19 18:42
@FranAlterados can you share the whole (Non-Android) Java project that you used to repro this issue? I want to try running it locally to understand this issue better

**Comment by timtay-microsoft** [comment] 2019-03-19 18:45
> HTTPS doesn't work. MQTT and MQTT_WS throws a connection error. AMQPS and AMQPS connect but don't send all the parameters.

Can you provide the stacktrace that you are seeing in the MQTT/MQTT_WS case?

**Comment by timtay-microsoft** [comment] 2019-03-19 20:28
I'm working to repro this issue, but I'm not seeing it so far. I edited one small block of code in our [DeviceTwinSample](https://github.com/Azure/azure-iot-sdk-java/blob/master/device/iot-device-samples/device-twin-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/DeviceTwinSample.java) such that it subscribes to 7 desired properties (Prop1, Prop2, ... Prop7)

```java
System.out.println("Subscribe to Desired properties on device Twin...");
Map<Property, Pair<TwinPropertyCallBack, Object>> desiredProperties = new HashMap<Property, Pair<TwinPropertyCallBack, Object>>()
{
    {
        put(new Property("Prop1", null), new Pair<TwinPropertyCallBack, Object>(new onHomeTempChange(), null));
        put(new Property("Prop2", null), new Pair<TwinPropertyCallBack, Object>(new onHomeTempChange(), null));
        put(new Property("Prop3", null), new Pair<TwinPropertyCallBack, Object>(new onHomeTempChange(), null));
        put(new Property("Prop4", null), new Pair<TwinPropertyCallBack, Object>(new onHomeTempChange(), null));
        put(new Property("Prop5", null), new Pair<TwinPropertyCallBack, Object>(new onHomeTempChange(), null));
        put(new Property("Prop6", null), new Pair<TwinPropertyCallBack, Object>(new onHomeTempChange(), null));
        put(new Property("Prop7", null), new Pair<TwinPropertyCallBack, Object>(new onHomeTempChange(), null));

    }
};
```

Then, before running this sample, I created a fresh device and gave it these desired properties: 

![image](https://user-images.githubusercontent.com/28789848/54638969-84a53b80-4a49-11e9-905c-e0aa5590a14e.png)

Then I ran the sample using the new device's connection string, and amqps, and I got this output

```
Successfully created an IoT Hub client.
Open connection to IoT Hub.

CONNECTION STATUS UPDATE: CONNECTED
CONNECTION STATUS REASON: CONNECTION_OK
CONNECTION STATUS THROWABLE: null

Start device Twin and get remaining properties...
IoT Hub responded to device twin operation with status OK
onProperty callback for desired property Prop1 to 1.0, Properties version:2
onProperty callback for desired property Prop2 to 2.0, Properties version:2
onProperty callback for desired property Prop7 to 7.0, Properties version:2
onProperty callback for desired property Prop3 to 3.0, Properties version:2
onProperty callback for desired property Prop4 to 4.0, Properties version:2
onProperty callback for desired property Prop5 to 5.0, Properties version:2
onProperty callback for desired property Prop6 to 6.0, Properties version:2
onProperty callback for reported property LivingRoomLights to ON, Properties version:8
onProperty callback for reported property HomeTemp(F) to 70.0, Properties version:8
onProperty callback for reported property HomeSecurityCamera to SAFELY_WORKING, Properties version:8
Subscribe to Desired properties on device Twin...
Get device Twin...
Update reported properties...
Updating reported properties..
Updating reported properties..
Updating reported properties..
Updating reported properties..
Updating reported properties..
Waiting for Desired properties
Press any key to exit...
IoT Hub responded to device twin operation with status OK
onHomeTempChange change Prop1 to 1.0, Properties version:2
onHomeTempChange change Prop2 to 2.0, Properties version:2
onHomeTempChange change Prop7 to 7.0, Properties version:2
onHomeTempChange change Prop3 to 3.0, Properties version:2
onHomeTempChange change Prop4 to 4.0, Properties version:2
onHomeTempChange change Prop5 to 5.0, Properties version:2
onHomeTempChange change Prop6 to 6.0, Properties version:2
onProperty callback for reported property LivingRoomLights to ON, Properties version:8
onProperty callback for reported property HomeTemp(F) to 70.0, Properties version:8
onProperty callback for reported property HomeSecurityCamera to SAFELY_WORKING, Properties version:8
IoT Hub responded to device twin operation with status OK
IoT Hub responded to device twin operation with status OK
IoT Hub responded to device twin operation with status OK
IoT Hub responded to device twin operation with status OK
IoT Hub responded to device twin operation with status OK
IoT Hub responded to device twin operation with status OK
IoT Hub responded to device twin operation with status OK

CONNECTION STATUS UPDATE: DISCONNECTED
CONNECTION STATUS REASON: CLIENT_CLOSE
CONNECTION STATUS THROWABLE: null

Shutting down...

Process finished with exit code 0
```

Note that the TwinPropertyCallback was fired for each of the 7 desired properties. This is inconsistent with what you are reporting correct? You are only seeing a desired property callback for one of your desired properties (twice). Can you please follow my steps above to see if you can get the same correct behavior?

I ran this test using JDK 1.8, and the latest code on our master branch of this repository, and I see the same exact behavior when I try it on the DeviceClient 1.14.1 code that you first saw this issue on.

**Comment by FranAlterados** [comment] 2019-03-22 14:26
Thank you @timtay-microsoft with your code sample I could find the error and it was in my code.

I need to change this:
```
deviceClient.startDeviceTwin(new DeviceTwinStatusCallback(), null, new **PropertyCallback()**, null);
```
By this:
```
deviceClient.startDeviceTwin(new DeviceTwinStatusCallback(), null, new **onDesiredPropertyChanged()**, null);
```

and set two callbacks that was null.

The issue can be closed.

Thank you very much

**Comment by timtay-microsoft** [comment] 2019-03-22 17:39
Awesome, I'm glad to hear the issue was resolved! I'm going to close this issue, but feel free to re-open/leave a comment if you have any further questions on this issue.

**Comment by az-iot-builder-01** [comment] 2019-03-22 17:40
@FranAlterados, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Closed by timtay-microsoft** 2019-03-22 17:39 UTC
Labels: Android, investigation-required
