### ISSUE TITLE
IoT SDK does not compile under JDK 11

### ISSUE THREAD

**Issue by JonathanGiles** [Azure/azure-iot-sdk-java#321] opened 2018-08-27 08:41 UTC
For future compatibility purposes it would be great to do a pass on the IoT SDK to remove dependencies on non-public API that were hidden after JDK 9. An example include use of `sun.security.tools.keytool.CertAndKeyGen`.

**Comment by timtay-microsoft** [comment] 2018-08-27 17:48
We'll look into doing this soon. Thanks for filing the issue!

**Comment by JonathanGiles** [comment] 2018-08-27 22:15
[This pull request](https://github.com/Azure/azure-iot-sdk-java/pull/322) gets to the point where things at least build under JDK 11 - but that doesn't mean everything works under JDK 11 :-) It's a step in the right direction, anyway, and it means I can continue to build JDK 11 javadocs for the azure-iot-sdk-java project.

**Comment by timtay-microsoft** [comment] 2020-03-30 18:46
Closing this issue as a duplicate of #555 for bringing JDK 11/12 support to this SDK

**Comment by az-iot-builder-01** [comment] 2020-03-30 18:46
@JonathanGiles, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Closed** 2020-03-30 18:46 UTC
Labels: IoTSDK, JDK 12 support, enhancement
