### ISSUE TITLE
Create Device Client using x509 cert and private key and Access Device Twin

### ISSUE THREAD

**Issue by payalgaikwad42** [Azure/azure-iot-sdk-java#1339] opened 2021-09-06 11:32 UTC
Hi @varunpuranik, 
I have had the questions previously answered by you regarding IoT Edge hence tagging you. 
I have an java springboot application deployed as a Azure IoT Edge module on a Linux vm with proxy setup. 
IoT Edge version -  1.2.3 installed 
ubuntu - 18.04. 
Provisioning method - DPS provisioning with x509 certificate. 
My Vm network has only one port open which is - 443
Now I am creating a device client using x509 cert and private key to connect with device twin and send a reported property.

`DeviceClient iothubClient = new DeviceClient(connString, IotHubClientProtocol.AMQPS_WS, publicKeyCertificate, true, privateKey, true);
iothubClient.startDeviceTwin(new DesiredProperties.DeviceTwinStatusCallBack(), null,new DesiredProperties.OnProperty(), null);
iothubClient.getDeviceTwin();
`

I am getting following error with AMQP_WS. 
![Screenshot (272)](https://user-images.githubusercontent.com/42204123/132210255-5c4045d3-2184-43e5-8164-0e26e068fe28.png)

As no other port is opened I don't think I can use MQTT or AMQP protocol. I tried with MQTT_WS but getting similar error of "connection could not be opened".

could you please guide me to correct documentation to access device twin with x509 cert? 
is there any other way to connect with iothub and access device twin ? Can we use moduleclient ?

Thank you

**Comment by timtay-microsoft** [comment] 2021-09-07 19:03
Just to be clear, are you trying to create a module client or a device client here? Device clients can connect as downstream devices from the edge device, but module clients are supposed to be run on the edge device itself. The code snippet you provided suggests you are connecting as a leaf device and not as an edge module.

Can you share the format of the connection string you are using here? (with the secrets removed)

And if you are connecting as a leaf device, do you see the same error when you connect directly to the cloud rather than connecting to your edgehub?

**Comment by timtay-microsoft** [comment] 2021-09-10 16:32
@payalgaikwad42 can you provide some extra context here?

**Comment by payalgaikwad42** [comment] 2021-09-13 06:00
@timtay-microsoft Hi, sorry for the late reply. 
The use case is as follows: 
1. I have one java iotedge module deploy on linux machine. 
2. I am creating **ModuleClient**   as we usually create it for communication. using 
`IotHubClientProtocol protocol = IotHubClientProtocol.MQTT;`
`client = ModuleClient.createFromEnvironment(protocol);` 
3. I am also creating device client in the same file to connect directly to iothub and update device client using 
`IotHubClientProtocol protocol1 = IotHubClientProtocol.AMQPS_WS;`
`DeviceClient iothubClient = new DeviceClient(connString, protocol1, publicKeyCertificate, true, privateKey,true);`
4. connection string used for the device client is as follow: 
`String connString = "Hostname="+ System.getenv("IOTEDGE_IOTHUBHOSTNAME")+ ";" + "DeviceId=" +System.getenv("IOTEDGE_DEVICEID")+ ";" + "x509=true";`
5. now as per my understanding we cannot use **ModuleClient**  to connect to iotedge device twin on the cloud hence I created **DeviceClient** separately. 
6. My system environment is restricted we have proxy setup. The only port which is open is 443. With port 443 **AMQPS_WS** should work while connecting to iothub using **DeviceClient** right?

**Device twin operation using DeviceClient in IoT Edge module using AMQPS_WS protocol on  port 443**

**Comment by payalgaikwad42** [comment] 2021-09-13 06:13
Here is the snippet of the code I am using along with the error I am getting for AMQPS_WS deviceclient: 

                     `String connString = "Hostname=" + System.getenv("IOTEDGE_IOTHUBHOSTNAME") + ";" + "DeviceId="
					+ System.getenv("IOTEDGE_DEVICEID") + ";" + "x509=true";
			System.out.println(" Connection string for creating device client " + connString);

			HashMap<String, String> t = CertPath.getCertPath("/app/tenant/");

			String publicKeyCertificate = "/app/tenant/" + t.get("publickeycertpath");
			String privateKey = "/app/tenant/" + t.get("privatekeypath");

			IotHubClientProtocol protocol = IotHubClientProtocol.MQTT;
			IotHubClientProtocol protocol1 = IotHubClientProtocol.AMQPS_WS;
			System.out.println("protocol used for creating moduleclient " + protocol);
			System.out.println("protocol used for creating Device client " + protocol1);
			DeviceClient iothubClient = new DeviceClient(connString, protocol1, publicKeyCertificate, true, privateKey,
					true);
			ModuleClient client = ModuleClient.createFromEnvironment(protocol);
			client.registerConnectionStatusChangeCallback(
					new ConnectionStatusChangeParentCallback.ConnectionStatusChangeCallback(), null);
			client.open();
			logger.info("ModuleClient created and opened");
			client.startTwin(new DesiredProperties.DeviceTwinStatusCallBack(), null, new DesiredProperties.OnProperty(),
					null);
			client.subscribeToTwinDesiredProperties(onDesiredPropertyChange);
			client.getTwin();
			
			iothubClient.open();
			logger.info("iothubClient created and opened");
			iothubClient.startDeviceTwin(new DesiredProperties.DeviceTwinStatusCallBack(), null,
					new DesiredProperties.OnProperty(), null);
			iothubClient.getDeviceTwin();
			iothubClient.subscribeToTwinDesiredProperties(onDesiredPropertyChange);
			
			String tenandId = LoggingLoaderScheduler.getInstance().getTenandId("/app/tenant/tenantinfo.txt");
			Set<Property> deviceReportProperties = new HashSet<Property>() {
				{
					add(new Property("tenandId", tenandId));

				}
			};
	     iothubClient.sendReportedProperties(deviceReportProperties);
		 
		 Set<Property> moduleReportProperties = new HashSet<Property>() {
				{
					add(new Property("certExpiryDate", certExpiryDate));

				}
			};

			client.sendReportedProperties(moduleReportProperties);`


> 2021-09-13 05:32:36.294 ERROR 1 --- [           main] c.m.a.s.i.d.t.a.AmqpsIotHubConnection    : Timed out waiting for worker links to open
com.microsoft.azure.sdk.iot.device.exceptions.TransportException: Timed out waiting for worker links to open
        at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection.closeConnectionWithException(AmqpsIotHubConnection.java:686) [iot-device-client-1.28.0.jar!/:na]
        at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection.open(AmqpsIotHubConnection.java:156) [iot-device-client-1.28.0.jar!/:na]
        at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.openConnection(IotHubTransport.java:785) [iot-device-client-1.28.0.jar!/:na]
        at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.open(IotHubTransport.java:325) [iot-device-client-1.28.0.jar!/:na]
        at com.microsoft.azure.sdk.iot.device.DeviceIO.open(DeviceIO.java:156) [iot-device-client-1.28.0.jar!/:na]
        at com.microsoft.azure.sdk.iot.device.InternalClient.open(InternalClient.java:170) [iot-device-client-1.28.0.jar!/:na]
        at com.microsoft.azure.sdk.iot.device.DeviceClient.open(DeviceClient.java:426) [iot-device-client-1.28.0.jar!/:na]
        at com.ge.hc.csi.CsiEdgeDataLoggingApplication.main(CsiEdgeDataLoggingApplication.java:111) [classes!/:0.0.1]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_212]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_212]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_212]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_212]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) [app.jar:0.0.1]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:107) [app.jar:0.0.1]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) [app.jar:0.0.1]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) [app.jar:0.0.1]
2021-09-13 05:32:36.299 ERROR 1 --- [           main] c.g.h.csi.CsiEdgeDataLoggingApplication  : Error on exeution of desired prperty and scheduler job {} :
java.io.IOException: Could not open the connection
        at com.microsoft.azure.sdk.iot.device.DeviceIO.open(DeviceIO.java:160) ~[iot-device-client-1.28.0.jar!/:na]
        at com.microsoft.azure.sdk.iot.device.InternalClient.open(InternalClient.java:170) ~[iot-device-client-1.28.0.jar!/:na]
        at com.microsoft.azure.sdk.iot.device.DeviceClient.open(DeviceClient.java:426) ~[iot-device-client-1.28.0.jar!/:na]
        at com.ge.hc.csi.CsiEdgeDataLoggingApplication.main(CsiEdgeDataLoggingApplication.java:111) ~[classes!/:0.0.1]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_212]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_212]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_212]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_212]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) [app.jar:0.0.1]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:107) [app.jar:0.0.1]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) [app.jar:0.0.1]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) [app.jar:0.0.1]
Caused by: com.microsoft.azure.sdk.iot.device.exceptions.TransportException: Timed out waiting for worker links to open
        at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection.closeConnectionWithException(AmqpsIotHubConnection.java:686) ~[iot-device-client-1.28.0.jar!/:na]
        at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection.open(AmqpsIotHubConnection.java:156) ~[iot-device-client-1.28.0.jar!/:na]
        at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.openConnection(IotHubTransport.java:785) ~[iot-device-client-1.28.0.jar!/:na]
        at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.open(IotHubTransport.java:325) ~[iot-device-client-1.28.0.jar!/:na]
        at com.microsoft.azure.sdk.iot.device.DeviceIO.open(DeviceIO.java:156) ~[iot-device-client-1.28.0.jar!/:na]
        ... 11 common frames omitted
java.io.IOException: Could not open the connection
        at com.microsoft.azure.sdk.iot.device.DeviceIO.open(DeviceIO.java:160)
        at com.microsoft.azure.sdk.iot.device.InternalClient.open(InternalClient.java:170)
        at com.microsoft.azure.sdk.iot.device.DeviceClient.open(DeviceClient.java:426)
        at com.ge.hc.csi.CsiEdgeDataLoggingApplication.main(CsiEdgeDataLoggingApplication.java:111)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:107)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: com.microsoft.azure.sdk.iot.device.exceptions.TransportException: Timed out waiting for worker links to open
        at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection.closeConnectionWithException(AmqpsIotHubConnection.java:686)
        at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection.open(AmqpsIotHubConnection.java:156)
        at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.openConnection(IotHubTransport.java:785)
        at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.open(IotHubTransport.java:325)
        at com.microsoft.azure.sdk.iot.device.DeviceIO.open(DeviceIO.java:156)
        ... 11 more

**Comment by timtay-microsoft** [comment] 2021-09-13 23:07
The issue here may be that you are trying to connect as the Edge device to IoT hub in order to get its twin while the edge device itself already establishes that connection when running. IoT hub only allows for a particular device identity (whether a normal identity or that of an edge device) to have one open connection at a time. I'd bring this question to the [Azure IoT Edge](https://github.com/Azure/iotedge/issues) team to have them clarify if that is a scenario that is supported. 

As far as the Java SDK is concerned, that error simply means that the device tried to establish the connection, but that the service failed to respond in time. If you see this timeout 100% of the time, its likely the issue I discussed above. However, if you are seeing this error only occasionally, then this could just be networking issues. This particular timeout can be configured to last longer in this case.

```java
DeviceClient dc; // omitted for brevity
dc.setOption("SetAmqpOpenDeviceSessionsTimeout", newTimeoutInSeconds);
dc.open();
```

**Comment by payalgaikwad42** [comment] 2021-09-14 05:06
@timtay-microsoft The issue is faced 100% of the time. 
I have tested this code in open network without any proxy and it works with MQTT protocol. 
we can open 2 connections separately using ModuleClient and DeviceClient to access Module twin and Device twin resp.
On the other hand, if we cannot open 2 connections **how do you suggest to access **device twin** from **IoT Edge module****? 
I have searched for documentations and Java SDK but didn't find anything relative. 

Also one more thing I need to access Device Twin in order to send reported property, based on that reported property I am creating a IoT Edge layered deployment. 
Is there a way I **can set target condition  to Module Twin in layered deployment** so that I wont need to use Device Twin at all?

please refer below image. I am setting target condition to device twin. can that be changed to module twin ?

![Screenshot (286)](https://user-images.githubusercontent.com/42204123/133197902-a7270537-f532-4213-9222-72a72d0efe42.png)

**Comment by payalgaikwad42** [comment] 2021-09-14 07:17
As I have mentioned before, My IoT Edge device is registered using DPS. Intermediate cert is uploaded to DPS, created the group enrollment and then added full chain device cert and device private key to config.toml file. 

So when I create Device client which sdk should be used? I am using azure-iot-device sdk. 
with constructor:

`public DeviceClient(String connString, IotHubClientProtocol protocol, String publicKeyCertificate, boolean isCertificatePath, String privateKey, boolean isPrivateKeyPath)`

refered doc :
https://docs.microsoft.com/en-us/java/api/com.microsoft.azure.sdk.iot.device.deviceclient.deviceclient?view=azure-java-stable#com_microsoft_azure_sdk_iot_device_DeviceClient_DeviceClient_java_lang_String_com_microsoft_azure_sdk_iot_device_IotHubClientProtocol_java_lang_String_boolean_java_lang_String_boolean_

**Comment by payalgaikwad42** [comment] 2021-09-14 11:47
Is there any documentation explaining how to configure device and DPS when you select **intermediate cert as a certificate type** in DPS group enrollment ? 

![Screenshot (287)](https://user-images.githubusercontent.com/42204123/133251989-8f113112-844e-4de4-a4e2-5cfd889424de.png)

**Comment by timtay-microsoft** [comment] 2021-10-04 22:09
I'm working with the user on this issue outside of this thread since they opened a support ticket. So far, the issue seems to be caused by local network firewall rules, so I'm closing this issue as it doesn't appear to be an SDK bug. I'll continue working on this issue the user is facing through their support ticket.

**Closed by timtay-microsoft** 2021-10-04 22:09 UTC
Labels: question, customer input needed, IoTSDK
