### ISSUE TITLE
[Device SDK / MQTT] sendEventAsync blocks after connection is lost and message expiry time is ignored

### ISSUE THREAD

**Issue by pizerg** [Azure/azure-iot-sdk-java#99] opened 2017-06-01 15:02 UTC
- **OS and version used:** Windows 8 / OS X 10.12.5 / Raspbian Jessie

- **Java runtime used:** 1.8 latest version available on each platform

- **SDK version used:** 1.2.27

# Description of the issue:
There are several issues happening when using MQTT protocol and internet connection drops:

* The SDK allows to keep sending messages even when the connection is lost, this becomes a problem as the callback is invoked immediately with status OK_EMPTY

* After a while the SDK becomes aware of the disconnection and starts the reconnection process, if we call sendEventAsync during the process and without restoring internet connection the method will block the execution due to the "synchronized" block in the implementation while adding the message to the sending queue. As the method is supposed to be async, this should never happen.

* If we have set "expiryTime" property for the message we're sending the SDK ignores it, in case of disconnection and "expiryTime" set (or if for some other reason the server is not available at that moment) we should get the callback invoked with proper error status after expiryTime milliseconds have passed.

# Code sample exhibiting the issue:
Some code to reproduce the issue, it's a variation of one of the samples that sends continuously a message after 5 seconds, just fire it up and interrupt your internet connection after DeviceClient has opened the connection and sent at least one message, then just wait until it starts to reconnect and it will soon get blocked right after calling sendEventAsync

```

public void reproIssue(){
	Scanner sc = new Scanner(System.in);
	
	String connectionString = "YOUR CONNECTION STRING HERE";
		
	sc.nextLine();
		
	new Thread(() -> {
		DeviceClient client = null;
		
		try {
			client = new DeviceClient(connectionString, IotHubClientProtocol.MQTT);
			client.open();
		} catch (Exception e1) {
			e1.printStackTrace();
		}
			
		while(isRunning){
			Message m = new Message("test");
			m.setMessageId(UUID.randomUUID().toString());
			m.setExpiryTime(4000);
			
			System.out.println("Before send async");
			client.sendEventAsync(m, new EventCallback(), m);
			System.out.println("After send async");
		
			try{
				Thread.sleep(5000);
			} catch (Exception e){}
		}
			
		try {
			client.closeNow();
		} catch (IOException e) {
			e.printStackTrace();
		}
	}).start();
		
	sc.nextLine();
	isRunning = false;
		
	sc.close();
}

protected static class EventCallback implements IotHubEventCallback
{
        public void execute(IotHubStatusCode status, Object context)
        {
            Message msg = (Message) context;
            
            System.out.println("IoT Hub responded to message "+ msg.getMessageId()  + " with status " + status.name());
        }
}

```

# Console log of the issue:

Before send async
After send async
IoT Hub responded to message 29c3c899-8eb1-4668-bf54-c771f9650480 with status OK_EMPTY

<------- INTERNET CONNECTION INTERRUPTED HERE ------>

Before send async
After send async
IoT Hub responded to message f21524e5-4fbb-4139-af9d-4a05436d9146 with status OK_EMPTY
Before send async
After send async
IoT Hub responded to message 2fc7ca40-9225-48c8-ab67-93b88dad0e84 with status OK_EMPTY
Before send async
After send async
IoT Hub responded to message eaadb10d-25b3-4954-a13d-5b6d89f335ba with status OK_EMPTY
Before send async
After send async
IoT Hub responded to message ec3c861d-9008-45dc-bb21-996e35265cf3 with status OK_EMPTY
Before send async
After send async
IoT Hub responded to message 8f0c0c3f-097b-4bf0-80f5-f85518b76df7 with status OK_EMPTY
Before send async
After send async
IoT Hub responded to message 895d6bb8-4931-4bee-9d6a-2eb53521fad2 with status OK_EMPTY
Before send async
After send async
IoT Hub responded to message 4dcfdfac-c74b-44a7-a6cd-80f0b6c45959 with status OK_EMPTY
Before send async
After send async
IoT Hub responded to message 257e94d3-338a-47a0-8ef3-8aa103344505 with status OK_EMPTY
Before send async
After send async
IoT Hub responded to message 8d8b6c86-9964-4a42-b5ad-1b3fbf3af1cf with status OK_EMPTY
Before send async
After send async
IoT Hub responded to message ae7d7e9f-f33f-4883-85c8-d24e624fa49e with status OK_EMPTY
Lost connection to the server. Reconnecting 0 time.
Lost connection to the server. Reconnecting 1 time.
Before send async
After send async
Lost connection to the server. Reconnecting 2 time.
Before send async
Lost connection to the server. Reconnecting 3 time.
Lost connection to the server. Reconnecting 4 time.

**Comment by prmathur-microsoft** [comment] 2017-07-06 01:10
Responses to your issues : 

1. The SDK allows to keep sending messages even when the connection is lost, this becomes a problem as the callback is invoked immediately with status OK_EMPTY
Ans :  From your scenario, if you received OK_EMPTY then it was responded by IotHub which we queued inside SDK. And perhaps you may be receiving it even after disconnection (if it was queued prior to disconnection). However you are right about informing user upon disconnection. We have it in our backlog to address this.

2.After a while the SDK becomes aware of the disconnection and starts the reconnection process, if we call sendEventAsync during the process and without restoring internet connection the method will block the execution due to the "synchronized" block in the implementation while adding the message to the sending queue. As the method is supposed to be async, this should never happen.
Ans : As far as I can see from device client, to device IO to transport there is no place where we use `synchronized` block. So send event Async is an asynchronous operation. However underneath we queue these messages and retrieve it one after another for which we try to `synchronize` between threads and it is expected behavior as we can publish only one message at a time. This however happens inside a thread which is an asynchronous operation.

If we have set "expiryTime" property for the message we're sending the SDK ignores it, in case of disconnection and "expiryTime" set (or if for some other reason the server is not available at that moment) we should get the callback invoked with proper error status after expiryTime milliseconds have passed.
Ans :  You are right about this scenario. A message gets added to waiting list if it not sent we never triggers a call back if it expires. We will work on this bug.

**Comment by pizerg** [comment] 2017-07-07 13:48
> 2.After a while the SDK becomes aware of the disconnection and starts the reconnection process, if we call sendEventAsync during the process and without restoring internet connection the method will block the execution due to the "synchronized" block in the implementation while adding the message to the sending queue. As the method is supposed to be async, this should never happen.
> Ans : As far as I can see from device client, to device IO to transport there is no place where we use synchronized block. So send event Async is an asynchronous operation. However underneath we queue these messages and retrieve it one after another for which we try to synchronize between threads and it is expected behavior as we can publish only one message at a time. This however happens inside a thread which is an asynchronous operation.

This is not correct, let's follow the invocation step by step:

On DeviceClient  we invoke `sendEventAsync(Message message, IotHubEventCallback callback, Object callbackContext)`

-> Internally it calls

DeviceIO `deviceIO.sendEventAsync(message, callback, callbackContext);`

-> Internally it calls

(in this case transport is an instance of MqttTransport)` transport.addMessage(message, callback, callbackContext);` where on the first line we can clearly see the `synchronized (sendMessagesLock)`

So clearly this is not happening in a different thread and it's causing an "async" method to block as another thread did not release the object monitor when the disconnection happened (at least when writting this issue, I think this has already been addressed with some pull request that fixed the thread that kept the monitor indefinitely)

**Comment by oriolpinol** [comment] 2017-07-10 10:26
Hi,
I am having the same problem here after a disconnection without a successful reconnection causing all the threads getting stuck waiting for the lock to happen. 

One thread locked on sendMessagesLock:

`"pool-4-thread-2" #2071 prio=5 os_prio=0 tid=0x00007fe5d4061800 nid=0x87f waiting for monitor entry [0x00007fe5a3479000]
   java.lang.Thread.State: BLOCKED (on object monitor)
        at com.microsoft.azure.sdk.iot.device.transport.mqtt.Mqtt.publish(Mqtt.java:286)
        - waiting to lock <0x00000000982c0f40> (a java.lang.Object)
        at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttMessaging.send(MqttMessaging.java:259)
        at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttIotHubConnection.sendEvent(MqttIotHubConnection.java:230)
        - locked <0x00000000982c6708> (a java.lang.Object)
        at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttTransport.sendMessages(MqttTransport.java:208)
        - locked <0x0000000097ed2950> (a java.lang.Object)
        at com.microsoft.azure.sdk.iot.device.transport.IotHubSendTask.run(IotHubSendTask.java:41)`

and then every other thread that calls sendEventAsync gets blocked there:

`
"HttpClient@877552828-6936" #6936 prio=5 os_prio=0 tid=0x00007fe5cc04f000 nid=0x1c3c waiting for monitor entry [0x00007fe5a367b000]
   java.lang.Thread.State: BLOCKED (on object monitor)
        at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttTransport.addMessage(MqttTransport.java:136)
        - waiting to lock <0x0000000097ed2950> (a java.lang.Object)
        at com.microsoft.azure.sdk.iot.device.DeviceIO.sendEventAsync(DeviceIO.java:292)
        at com.microsoft.azure.sdk.iot.device.DeviceClient.sendEventAsync(DeviceClient.java:275)
`

`"HttpClient@877552828-17999" #17999 prio=5 os_prio=0 tid=0x00007fe5d855c800 nid=0x4773 waiting for monitor entry [0x00007fe5972bc000]
   java.lang.Thread.State: BLOCKED (on object monitor)
        at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttTransport.addMessage(MqttTransport.java:136)
        - waiting to lock <0x0000000097ed2950> (a java.lang.Object)
        at com.microsoft.azure.sdk.iot.device.DeviceIO.sendEventAsync(DeviceIO.java:292)
        at com.microsoft.azure.sdk.iot.device.DeviceClient.sendEventAsync(DeviceClient.java:275)
`

**Comment by oriolpinol** [comment] 2017-07-10 10:31
Also, if we try to close the connection to restart it, it ends up trying to grab the same lock and not being able to close.

`"qtp800735172-29100" #29100 prio=5 os_prio=0 tid=0x00007fe5d831c000 nid=0x7327 waiting for monitor entry [0x00007fe5971ba000]
   java.lang.Thread.State: BLOCKED (on object monitor)
        at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttTransport.invokeCallbacks(MqttTransport.java:233)
        - waiting to lock <0x0000000097ed2950> (a java.lang.Object)
        at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttTransport.close(MqttTransport.java:112)
        at com.microsoft.azure.sdk.iot.device.DeviceIO.close(DeviceIO.java:254)
        at com.microsoft.azure.sdk.iot.device.DeviceClient.closeNow(DeviceClient.java:245)`

**Comment by prmathur-microsoft** [comment] 2017-07-11 18:28
We will work on this issue related to lock and update you of our findings soon.

**Comment by ts4iot** [comment] 2017-07-17 06:02
Hi,

I have the same problem and need a workaround for it. I use the Azure Java SDK on Android to send Messages in an 100ms interval to the IoT hub. After a network disconnection the GUI of the smartphone app freezes even though I run the user interface, backend communication and data capturing in different threads. My first idea was to monitor the connection state an stop/start the data capturing and backend communication thread dependend on the connection state. But the monitoring of the connection state is not fast enough to prevent the data capturing thread to send some messages to the sdk before stopping. Is there a workaround to remove the lock programatically until a bugfix is in place?

**Comment by xiaolingcong** [comment] 2017-08-17 12:02
Hi,
I have the same problem too.

**Comment by rahulsabharwal** [comment] 2017-11-20 10:05
We have the same issue. This has become a blocker since the main thread blocks and gets into an infinite loop of "Lost connection to the server. Reconnecting xx time." .. By when is a fix for this issue expected ?

**Comment by prmathur-microsoft** [comment] 2017-11-20 21:03
While we work on providing a fix, feel free to send a PR and I'll be happy to review it for you.

**Comment by timtay-microsoft** [comment] 2017-12-04 22:05
This issue is being actively looked into right now. 3 bug fixes will be coming soon to resolve this issue:

1) SendEventAsync over MQTT will no longer block when internet connection is lost.
2) Message expiry time will be respected by MQTT. A callback will be fired to notify that the message expired if it is not sent in time.
3) ConnectionStateCallback will be used to notify users that a CONNECTION_DROP has occurred.

Sorry for the delay on this. It should be coming in the next release.

**Comment by pperezp306** [comment] 2017-12-06 18:22
Usé un protocolo AMQP, y tengo el mismo problema, mi dispositivo está conectado durante aproximadamente 1 hora, luego el dispositivo se desconecta de IoT. Necesito que la conexion sea estable y no se desconecte del IoT Hub. Alguna idea?
[logdevice.txt](https://github.com/Azure/azure-iot-sdk-java/files/1536368/logdevice.txt)

**Comment by pperezp306** [comment] 2017-12-06 18:22
I used an AMQP protocol, and I have the same problem, my device is connected for about 1 hour, then the device is disconnected from IoT. I need the connection to be stable and not be disconnected from the IoT Hub. Any ideas?
[logdevice.txt](https://github.com/Azure/azure-iot-sdk-java/files/1536372/logdevice.txt)

**Comment by pperezp306** [comment] 2017-12-06 18:25
I used an AMQP protocol, and I have the same problem, my device is connected for about 1 hour, then the device is disconnected from IoT. I need the connection to be stable and not be disconnected from the IoT Hub. Any ideas?
[logdevice.txt](https://github.com/Azure/azure-iot-sdk-java/files/1536385/logdevice.txt)

[simulatedDevice.txt](https://github.com/Azure/azure-iot-sdk-java/files/1536386/simulatedDevice.txt)

**Comment by pperezp306** [comment] 2017-12-06 18:26
I used an AMQP protocol, and I have the same problem, my device is connected for about 1 hour, then the device is disconnected from IoT. I need the connection to be stable and not be disconnected from the IoT Hub. Any ideas? I attached my code here, the version of the libraries are: device-
[simulatedDevice.txt](https://github.com/Azure/azure-iot-sdk-java/files/1536391/simulatedDevice.txt)
[logdevice.txt](https://github.com/Azure/azure-iot-sdk-java/files/1536392/logdevice.txt)

client-1.4.34

**Comment by timtay-microsoft** [comment] 2017-12-06 18:28
@pperezp306 I think your problem is actually tied to Github Issue #180   

This thread pertains to MQTT specific issues, not AMQP

**Comment by ts4iot** [comment] 2017-12-14 11:38
I checked it with:
**com.microsoft.azure.sdk.iot:iot-device-client:1.6.0**
and the problem is still there. When I disable the internet connection, the code stops at **client.sendEventAsync(msg, eventCallback, msgId);** 
and continues when the internet connection is available again.

**Comment by timtay-microsoft** [comment] 2017-12-21 21:38
Just a quick update on this issue:

A fix has been checked in for two of the three bugs at play here.

1) ConnectionStateCallback for MQTT now will notify you when connection is dropped (as long as your register it).
2) Message expiry time is now respected. If you set a message to expire, it won't be sent if it expires before it can be sent.

The above fixes will be in the next release.

The third issue, where sendEventAsync blocks when connection has been lost, is still being looked at.

**Comment by timtay-microsoft** [comment] 2018-01-24 22:13
Update:

The two bugs outlined above (connection state callback, and message expiry time) have now been fixed as of [Device Client Version 1.7.0](https://github.com/Azure/azure-iot-sdk-java/releases/tag/2018-1-23)

The fix for the mqtt deadlock issue is still being worked on and I will update this thread as it progresses.

**Comment by timtay-microsoft** [comment] 2018-02-02 18:21
The fix for the final issue here (where sendEventAsync does not behave asynchronously) has been checked in and will be in the next release on 2/9.

**Comment by timtay-microsoft** [comment] 2018-02-12 19:51
The fix for the final issue here has been released. You can pull the new Device Client library. Go ahead and upgrade to 1.8.0 to get this fix.

https://github.com/Azure/azure-iot-sdk-java/releases/tag/2018-2-9

I'm closing this issue. Feel free to re-open if you are still facing issues with this.

**Closed by timtay-microsoft** 2018-02-12 19:51 UTC
Labels: bug, fix checked in
