### ISSUE TITLE
[ModuleClient] Sending Queue out of memory

### ISSUE THREAD

**Issue by kugelbit** [Azure/azure-iot-sdk-java#285] opened 2018-07-26 07:56 UTC
- **OS and version used:** <VERSION>  Yocto Linux

- **Java runtime used:** <VERSION> 1.8

- **SDK version used:** <VERSION>  1.13.1 

- **transmission Protocol:** <VERSION>  MQTT

# Description of the issue:

You implemented a queue for sending messages. If there is no connection to the cloud the messages will be stored in this queue and after a succsessful reconnect the stored messages will be send. 
For the queue you use a ConcurrentLinkedQueue wich is not memory bounded. The problem is i'm working on a memory constrained device and i have to face long time connection drops.
So it could happen that in a long time connection drop my device run out of memory and my app crashs with a out of memory exception. Is there any way to handle that? 

In my app i have timer which is reset every time there is interaction (getting a callback for a message, or when i direct method is called) with the cloud if there is no interaction for a specific time i want to clear the sending queue and trying to reconnect to the cloud (see code).
i tried the closeNow() function as a work around. The function empty the queue but also shut down the logical connection to the cloud which means a have to reconnect by my self. This leeds to strange behavior if there is
no physical connection to the cloud. In detail if there is no connection and i call closeNow() and open() directly after another i'm not able to use the message queue again.
It would be nice if there was a possebility to manage the memory of the queue like a function to empty the sending queue or option to bound the queue.

# Code sample exhibiting the issue:

      `while (true)
                {
                    try
                    {
                        Thread.sleep(1000);

                        if (new Date().getTime() > device.getLastConnectTime() + RECONNECTING_TIMEOUT)
                        {                            
                            device.reInit()
                            azureClient.closeNow();                            
                            azureClient.open();
                        }                        
                        azureClient.open();
                    }
                    catch (Exception ex)
                    {
                        L.error("no connection: ", ex.getMessage());
                    }
                  }`

**Comment by jasmineymlo** [comment] 2018-07-26 18:30
Thanks for filing the issue.  Currently, the SDK does not provide a way for message queue management.  It is up to the application implementation to limit the size of the queue in case of network disconnect/unavailable.  We have introduced the connection status update feature which would notify the application on the connection changes.  Implementating the notification might help in your case.  

See sample:
https://github.com/Azure/azure-iot-sdk-java/blob/8236200e491fe40546c9e4e0de2d56ec768e34e2/device/iot-device-samples/send-event/src/main/java/samples/com/microsoft/azure/sdk/iot/SendEvent.java#L181

In regards to the other issue that you mentioned:
"In detail if there is no connection and i call closeNow() and open() directly after another i'm not able to use the message queue again."  The expected behavior on closeNow() is that it will delete the queues and on open(), new message queues are being created and you should be able to send messages again.  SDK does NOT cache any messages in the original queue upon closeNow() and resend on open.  Is that the behavior that you are seeing?  Thanks.

**Comment by jasmineymlo** [comment] 2018-07-31 16:56
The connection status callback should be triggered by either at mqtt ping request failed or send event failed.  You will have to wait for worst case 240 second if you are not sending anything.  Are you seeing something different?

It is a good idea to invoke message callback upon expiry, it would be an enhancement to the current design.

**Comment by kugelbit** [comment] 2018-08-01 14:24
Indeed i see something different.

In my test app i always (with and without physical connection) send telemetry messages to the cloud with an interval of 1 second. 
In my tests my device  is connected to the internet over ethernet. To simulate a connection drop i simply unplug  the ethernet-cable. It seems that the underlying layers (Paho MQTT) do not chance their connection state  while trying to send messages with no physical connection. Hence there is no connection chance in the SDK and all incoming messages are saved in the waiting queue. Hence a connection chance is only observed when the PAHO-SDK tries to send an MQTT ping request. But this is only my theory. Im not sure about it. But this behavior would explain the results.  If you want a can share my little test app code and you can try this by your self. 

To came back to my first question: Are there plans to implement a queue management? do you discussed  this with your team ?  The queue management could also provide an Prioritization of the device to cloud messages (see Isue #244) 

There is another Thing i determined while testing:  
I wrote my own Retry-Policy were i always try to reconnect like this: 
```
public RetryDecision getRetryDecision(int currentRetryCount, TransportException lastException)
{
        System.out.println("retry count: "+ Integer.toString(currentRetryCount));
        return new RetryDecision(true, 5000);
}


```
In my first attempt i was testing in the way described in my second post. I had to face the following problem: When i was offline my app was trying to reconnect as expected but after some time close() was called and my app disconnected... After some debugging i found out i had to call setOperationTimeout(Long.MAX_VALUE)  to make my retry-policy work as expected. Because the internal retry-logic ran into a timeout.

Is this OperationTimeout really necessary in the retry logic when user can create it's own retry-policy? 
And if so could you please add a hint about the relation between the OperationTimeout and the retry-policy  in your retry-policy-documentation ([retry-doc](https://github.com/Azure/azure-iot-sdk-java/blob/master/device/iot-device-client/devdoc/requirement_docs/com/microsoft/azure/iothub/retryPolicy.md))?

**Comment by jasmineymlo** [comment] 2018-08-06 17:17
There is currently no plan to implement a queue management since the assumption is that with connection status notification, application would be able to manage the number of messages in the queue.  Please post it on [User Voice](https://feedback.azure.com/forums/321918-azure-iot) to help us prioritize.

setOperationTimeout is to control the max time for a given command, ie open or send.  This is the ultimate control for retry policy.   This is necessary for application using the default retry policy and would only want to limit the retry by time.  If you are implementing your own retry-policy, you are already doing the right thing to set the operation timeout to infinity.

**Comment by jasmineymlo** [comment] 2018-08-20 21:57
@kugelbit I have ran some test with our SendEvent sample.  I configure the sample to send 1 message using mqtt with a long (200s) message expiry.  After the message was sent and received on the iothub successfully, the connection was dropped by unplugging the cable.  I received the connection status update callback almost instantaneously due to Mqtt connection lost:

CONNECTION STATUS UPDATE: DISCONNECTED_RETRYING
CONNECTION STATUS REASON: NO_NETWORK
CONNECTION STATUS THROWABLE: Mqtt connection lost

com.microsoft.azure.sdk.iot.device.exceptions.ProtocolException: Mqtt connection lost
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.exceptions.PahoExceptionTranslator.convertToMqttException(PahoExceptionTranslator.java:75)
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.Mqtt.connectionLost(Mqtt.java:346)
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.connectionLost(CommsCallback.java:292)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms.shutdownConnection(ClientComms.java:423)
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:181)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: Connection lost (32109) - java.net.SocketException: Software caused connection abort: recv failed
	... 8 more
Caused by: java.net.SocketException: Software caused connection abort: recv failed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:940)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:71)
	at java.io.DataInputStream.readByte(DataInputStream.java:265)
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:92)
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:133)
	... 7 more

You might want to try to do the same on your test app without sending messages every second.  We could get a clearer picture on the delay in disconnection status update if there is any.  Thanks.

**Comment by jasmineymlo** [comment] 2018-09-05 17:03
Closing this as I am not able to repro on latest.  Please reopen if needed.  Thanks.

**Comment by az-iot-builder-01** [comment] 2018-09-05 17:03
@kugelbit, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Closed** 2018-09-05 17:03 UTC
Labels: investigation-required
