### ISSUE TITLE
Why the update properties API can not be used any more?

### ISSUE THREAD

**Issue by wuwei3** [Azure/azure-iot-sdk-java#1109] opened 2021-02-05 10:48 UTC
Hi, 

The update propertises API:
https://docs.microsoft.com/en-us/rest/api/iotcentral/devices/updateproperties

it was ok 3days ago, the http method is "PUT", but I saw it change to "patch" 2 days ago.

![up1](https://user-images.githubusercontent.com/46955295/107023784-13f49d00-67e2-11eb-856a-af390cf9a8a7.png)

The problem is, there is no "Body" request any more to commit the request parameter,

![up2](https://user-images.githubusercontent.com/46955295/107023962-54ecb180-67e2-11eb-9fc5-658d9578c30a.png)

even I test with my code, it said "InvalidBody"

![up3](https://user-images.githubusercontent.com/46955295/107024147-a006c480-67e2-11eb-9bf4-d2bf062f13ea.png)

Does Azure is upgrading the API? I have been waiting for 3days, it's urgent to use the API.

AB#9282972

**Comment by wuwei3** [comment] 2021-02-05 10:51
All the IOT central patch request have no "Body" input

**Comment by timtay-microsoft** [comment] 2021-02-05 17:11
This looks like a question about IoT Central, not IoT Hub. This Github issues page is for questions/bugs on the IoT Hub java SDK, not for IoT Central. I'll see if I can find someone to answer this for you though.

**Comment by yang-hai-feng** [comment] 2021-02-05 19:13
IoT Central add incremental update for properties through PATCH, the PUT operation should still work.

**Comment by yang-hai-feng** [comment] 2021-02-05 19:28
@wuwei3 , would you please provide your application id, so I can take a look?

**Comment by wuwei3** [comment] 2021-02-07 02:31
@yang-hai-feng 

![9](https://user-images.githubusercontent.com/46955295/107134682-45c74a00-692f-11eb-8a58-dd8e8711d9f2.png)

the whole model file:

{
  "@id": "dtmi:olcsimulationcentral:testforsensor2uo;1",
  "@type": "Interface",
  "contents": [
    {
      "@id": "dtmi:olcsimulationcentral:testforsensor2uo:sensorProperty;1",
      "@type": "Telemetry",
      "displayName": {
        "en": "sensor property"
      },
      "name": "sensorProperty",
      "schema": {
        "@id": "dtmi:olcsimulationcentral:testforsensor2uo:sensorProperty:schema;1",
        "@type": "Object",
        "displayName": {
          "en": "Object"
        },
        "fields": [
          {
            "@id": "dtmi:olcsimulationcentral:testforsensor2uo:sensorProperty:schema:id;1",
            "displayName": {
              "en": "id"
            },
            "name": "id",
            "schema": "string"
          },
          {
            "@id": "dtmi:olcsimulationcentral:testforsensor2uo:sensorProperty:schema:deviceId;1",
            "displayName": {
              "en": "deviceId"
            },
            "name": "deviceId",
            "schema": "string"
          },
          {
            "@id": "dtmi:olcsimulationcentral:testforsensor2uo:sensorProperty:schema:insertTime;1",
            "displayName": {
              "en": "insertTime"
            },
            "name": "insertTime",
            "schema": "string"
          },
          {
            "@id": "dtmi:olcsimulationcentral:testforsensor2uo:sensorProperty:schema:temperature;1",
            "displayName": {
              "en": "temperature"
            },
            "name": "temperature",
            "schema": "long"
          },
          {
            "@id": "dtmi:olcsimulationcentral:testforsensor2uo:sensorProperty:schema:humidity;1",
            "displayName": {
              "en": "humidity"
            },
            "name": "humidity",
            "schema": "string"
          },
          {
            "@id": "dtmi:olcsimulationcentral:testforsensor2uo:sensorProperty:schema:co2;1",
            "displayName": {
              "en": "co2"
            },
            "name": "co2",
            "schema": "string"
          },
          {
            "@id": "dtmi:olcsimulationcentral:testforsensor2uo:sensorProperty:schema:pollution;1",
            "displayName": {
              "en": "pollution"
            },
            "name": "pollution",
            "schema": "string"
          }
        ]
      }
    },
    {
      "@id": "dtmi:olcsimulationcentral:testforsensor2uo:firmwareUpdate;1",
      "@type": "Property",
      "displayName": {
        "en": "firmware update"
      },
      "name": "firmwareUpdate",
      "schema": "long",
      "writable": true
    },
    {
      "@id": "dtmi:olcsimulationcentral:testforsensor2uo:sendConfigUpdate;1",
      "@type": "Property",
      "displayName": {
        "en": "send config update"
      },
      "name": "sendConfigUpdate",
      "schema": "long",
      "writable": true
    }
  ],
  "displayName": {
    "en": "Interface"
  },
  "@context": [
    "dtmi:iotcentral:context;2",
    "dtmi:dtdl:context;2"
  ]
}


"firmwareUpdate" exist in my model, It was working on "PUT" method before, and I didn't change anything on model, I don't know why the patch not work

**Comment by wuwei3** [comment] 2021-02-07 02:33
From this screen:

![a](https://user-images.githubusercontent.com/46955295/107134732-bb331a80-692f-11eb-97a1-dcdfb6e3fbb9.png)

I think there should be "Body" input box to post the parameter, but it has no any input, could you please tell me how to try it on the page for this command?

https://docs.microsoft.com/en-us/rest/api/iotcentral/devices/updateproperties#code-try-0

**Comment by wuwei3** [comment] 2021-02-07 02:53
> IoT Central add incremental update for properties through PATCH, the PUT operation should still work.

I tried with PUT, still not working

![8](https://user-images.githubusercontent.com/46955295/107135060-a310ca80-6932-11eb-96f8-9a8e78dd7218.png)


Request Id: 4owa4d4s

**Comment by yang-hai-feng** [comment] 2021-02-08 16:33
@wuwei3, thanks for the detail, I have imported your model to my local application, it has an inherited interface, this issue can be reproduced from my side as well, I would have our engineer to check, will get your back once they have the answer.

**Comment by yang-hai-feng** [comment] 2021-02-08 16:46
It turns out that inherited interface should access with components, you can find your component name from here:
![image](https://user-images.githubusercontent.com/14871527/107251653-7075d900-69e9-11eb-96f6-a2a0efc13ea2.png)

PATCH https://iotsimulationcentral.azureiotcentral.com/api/preview/devices/1g0swB29y/components/[your component name]/properties

{
    "firmwareUpdate": 2
}

should work as expected, properties defined under "testforsensor" directly can be access by /devices/[id]/properties, the rest must follow the /devices/[id]/components/[name]/properties.

**Comment by wuwei3** [comment] 2021-02-09 02:23
@yang-hai-feng 

Great, it works

![1](https://user-images.githubusercontent.com/46955295/107306642-31ff1d80-6ac0-11eb-9f94-5950f5d67f23.png)


But I still have one question:

The "try it" function on page

https://docs.microsoft.com/en-us/rest/api/iotcentral/devices/updatecomponentproperties#code-try-0

![2](https://user-images.githubusercontent.com/46955295/107306788-7db1c700-6ac0-11eb-801f-ca08d6ad5dd3.png)

There is no place to put forward the "Body" request like I write in the code, If I just want to try the function on page, where I should to put the body request? I found all "PATCH" request have no body input, only the "GET" and "POST" have.

**Comment by yang-hai-feng** [comment] 2021-02-09 23:30
@wuwei3 , this might be some mistake made on document update, patch body usually is partial of entity that PUT operation used.

**Comment by wuwei3** [comment] 2021-02-10 02:04
Ok, thanks for your help, you helped me a lot, thank you very much, you could close the issue.
And happy Chinese new year to you and your family.

**Comment by yang-hai-feng** [comment] 2021-02-10 02:11
Thanks @wuwei3, Happy Chinese New Year!

**Comment by timtay-microsoft** [comment] 2021-02-10 17:08
Closing this issue as per the above

**Closed by timtay-microsoft** 2021-02-10 17:08 UTC
Labels: IoTSDK, question
