### ISSUE TITLE
SAS token not supported

### ISSUE THREAD

**Issue by carocad** [Azure/azure-iot-sdk-java#170] opened 2017-10-19 09:16 UTC
OS and version used: MAC OS X 10.11.6
Java runtime used: Android JDK 1.7
SDK version used: iot-device-client:1.5.35

# Description of the issue:
I have been trying to use a SAS token to connect to my iot Hub instance but unfortunately I get an error due to it not being supported by the Device. That would be fine if your documentation wouldn't say otherwise (see [here](https://github.com/Azure/azure-iot-sdk-java#device-client-sdk) and [here](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-security)).

Furthermore inside the `DeviceClient` class there is a `shared access signature` resembling the SAS token but it is marked as deprecated:
```java
/**
     * @deprecated as of release 1.2.27 this value is deprecated and will not be replaced.
     * The shared access signature attribute name in a connection string.
     */
    @Deprecated
    public static final String SHARED_ACCESS_TOKEN_ATTRIBUTE = "SharedAccessSignature=";
```

# Code sample exhibiting the issue:
```java
IotHubClientProtocol protocol = IotHubClientProtocol.AMQPS;
// fake sas token, just for clarity
connString = "SharedAccessSignature sr=iothubname.azure-devices.net%2fdevices%2fDeviceId&sig=kPszxZZZZZZZZZZZZZZZZZAhLT%2bV7o%3d&se=1487709501";
client = new DeviceClient(connString, protocol);
```

# Console log of the issue:
```
10-19 10:51:11.375 490-490/bike.cobi.app.debug E/AzureSystemStatePlugin: Exception while opening IoTHub connection: java.lang.IllegalArgumentException: IoT Hub hostName cannot be null.
10-19 11:43:22.335 14487-14487/bike.cobi.app.debug E/AzureSystemStatePlugin: com.microsoft.azure.sdk.iot.device.IotHubConnectionString.validateTerms(IotHubConnectionString.java:242)
                                                                             com.microsoft.azure.sdk.iot.device.IotHubConnectionString.<init>(IotHubConnectionString.java:104)
                                                                             com.microsoft.azure.sdk.iot.device.DeviceClient.<init>(DeviceClient.java:139)
                                                                             bike.cobi.plugin_systemstate.AzureSystemStatePlugin.init(AzureSystemStatePlugin.java:215)
                                                                             bike.cobi.plugin_systemstate.AzureSystemStatePlugin$1.finished(AzureSystemStatePlugin.java:194)
                                                                             bike.cobi.plugin_systemstate.AzureSystemStatePlugin$1.finished(AzureSystemStatePlugin.java:181)
                                                                             bike.cobi.plugin.mycobi.MyCobiPlugin$9$1.onResponse(MyCobiPlugin.java:379)
                                                                             retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:68)
                                                                             android.os.Handler.handleCallback(Handler.java:751)
                                                                             android.os.Handler.dispatchMessage(Handler.java:95)
                                                                             android.os.Looper.loop(Looper.java:154)
                                                                             android.app.ActivityThread.main(ActivityThread.java:6692)
                                                                             java.lang.reflect.Method.invoke(Native Method)
                                                                             com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
                                                                             com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
```

**Comment by prmathur-microsoft** [comment] 2017-10-19 19:46
This is probably a regression for us. We should be supporting SasToken. We will take a look and get back to you.

**Comment by timtay-microsoft** [comment] 2017-10-20 23:47
Looks like the connection string you are using is incomplete. When using SAS token authentication, the full connection string will look like:

HostName=<your_hub_name>.azure-devices.net;DeviceId=<your_device_id>;SharedAccessSignature=SharedAccessSignature sr=<your_hub_name>.azure-devices.net%2Fdevices%2F1&sig=pe9UaBjPDrBX7q8z5%2F1I1Ll8CGYyDhKljSCKVem9Qcc%3D&se=1508715695

The complete connection string you need includes the HostName and DeviceId segments.

Let me know if you need any help on where to find the whole connection string.

**Comment by carocad** [comment] 2017-10-24 11:34
@timtay-microsoft you were right !

It works if the `connString` has the shape that you specified.

However this contradict the documentation that is available online: https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-security

Furthermore the connstring was created with the NodeJs functions specified in this repo: https://github.com/Azure-Samples/functions-node-sas-token/blob/master/GetSasToken-Node/index.js

**Comment by timtay-microsoft** [comment] 2017-10-24 17:36
Glad to hear you got it working! I'm sorry for the confusion from those two sources. I will try to get those sources up to date so no one else runs into the same issue.

I'm going to close this issue for now.

**Closed** 2017-10-24 17:37 UTC
Labels: investigation-required
