### ISSUE TITLE
Rename DeviceTwin package to lowercase devicetwin

### ISSUE THREAD

**Issue by JonathanGiles** [Azure/azure-iot-sdk-java#233] opened 2018-04-30 23:20 UTC
It's standard practice to have package names be all lower case. There are two 'devicetwin' packages in the public API, but one of them is named 'DeviceTwin' (it's fully qualified name is `com.microsoft.azure.sdk.iot.device.DeviceTwin`), which is not standard. I know this is a known problem, but for the sake of tracking, I'm adding this issue :-)

**Comment by timtay-microsoft** [comment] 2018-04-30 23:28
Thanks for filing the issue. This would be a breaking change to make right now, but we will certainly look into this the next time we are allowed to make breaking changes.

**Comment by jasmineymlo** [comment] 2018-05-03 19:03
duplicate of #56.

**Closed by jasmineymlo** 2018-05-03 19:03 UTC
Labels: enhancement
