### ISSUE TITLE
[Java IoTHub Issue: Disconnecting after a period of time MQTT Protocol]

### ISSUE THREAD

**Issue by pperezp306** [Azure/azure-iot-sdk-java#188] opened 2017-12-11 23:37 UTC
- **OS and version used:** Windows 10 

- **Java runtime used:** Java 8 

- **SDK version used:** <VERSION> 

# Description of the issue:
Hello, I have been using the libraries in Java to create a client of the IoT Hub, which is able to receive c2d menssages, but after a while, not all the applications, this error appears:

Dec 11, 2017 3:58:00 PM org.eclipse.paho.client.mqttv3.internal.ClientState checkForActivity
SEVERE: asdess: Timed out as no activity, keepAlive = 20,000 lastOutboundActivity = 1,513,029,460,125 lastInboundActivity = 1,513,029,455,668 time = 1,513,029,480,125 lastPing = 1,513,029,460,125

Does anyone know, what could cause it, or how to fix it? I attach my code.

# Code sample exhibiting the issue:
public class SimulatedDevice {
	
    private static final String connString = "HostName=XXXXXXX-iothub.azure-devices.net;DeviceId=ABC1234567;SharedAccessKey=XXXXXXXXXX";
    private static final IotHubClientProtocol protocol = IotHubClientProtocol.MQTT;
    private static String deviceId = "ABC1234567";
    private static DeviceClient client;
        
    private static class TelemetryDataPoint {
        public String DeviceId;
        public double Temperature;
        public double Humidity;
        public double Preassure;

        public String serialize() {
          Gson gson = new Gson();
          return gson.toJson(this);
        }
    }

    private static class EventCallback implements IotHubEventCallback {
        @Override
        public void execute(IotHubStatusCode status, Object context) {
            Date currentDate = Calendar.getInstance(TimeZone.getDefault()).getTime();
            System.out.println("IoT Hub responded to message with status: " + status.name() + " " + currentDate);
            if (context != null) {
                synchronized (context) {
                  context.notify();
                }
            }
        }
    }
        
    private static class MessageSender implements Runnable {
        public void run()  {
            try {
                double minTemperature = 20;
                double minHumidity = 60;
                Random rand = new Random();

                while (true) {
                    double currentTemperature = minTemperature + rand.nextDouble() * 15;
                    double currentHumidity = minHumidity + rand.nextDouble() * 20;
                    TelemetryDataPoint telemetryDataPoint = new TelemetryDataPoint();
                    telemetryDataPoint.DeviceId = deviceId;
                    telemetryDataPoint.Temperature = currentTemperature;
                    telemetryDataPoint.Humidity = currentHumidity;
                    telemetryDataPoint.Preassure = currentHumidity;

                    String msgStr = telemetryDataPoint.serialize();
                    Message msg = new Message(msgStr);
                    msg.setProperty("temperatureAlert", (currentTemperature > 30) ? "true" : "false");
                    msg.setMessageType(MessageType.DEVICE_TELEMETRY);
                    msg.setMessageId(java.util.UUID.randomUUID().toString()); 
                    System.out.println("Sending: " + msgStr);
                    
                    Object lockobj = new Object();
                    EventCallback callback = new EventCallback();
                    client.sendEventAsync(msg, callback, lockobj);

                    synchronized (lockobj) {
                        lockobj.wait();
                    }
                    Thread.sleep(60000);
                }
            } catch (InterruptedException e) {
              System.out.println("Finished.");
            }
          }
    }
	
    private static class AppMessageCallback implements MessageCallback {
        @Override
        public IotHubMessageResult execute(Message msg, Object context) {
            Date fecha = new Date();
            System.out.println("Received message from hub: " + new String(msg.getBytes()) + " A las: " + fecha.toString() + " ID mensaje " + msg.getMessageId());
            return IotHubMessageResult.COMPLETE;
        }	  
    }
	
    public static void main( String[] args ) throws IOException, URISyntaxException {
        System.out.println("Device ABC1234567 epicenter-iot");
        client = new DeviceClient(connString, protocol);

        MessageCallback callback = new AppMessageCallback();
        MessageSender sender = new MessageSender();
        client.setMessageCallback(callback, null);
        client.open();
        
        ExecutorService executor = Executors.newFixedThreadPool(1);
        executor.execute(sender);

        System.out.println("Press ENTER to exit.");
        System.in.read();
        client.closeNow();
    }
}

# Console log of the issue:
Dec 11, 2017 3:58:00 PM org.eclipse.paho.client.mqttv3.internal.ClientState checkForActivity
SEVERE: asdess: Timed out as no activity, keepAlive = 20,000 lastOutboundActivity = 1,513,029,460,125 lastInboundActivity = 1,513,029,455,668 time = 1,513,029,480,125 lastPing = 1,513,029,460,125

**Comment by timtay-microsoft** [comment] 2017-12-13 23:04
Could you tell us what version of the Java IoT Device SDK you are using? And can you try upgrading to the latest if you haven't already?

[1.6.0 is the latest](https://github.com/Azure/azure-iot-sdk-java/releases/tag/2017-12-2)

**Comment by pperezp306** [comment] 2017-12-14 17:01
Hi timtay! I'm using the latest version of the SDK, the 1.6.0, and the device doesn try to reconnect to the iot hub, sometimes yes, and sometimes not.

**Comment by timtay-microsoft** [comment] 2018-01-04 22:51
I'm having trouble reproducing this error. About how long are you running the above code sample before encountering this error?

**Comment by timtay-microsoft** [comment] 2018-01-29 21:44
@pperezp306 Are you still seeing this issue? And can you provide a more reliable means of reproducing this issue?

**Comment by timtay-microsoft** [comment] 2018-01-30 18:36
I'm looking into the mqtt library that our SDK uses and I found the relevant exception and why it is thrown.

Essentially, the service that you are trying to connect to (The IoT Hub) is going a long period of time without sending anything to your device. Even when the service is not sending a C2D message, it is sending "keep alive" messages over the MQTT connection to ensure that the connection does not close from a timeout.

What this means is that either the IoT Hub service isn't properly sending these "keep alive" messages, or your device is not receiving these "keep alive" messages. I suspect that the service is not at fault here. Is it possible that your device is operating with a very poor internet connection? Also, how frequently are you sending C2D messages in your scenario?

**Comment by pperezp306** [comment] 2018-01-30 19:25
Hello!

The scenario considered is as follows, the devices are programmed only to receive C2D messages, since at the moment we do not need to send D2C information. The equipment is connected to a stable 4G network in most cases and in others to a home wifi network, users are able to send messages to the device so that the computer reacts to these messages.

In addition we could have an independent process, which sends messages to the devices connected to the IoT, but this process in the same way sends the messages at different times when it is executed.

During this time, the error that I explained to you before occurs  randomly, with your explanation could suppose that it could really be a topic of stability in the internet connection.


Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

De: timtay-microsoft<mailto:notifications@github.com>
Enviado: martes, 30 de enero de 2018 12:37 p. m.
Para: Azure/azure-iot-sdk-java<mailto:azure-iot-sdk-java@noreply.github.com>
CC: Pablo Emilio Pérez Paredes<mailto:pablo.prezparedes@outlook.com>; Mention<mailto:mention@noreply.github.com>
Asunto: Re: [Azure/azure-iot-sdk-java] [Java IoTHub Issue: Disconnecting after a period of time MQTT Protocol] (#188)


I'm looking into the mqtt library that our SDK uses and I found the relevant exception and why it is thrown.

Essentially, the service that you are trying to connect to (The IoT Hub) is going a long period of time without sending anything to your device. Even when the service is not sending a C2D message, it is sending "keep alive" messages over the MQTT connection to ensure that the connection does not close from a timeout.

What this means is that either the IoT Hub service isn't properly sending these "keep alive" messages, or your device is not receiving these "keep alive" messages. I suspect that the service is not at fault here. Is it possible that your device is operating with a very poor internet connection? Also, how frequently are you sending C2D messages in your scenario?

**Comment by timtay-microsoft** [comment] 2018-01-30 19:45
Due to the transient nature of this exception, I think it is safe to assume that this stems from temporary issues with internet connection. We will be working on re-vamping our re-connection logic to handle cases like this in the future, but there is very little I could provide you right now to fix this issue from our end.

In the meantime, could you provide the whole stack trace for this exception you are getting? I'd like to add logic to handle it from our end and I need to know where the exception is propagating up through to do that.

**Comment by timtay-microsoft** [comment] 2018-02-05 23:24
@pperezp306  do you have a more complete set of logs for this issue? Right now, it looks like our SDK is handling this error correctly by retrying to establish the connection. Our SDK runs through its complete retry mechanism, and still fails to connect.

If this is the case, then there is nothing our SDK can do to address this issue further because it is an internet connectivity issue. I would still like to see some logs of this issue to confirm that, though.

Also, on your message earlier:
"I'm using the latest version of the SDK, the 1.6.0, and the device doesn try to reconnect to the iot hub, sometimes yes, and sometimes not. all problems appear after a network desconnection."

Do you mean that the SDK does recover from this drop sometimes? And that other times it fails?

**Comment by prmathur-microsoft** [comment] 2018-02-08 19:16
@pperezp306 As per the comment above, we believe there was network drop on your end during re-connection. We are in the process of implementing a better retry logic and you should soon be able to control your re connection scenarios. But until then you have to wait for network to connect back during reconnection. I'm closing this on that note. Feel free to reopen if you have any further questions.

**Closed by prmathur-microsoft** 2018-02-08 19:16 UTC
Labels: investigation-required
