### ISSUE TITLE
[Bug Report] IoT edge ModuleClient open(): An illegal reflective access operation in Mqttv3 when connecting to IoT hub

### ISSUE THREAD

**Issue by derSchtefan** [Azure/azure-iot-sdk-java#1555] opened 2022-05-24 21:33 UTC
# Context

- **OS and version used:** Ubuntu 18.04, moby, iot edge 1.1.13
- **Java runtime used:** 11
- **SDK version used:** Spring: 2.7.0
- azure.iot.device.client.version: 2.0.3
- azure.iot.service.client.version: 2.0.2
- Run in a Oracle VM VirtualBox

## Description of the issue
When running in an IoT edge module, opening a connection created from environment with protocol MQTT, causes `WARNING: Illegal reflective access by org.eclipse.paho.client.mqttv3.internal.NetworkModuleService (file:/app/app.jar) to field java.net.URI.userInfo` and the process stops. See logs below.

Absurdly enough, the very same iot edge configuration runs perfectly on another Oracle VM VirtualBox, or on physical devices, but a specific VirtualBox device has this issue. We checked version numbers, environments, times, time zones, etc. all are identical, but it always fails on one machine, and runs on the others.

## Code sample exhibiting the issue
```java
var msgCallback = new MessageCallbackMqtt(collectorService, objectMapper);

IotHubClientProtocol protocol = IotHubClientProtocol.MQTT;
log.info("Start to create client with MQTT protocol");
this.client = ModuleClient.createFromEnvironment(new UnixDomainSocketChannelImpl(), protocol);
log.info("Client created");
reportedPropertiesSetter.setClient(client);
this.client.setMessageCallback(IotHubCallbacks.INPUT_NAME, msgCallback, client);
this.client.setConnectionStatusChangeCallback(this::connectionStatusChangeCallback, null);

log.info("Opening connection to IoT hub");
this.client.open(true);
```

## Console log of the issue
```
:: Spring Boot :: (v2.7.0)2022-05-24 15:09:24.579 INFO 1 --- [ main] sym.edgemodule.App : Starting App v1.0.0-SNAPSHOT using Java 11.0.15 on 7155d056c403 with PID 1 (/app/app.jar started by root in /app)
2022-05-24 15:09:24.588 INFO 1 --- [ main] sym.edgemodule.App : No active profile set, falling back to 1 default profile: "default"
2022-05-24 15:09:26.607 INFO 1 --- [ main] s.edgemodule.callbacks.IotHubCallbacks : Start to create client with MQTT protocol
2022-05-24 15:09:26.633 INFO 1 --- [ main] c.m.azure.sdk.iot.device.ModuleClient : Creating module client from environment with protocol MQTT...
2022-05-24 15:09:26.634 INFO 1 --- [ main] c.m.azure.sdk.iot.device.ModuleClient : No connection string was configured for this module, so it will get its credentials from the edgelet
2022-05-24 15:09:27.301 INFO 1 --- [ main] m.a.s.i.d.t.ExponentialBackoffWithJitter : NOTE: A new instance of ExponentialBackoffWithJitter has been created with the following properties. Retry Count: 2147483647, Min Backoff Interval: 100, Max Backoff Interval: 10000, Max Time Between Retries: 100, Fast Retry Enabled: true
2022-05-24 15:09:27.307 INFO 1 --- [ main] m.a.s.i.d.t.ExponentialBackoffWithJitter : NOTE: A new instance of ExponentialBackoffWithJitter has been created with the following properties. Retry Count: 2147483647, Min Backoff Interval: 100, Max Backoff Interval: 10000, Max Time Between Retries: 100, Fast Retry Enabled: true
2022-05-24 15:09:27.310 INFO 1 --- [ main] s.edgemodule.callbacks.IotHubCallbacks : Client created
2022-05-24 15:09:27.312 INFO 1 --- [ main] s.edgemodule.callbacks.IotHubCallbacks : Opening connection to IoT hub
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.eclipse.paho.client.mqttv3.internal.NetworkModuleService (file:/app/app.jar) to field java.net.URI.userInfo
WARNING: Please consider reporting this to the maintainers of org.eclipse.paho.client.mqttv3.internal.NetworkModuleService
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

**Comment by brycewang-microsoft** [comment] 2022-05-31 21:52
Thanks for bringing this to our attention! As the warning message pointed, the illegal reflective access operation was caused by `org.eclipse.paho.client.mqttv3.internal.NetworkModuleService`, so it appears that the paho mqtt client was using reflection to access parts of the JDK that are meant for internal use only. 

To disable the warning message, can you add the "--add-opens" flag which explicitly acknowledges the reflective access:
`--add-opens=java.base/java.net=ALL-UNNAMED`
[Ref](https://docs.oracle.com/en/java/javase/11/migrate/index.html#JSMIG-GUID-7BB28E4D-99B3-4078-BDC4-FC24180CE82B)

**Comment by brycewang-microsoft** [comment] 2022-05-31 21:54
Additionally, as this error stems from the MQTT stack, you can also opt to use AMQP on this troublesome device in particular if necessary.

**Comment by derSchtefan** [comment] 2022-06-09 15:12
Thank you. We have decided to scrap that VM and replace it. The error disappeared on its own, but we will have your solution with AMQP ready in case it re-appears. 

Is there a reason all examples utilize MQTT for the local connection by default? Is it because it is faster/less resource intense?

We can close this issue for now if you agree.

**Comment by brycewang-microsoft** [comment] 2022-06-09 22:30
> Is there a reason all examples utilize MQTT for the local connection by default? Is it because it is faster/less resource intense?

Yes, you are correct. Also, MQTT is more widely used in the IoT industry and widely supported among the most popular clouds.

I am closing this issue. Please always feel free to reopen if you observe it further.

**Closed by brycewang-microsoft** 2022-06-09 22:30 UTC
Labels: bug, IoTSDK

**Comment by timtay-microsoft** [comment] 2022-06-10 16:48
> Is it because it is faster/less resource intense?
 
Compared to HTTPS, yes. AMQP and MQTT have roughly the same overhead though.
